### ISSUE TITLE
Table of contents links are incorrect when layout includes <base> element in <head>

### ISSUE THREAD

**Issue by danielfdickinson** [gohugoio/hugo#4735] opened 2018-05-20 06:50 UTC
With Hugo version v0.40.3 using the {{ .TableOfContents }} variable when one has a `<base href="$.Site.BaseURL">` in a `<HEAD>` section, and using `hugo server` fails with Firefox (both ESR and 5x.x

Specifically the relative references for page fragments (e.g. `href="#nameofheading"`) get turned into `http://localhost:1313/#nameofheading` instead of properly being relative (.e.g. on a /section1/page1/ you should get `http://localhost:1313/section1/page1/#nameofheading`).

I'm not not sure if this is a browser issue or a Hugo issue, when using BaseURL (as required by the theme site, becase of issue https://github.com/gohugoio/hugo/issues/2575)

**Comment by cshoredaniel** [comment] 2018-05-28 05:18
This also affects the statically generated pages.

**Comment by jeetsukumaran** [comment] 2018-09-30 21:14
Stale or not, I can confirm that this issue exists across multiple browsers. The Table of Contents generated by Hugo is essentially broken if ``<base href="$.Site.BaseURL">`` is used. A simple fix MIGHT be to generate full URLs in the ToC links instead of just "#anchors"?

**Comment by cshoredaniel** [comment] 2018-10-09 06:40
@jeetsukumaran That seems the obvious solution...not sure how doable it is withing hugo code.

**Comment by cshoredaniel** [comment] 2019-01-05 08:02
@digitalcraftsman for ToC does it still just generated #anchors even with BaseURL, and is there a way to configure it to generate the right URL when using BaseURL?

**Comment by shprink** [comment] 2019-02-23 13:08
Since `BaseURL` is required for Open Graph or Twitter Cards `urls`, `{{ .TableOfContents }}` is therefore not usable at all.

**Comment by siegerts** [comment] 2019-03-04 19:08
Depending on your use case,  I was able to make similar adjustments in the template using:

```
{{ replace .TableOfContents `href="#` (printf `href="%s#` .Permalink) | safeHTML }}
```
Hope that this helps.

**Comment by bep** [comment] 2019-03-04 19:41
This issue has been discussed before. I will redo the ToC integration in the not so distant future and will have this in mind. 

Curious: Why do you need `base href`?

**Comment by cshoredaniel** [comment] 2019-05-01 01:28
```base href``` is required by the Hugo Themes site ... let me scare up the link....

**Comment by cshoredaniel** [comment] 2019-05-01 01:30
It's mentioned in this section https://github.com/gohugoio/hugoThemes#adding-a-theme-to-the-list

**Comment by thombergs** [comment] 2022-01-12 10:31
The table of content outputs anchor links like "#section", whether you run hugo with the `--baseUrl` parameter or not. What changes when you use the `--baseUrl` parameter, however, is that Hugo adds a `<base href="<BASE_URL>">` tag to the page. This tag directs browsers to prefix all relative links with this base URL, and this includes the anchor links. 

This means that when you use the `--baseUrl` parameter, all anchor links break!

To fix this in the table of content, I came up with this workaround:

```
{{ .TableOfContents | replaceRE `href="#(.*)"` (printf `href="%s#%s"` .Page.RelPermalink "$1") | safeHTML }}
```

This prefixes the anchor links with the relative link of the current page. When the browser adds the base URL prefix to that, everything will work fine.

**Comment by jmooring** [comment] 2022-01-12 15:19
Some themes include a `<base>` element in `<head>` in an attempt to handle sites served from a subdirectory (`baseURL = 'https://example.org/my-site/'`). Now that render hooks can produce portable links and images, including a `<base>` element is the not the optimal approach.

However, I believe that the table of contents links should work either way, and have re-opened this issue. We recently fixed a similar problem with the pagination template.

@thombergs Hugo does not insert a `<base>` element. That element is present in one or more of your layouts.

**Comment by thombergs** [comment] 2022-01-12 19:17
@jmooring right, thanks for clearing that up. I didn't check if the `<base>` tag comes from the theme or from Hugo itself. 

Anyway, if Hugo's table of contents would render `/relative_path#anchor` instead of just `#anchor`, that would make the table of content more robust.

**Comment by bep** [comment] 2022-01-12 19:33
>Anyway, if Hugo's table of contents would render /relative_path#anchor instead of just #anchor, that would make the table of content more robust.

I think it would need to be `relative_path#anchor` -- but even so, there are several known issues with using the "base" element with static site generators, so I would recommend not using it. If we implemented the above fix, then the ToC will only work on that particular page which may or may not be OK.

We have another issue that would allow people to render the ToC items as they please -- I'm closing this in favour of #5087

**Closed by bep** 2022-01-12 19:33 UTC
Labels: Keep
