### ISSUE TITLE
Postcss transformation fails with space in filepath in Windows

### ISSUE THREAD

**Issue by jdclarke5** [gohugoio/hugo#7571] opened 2020-08-19 01:52 UTC
## What version of Hugo are you using (hugo version)?

> Hugo Static Site Generator v0.74.3/extended windows/amd64 BuildDate: unknown

## Does this issue reproduce with the latest release?

Yes

## Summary

When running `hugo` command in Windows within a working directory with a space (e.g. `C:\Users\Jackson Clarke\...`), the postcss transformation fails with the following error.

```sh
Error: Error building site: POSTCSS: failed to transform "scss/main.css" (text/css): 'C:\Users\Jackson' is not recognized as an internal or external command, operable program or batch file.
```

Obviously the space means that the path is being interpreted as separate command line arguments. The error would occur at the following line: https://github.com/gohugoio/hugo/blob/6add6d77b48cf0aab8b39d7a2bddedb1aa2a52b8/resources/resource_transformers/postcss/postcss.go#L199

A potential fix would be to ensure such file paths are surround by double quotation marks.

> Note: Running the `hugo_extended_0.74.3_Windows-64bit.zip` build.

**Comment by jmooring** [comment] 2020-08-19 09:07
Duplicate of https://github.com/gohugoio/hugo/issues/7333.

**Closed** 2021-03-26 19:37 UTC
Labels: Duplicate
