### ISSUE TITLE
PostCSS config not working

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#10099] opened 2022-07-17 14:49 UTC
```html
resources.Get "assets/main.css" | resources.PostCSS (dict "config" "mypostcss.config.js")
```

`mypostcss.config.js` as follows:

```js
throw new Error('error from mypostcss.config.js');
```

Hugo does check the `config` exists, but didn't use it.

### What version of Hugo are you using (`hugo version`)?

$ hugo version
```bash
$ hugo version
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
```

### Does this issue reproduce with the latest release?

Yes.

**Comment by bep** [comment] 2022-07-17 18:57
What's the output of `hugo -v`?

**Comment by bep** [comment] 2022-07-17 18:59
OK, I think I remember now, your docs update is correct; this did as intended in an older PostCSS version, though.

**Comment by bep** [comment] 2022-07-17 18:59
I'm closing this in favour of the docs issue.

**Closed by bep** 2022-07-17 18:59 UTC
Labels: Bug, NeedsTriage, Upstream, NeedsUserFeedback
