### ISSUE TITLE
Idea: Shortcode interpreted into data YML

### ISSUE THREAD

**Issue by SiRiLiS** [gohugoio/hugo#8650] opened 2021-06-15 12:48 UTC
Hi,
the shortcodes are not interpreted if into data/language/test.yml. 
I think it is a good idea to have the possibility to insert shortcodes in the datas. :+1: 

Good Day

**Comment by jmooring** [comment] 2021-06-15 14:46
Duplicate of https://github.com/gohugoio/hugo/issues/6703

**Closed by jmooring** 2021-06-15 14:46 UTC
Labels: Duplicate, Proposal
