### ISSUE TITLE
Hugo is unable to find layout

### ISSUE THREAD

**Issue by hanzei** [gohugoio/hugo#4888] opened 2018-06-28 20:49 UTC
Since v0.42 hugo fails to build html files. It seems that the `-t` option not longer works.
### Steps to reproduce
```
$ git clone https://github.com/Hanzei/hugo-test.git
$ cd hugo-theme-introduction/exampleSite/
$ wget https://github.com/gohugoio/hugo/releases/download/v0.42.2/hugo_0.42.2_Linux-64bit.tar.gz
$ tar -xf hugo_0.42.2_Linux-64bit.tar.gz
$ ./hugo -v -t hugo-theme-introduction
WARN 2018/07/04 11:13:43 No translation bundle found for default language "en"
WARN 2018/07/04 11:13:43 Translation func for language en not found, use default.
WARN 2018/07/04 11:13:43 i18n not initialized, check that you have language file (in i18n) that matches the site language or the default language.
INFO 2018/07/04 11:13:43 Using config file: /XYZ/hugo-test/config.toml
Building sites … INFO 2018/07/04 11:13:43 syncing static files to /XYZ/hugo-test/public/
INFO 2018/07/04 11:13:43 found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
WARN 2018/07/04 11:13:43 [en] Unable to locate layout for "page": [blog/single.en.html.html blog/single.html.html blog/single.en.html blog/single.html _default/single.en.html.html _default/single.html.html _default/single.en.html _default/single.html]
WARN 2018/07/04 11:13:43 [en] Unable to locate layout for "page": [projects/single.en.html.html projects/single.html.html projects/single.en.html projects/single.html _default/single.en.html.html _default/single.html.html _default/single.en.html _default/single.html]
WARN 2018/07/04 11:13:43 [en] Unable to locate layout for "page": [page/single.en.html.html page/single.html.html page/single.en.html page/single.html _default/single.en.html.html _default/single.html.html _default/single.en.html _default/single.html]
WARN 2018/07/04 11:13:43 [en] Unable to locate layout for "section": [blog/blog.en.html.html blog/section.en.html.html blog/list.en.html.html blog/blog.html.html blog/section.html.html blog/list.html.html blog/blog.en.html blog/section.en.html blog/list.en.html blog/blog.html blog/section.html blog/list.html section/blog.en.html.html section/section.en.html.html section/list.en.html.html section/blog.html.html section/section.html.html section/list.html.html section/blog.en.html section/section.en.html section/list.en.html section/blog.html section/section.html section/list.html _default/blog.en.html.html _default/section.en.html.html _default/list.en.html.html _default/blog.html.html _default/section.html.html _default/list.html.html _default/blog.en.html _default/section.en.html _default/list.en.html _default/blog.html _default/section.html _default/list.html]
WARN 2018/07/04 11:13:43 [en] Unable to locate layout for "taxonomyTerm": [categories/category.terms.en.html.html categories/terms.en.html.html categories/list.en.html.html categories/category.terms.html.html categories/terms.html.html categories/list.html.html categories/category.terms.en.html categories/terms.en.html categories/list.en.html categories/category.terms.html categories/terms.html categories/list.html taxonomy/category.terms.en.html.html taxonomy/terms.en.html.html taxonomy/list.en.html.html taxonomy/category.terms.html.html taxonomy/terms.html.html taxonomy/list.html.html taxonomy/category.terms.en.html taxonomy/terms.en.html taxonomy/list.en.html taxonomy/category.terms.html taxonomy/terms.html taxonomy/list.html category/category.terms.en.html.html category/terms.en.html.html category/list.en.html.html category/category.terms.html.html category/terms.html.html category/list.html.html category/category.terms.en.html category/terms.en.html category/list.en.html category/category.terms.html category/terms.html category/list.html _default/category.terms.en.html.html _default/terms.en.html.html _default/list.en.html.html _default/category.terms.html.html _default/terms.html.html _default/list.html.html _default/category.terms.en.html _default/terms.en.html _default/list.en.html _default/category.terms.html _default/terms.html _default/list.html]
WARN 2018/07/04 11:13:43 [en] Unable to locate layout for "taxonomy": [tags/tag.en.html.html tags/taxonomy.en.html.html tags/list.en.html.html tags/tag.html.html tags/taxonomy.html.html tags/list.html.html tags/tag.en.html tags/taxonomy.en.html tags/list.en.html tags/tag.html tags/taxonomy.html tags/list.html taxonomy/tag.en.html.html taxonomy/taxonomy.en.html.html taxonomy/list.en.html.html taxonomy/tag.html.html taxonomy/taxonomy.html.html taxonomy/list.html.html taxonomy/tag.en.html taxonomy/taxonomy.en.html taxonomy/list.en.html taxonomy/tag.html taxonomy/taxonomy.html taxonomy/list.html tag/tag.en.html.html tag/taxonomy.en.html.html tag/list.en.html.html tag/tag.html.html tag/taxonomy.html.html tag/list.html.html tag/tag.en.html tag/taxonomy.en.html tag/list.en.html tag/tag.html tag/taxonomy.html tag/list.html _default/tag.en.html.html _default/taxonomy.en.html.html _default/list.en.html.html _default/tag.html.html _default/taxonomy.html.html _default/list.html.html _default/tag.en.html _default/taxonomy.en.html _default/list.en.html _default/tag.html _default/taxonomy.html _default/list.html]
WARN 2018/07/04 11:13:44 [en] Unable to locate layout for "home": [page/index.en.html.html page/home.en.html.html page/list.en.html.html page/index.html.html page/home.html.html page/list.html.html page/index.en.html page/home.en.html page/list.en.html page/index.html page/home.html page/list.html index.en.html.html home.en.html.html list.en.html.html index.html.html home.html.html list.html.html index.en.html home.en.html list.en.html index.html home.html list.html _default/index.en.html.html _default/home.en.html.html _default/list.en.html.html _default/index.html.html _default/home.html.html _default/list.html.html _default/index.en.html _default/home.en.html _default/list.en.html _default/index.html _default/home.html _default/list.html]
WARN 2018/07/04 11:13:44 [en] Unable to locate layout for "section": [projects/projects.en.html.html projects/section.en.html.html projects/list.en.html.html projects/projects.html.html projects/section.html.html projects/list.html.html projects/projects.en.html projects/section.en.html projects/list.en.html projects/projects.html projects/section.html projects/list.html section/projects.en.html.html section/section.en.html.html section/list.en.html.html section/projects.html.html section/section.html.html section/list.html.html section/projects.en.html section/section.en.html section/list.en.html section/projects.html section/section.html section/list.html _default/projects.en.html.html _default/section.en.html.html _default/list.en.html.html _default/projects.html.html _default/section.html.html _default/list.html.html _default/projects.en.html _default/section.en.html _default/list.en.html _default/projects.html _default/section.html _default/list.html]
WARN 2018/07/04 11:13:44 [en] Unable to locate layout for "taxonomyTerm": [tags/tag.terms.en.html.html tags/terms.en.html.html tags/list.en.html.html tags/tag.terms.html.html tags/terms.html.html tags/list.html.html tags/tag.terms.en.html tags/terms.en.html tags/list.en.html tags/tag.terms.html tags/terms.html tags/list.html taxonomy/tag.terms.en.html.html taxonomy/terms.en.html.html taxonomy/list.en.html.html taxonomy/tag.terms.html.html taxonomy/terms.html.html taxonomy/list.html.html taxonomy/tag.terms.en.html taxonomy/terms.en.html taxonomy/list.en.html taxonomy/tag.terms.html taxonomy/terms.html taxonomy/list.html tag/tag.terms.en.html.html tag/terms.en.html.html tag/list.en.html.html tag/tag.terms.html.html tag/terms.html.html tag/list.html.html tag/tag.terms.en.html tag/terms.en.html tag/list.en.html tag/tag.terms.html tag/terms.html tag/list.html _default/tag.terms.en.html.html _default/terms.en.html.html _default/list.en.html.html _default/tag.terms.html.html _default/terms.html.html _default/list.html.html _default/tag.terms.en.html _default/terms.en.html _default/list.en.html _default/tag.terms.html _default/terms.html _default/list.html]
WARN 2018/07/04 11:13:44 [en] Unable to locate layout for "404": [404.html theme/404.html]

                   | EN  
+------------------+----+
  Pages            | 10  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  5  Steps to reproduce
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 11 
```
### Hugo v0.41
```
./hugo -v -t hugo-theme-introduction
INFO 2018/07/04 13:31:06 Using config file /XYZhugo-test/config.toml
Building sites … INFO 2018/07/04 13:31:06 syncing static files to /XYZ/hugo-test/public/
WARN 2018/07/04 13:31:06 No translation bundle found for default language "en"
WARN 2018/07/04 13:31:06 Translation func for language en not found, use default.
WARN 2018/07/04 13:31:06 i18n not initialized, check that you have language file (in i18n) that matches the site language or the default language.
INFO 2018/07/04 13:31:06 found taxonomies: map[string]string{"tag":"tags", "category":"categories"}

                   | EN  
+------------------+----+
  Pages            | 29  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     | 35  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 55 ms
```

If you comment out `theme` in `config.toml` hugo will panic:
```
$ hugo -v -t hugo-theme-introduction
panic: AllThemes not set

goroutine 1 [running]:
github.com/gohugoio/hugo/hugolib/filesystems.createThemesOverlayFs(0xc42010ca00, 0x0, 0xc42045d0f8, 0x412378, 0x30, 0xdf1360, 0x1, 0xc4202faf90)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/hugolib/filesystems/basefs.go:572 +0x315
github.com/gohugoio/hugo/hugolib/filesystems.(*sourceFilesystemsBuilder).Build(0xc4204b28c0, 0xc4202faf90, 0xc4200281e4, 0x25)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/hugolib/filesystems/basefs.go:258 +0x2ee
github.com/gohugoio/hugo/hugolib/filesystems.NewBase(0xc42010ca00, 0x0, 0x0, 0x0, 0x0, 0x0, 0xdd0000000000000e)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/hugolib/filesystems/basefs.go:232 +0x7e5
github.com/gohugoio/hugo/helpers.NewPathSpecWithBaseBaseFsProvided(0xc4204b2500, 0x101f300, 0xc4201bbdc0, 0x0, 0xc420440420, 0x20, 0x20)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/helpers/pathspec.go:59 +0x9f
github.com/gohugoio/hugo/helpers.NewPathSpec(0xc4204b2500, 0x101f300, 0xc4201bbdc0, 0xc420440420, 0x0, 0x1519180)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/helpers/pathspec.go:41 +0x48
github.com/gohugoio/hugo/deps.New(0xc4204b4200, 0xc4204b2500, 0xc4201bbdc0, 0x101f420, 0xc4200cd680, 0x100e5c0, 0x0, 0xc420440420, 0x100e540, 0xc420440400, ...)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/deps/deps.go:126 +0xb0
github.com/gohugoio/hugo/hugolib.applyDepsIfNeeded(0xc4204b4200, 0xc4204b2500, 0xc4201bbdc0, 0x101f420, 0xc4200cd680, 0x100e5c0, 0x0, 0xc420440420, 0x100e540, 0xc420440400, ...)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:190 +0x321
github.com/gohugoio/hugo/hugolib.newHugoSites(0xc4204b4200, 0xc4204b2500, 0x0, 0x101f420, 0xc4200cd680, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:134 +0x24d
github.com/gohugoio/hugo/hugolib.NewHugoSites(0xc4204b4200, 0xc4204b2500, 0x0, 0x101f420, 0xc4200cd680, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:227 +0xf5
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig.func3()
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/commands/commandeer.go:212 +0x15f
sync.(*Once).Do(0xc4204968b0, 0xc420453a98)
	/build/hugo/parts/go/build/src/sync/once.go:44 +0xbe
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc4204d08c0, 0xc420490001, 0x4, 0x10)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/commands/commandeer.go:194 +0x570
github.com/gohugoio/hugo/commands.newCommandeer(0x1, 0xc42007c1e0, 0x100b080, 0xc420498690, 0xc4204987b0, 0x0, 0x0, 0x0, 0xd84980, 0xc42001e001, ...)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/commands/commandeer.go:105 +0x141
github.com/gohugoio/hugo/commands.initializeConfig(0xd80001, 0xc42007c1e0, 0x100b080, 0xc420498690, 0xc4204987b0, 0xc420453c08, 0xc420453bd8, 0x0)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/commands/hugo.go:111 +0x76
github.com/gohugoio/hugo/commands.(*commandsBuilder).newHugoCmd.func1(0xc420368a00, 0xc42049df20, 0x0, 0x3, 0x0, 0x0)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/commands/commands.go:151 +0x97
github.com/gohugoio/hugo/vendor/github.com/spf13/cobra.(*Command).execute(0xc420368a00, 0xc42001e0d0, 0x3, 0x3, 0xc420368a00, 0xc42001e0d0)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/vendor/github.com/spf13/cobra/command.go:756 +0x468
github.com/gohugoio/hugo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420368a00, 0xc420498690, 0xc420174640, 0xc420453ee8)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/vendor/github.com/spf13/cobra/command.go:846 +0x30a
github.com/gohugoio/hugo/commands.Execute(0xc42001e0d0, 0x3, 0x3, 0xc420453f78, 0x40597c, 0xc42002a1d8, 0x0)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/commands/hugo.go:77 +0xbe
main.main()
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/main.go:27 +0x7b
```

**Comment by bep** [comment] 2018-06-28 20:53
What does "-t ." mean? I assume this is a path issue vs the `--themesDir` setting. Does it work if you either

1. Put the theme inside /themes
2. Set themesDir in config.xml

**Comment by Hanzei** [comment] 2018-06-28 21:01
`-t` sets the theme to use. (` -t, --theme string               theme to use (located in /themes/THEMENAME/)`)
Neither 1. nor 2. works.

**Comment by bep** [comment] 2018-06-28 21:15
>-t sets the theme to use.

That I understand. But is your theme really named "."?

**Comment by Hanzei** [comment] 2018-06-28 21:45
No. But this way I can use the current directory as theme.
I don't think this is the root of the problem. It also happens if I put the theme the "normal way" into `themes`.

**Comment by Hanzei** [comment] 2018-06-28 21:45
No. But this way I can use the current directory as theme.
I don't think this is the root of the problem. It also happens if I put the theme the "normal way" into `themes`.

**Comment by Hanzei** [comment] 2018-07-04 12:17
I updated the Steps to reproduce to make the problem more clear.

**Comment by Hanzei** [comment] 2018-07-04 12:18
If you comment out `theme` in `config.toml` hugo will panic:
```
$ hugo -v -t hugo-theme-introduction
panic: AllThemes not set

goroutine 1 [running]:
github.com/gohugoio/hugo/hugolib/filesystems.createThemesOverlayFs(0xc42010ca00, 0x0, 0xc42045d0f8, 0x412378, 0x30, 0xdf1360, 0x1, 0xc4202faf90)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/hugolib/filesystems/basefs.go:572 +0x315
github.com/gohugoio/hugo/hugolib/filesystems.(*sourceFilesystemsBuilder).Build(0xc4204b28c0, 0xc4202faf90, 0xc4200281e4, 0x25)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/hugolib/filesystems/basefs.go:258 +0x2ee
github.com/gohugoio/hugo/hugolib/filesystems.NewBase(0xc42010ca00, 0x0, 0x0, 0x0, 0x0, 0x0, 0xdd0000000000000e)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/hugolib/filesystems/basefs.go:232 +0x7e5
github.com/gohugoio/hugo/helpers.NewPathSpecWithBaseBaseFsProvided(0xc4204b2500, 0x101f300, 0xc4201bbdc0, 0x0, 0xc420440420, 0x20, 0x20)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/helpers/pathspec.go:59 +0x9f
github.com/gohugoio/hugo/helpers.NewPathSpec(0xc4204b2500, 0x101f300, 0xc4201bbdc0, 0xc420440420, 0x0, 0x1519180)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/helpers/pathspec.go:41 +0x48
github.com/gohugoio/hugo/deps.New(0xc4204b4200, 0xc4204b2500, 0xc4201bbdc0, 0x101f420, 0xc4200cd680, 0x100e5c0, 0x0, 0xc420440420, 0x100e540, 0xc420440400, ...)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/deps/deps.go:126 +0xb0
github.com/gohugoio/hugo/hugolib.applyDepsIfNeeded(0xc4204b4200, 0xc4204b2500, 0xc4201bbdc0, 0x101f420, 0xc4200cd680, 0x100e5c0, 0x0, 0xc420440420, 0x100e540, 0xc420440400, ...)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:190 +0x321
github.com/gohugoio/hugo/hugolib.newHugoSites(0xc4204b4200, 0xc4204b2500, 0x0, 0x101f420, 0xc4200cd680, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:134 +0x24d
github.com/gohugoio/hugo/hugolib.NewHugoSites(0xc4204b4200, 0xc4204b2500, 0x0, 0x101f420, 0xc4200cd680, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:227 +0xf5
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig.func3()
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/commands/commandeer.go:212 +0x15f
sync.(*Once).Do(0xc4204968b0, 0xc420453a98)
	/build/hugo/parts/go/build/src/sync/once.go:44 +0xbe
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc4204d08c0, 0xc420490001, 0x4, 0x10)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/commands/commandeer.go:194 +0x570
github.com/gohugoio/hugo/commands.newCommandeer(0x1, 0xc42007c1e0, 0x100b080, 0xc420498690, 0xc4204987b0, 0x0, 0x0, 0x0, 0xd84980, 0xc42001e001, ...)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/commands/commandeer.go:105 +0x141
github.com/gohugoio/hugo/commands.initializeConfig(0xd80001, 0xc42007c1e0, 0x100b080, 0xc420498690, 0xc4204987b0, 0xc420453c08, 0xc420453bd8, 0x0)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/commands/hugo.go:111 +0x76
github.com/gohugoio/hugo/commands.(*commandsBuilder).newHugoCmd.func1(0xc420368a00, 0xc42049df20, 0x0, 0x3, 0x0, 0x0)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/commands/commands.go:151 +0x97
github.com/gohugoio/hugo/vendor/github.com/spf13/cobra.(*Command).execute(0xc420368a00, 0xc42001e0d0, 0x3, 0x3, 0xc420368a00, 0xc42001e0d0)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/vendor/github.com/spf13/cobra/command.go:756 +0x468
github.com/gohugoio/hugo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420368a00, 0xc420498690, 0xc420174640, 0xc420453ee8)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/vendor/github.com/spf13/cobra/command.go:846 +0x30a
github.com/gohugoio/hugo/commands.Execute(0xc42001e0d0, 0x3, 0x3, 0xc420453f78, 0x40597c, 0xc42002a1d8, 0x0)
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/commands/hugo.go:77 +0xbe
main.main()
	/build/hugo/parts/hugo/go/src/github.com/gohugoio/hugo/main.go:27 +0x7b
```

**Comment by felicianotech** [comment] 2018-07-05 20:09
I can confirm that this issue affects me as well.

The `-t` flag for `hugo serve` is suppose to be passed the name of a theme you want to serve the site with, which will override the set theme name in the Hugo config file. This is no longer working.

I did some testing and this flag broke with the Hugo v0.42 release. Using Hugo v0.41 and below (I tried down to v0.30.1) has the `-t` flag working.

**Comment by jygastaud** [comment] 2018-07-05 22:34
I also confirm that issue with `-t` flag

**Comment by jygastaud** [comment] 2018-07-05 22:37
That issue look like a duplicate of #4851

**Comment by moorereason** [comment] 2018-10-03 03:03
Closing as duplicate of #4851

**Closed by moorereason** 2018-10-03 03:03 UTC
