### ISSUE TITLE
Allow Summary to take a arbitary amount of characters

### ISSUE THREAD

**Issue by Splizard** [gohugoio/hugo#1142] opened 2015-05-15 00:04 UTC
Add a {{ SummaryAmount 250 }} function for example which will only generate the specified amount of characters in the summary not including words that are on the cut off. Either that or be able to specify it as a site variable or the like.

**Comment by bep** [comment] 2015-05-15 00:08
It would have to be a site-wide config constant. (or, it wouldn't HAVE to be, but what you suggest would be too much work to be worth it).

**Comment by bep** [comment] 2015-05-15 00:11
Also, if you want per-page sumarylength, you can do it all manual style by adding `<!--more-->` after your summary.

**Comment by Splizard** [comment] 2015-05-15 00:45
The use-case is that the text needs a fixed maximum size that I don't want to manually input  tags which I currently do.

**Comment by bep** [comment] 2015-05-15 20:39
It's pretty easy to extract the summary length into site config. I know @spf13 isn't a fan of too many knobs, so he'll be the judge.

**Comment by bep** [comment] 2017-03-01 09:15
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by hyacinthus** [comment] 2017-03-21 02:40
In chinese, there is no space between words, so you can't count it in normal way.

If I use any theme which have ".Summary" in list page, the summary will **very very long**.

Can we have a way to count summary by character?

**Comment by bep** [comment] 2017-03-21 08:15
@hyacinthus try to set `hasCJKLanguage = true` in your Site config.

**Comment by hyacinthus** [comment] 2017-03-21 13:51
@bep thank you , it works.  But the summary is a little short now...

**Comment by bep** [comment] 2017-03-21 13:55
@hyacinthus cannot have it all ... you may try the truncate func with full content.

**Comment by hyacinthus** [comment] 2017-03-21 14:05
I switch from wordpress, and already have many posts, without truncate function.

Anyway, I'll use a none summary theme. Looks more cleaner.

**Comment by rdwatters** [comment] 2017-03-22 22:54
@bep thanks for the cc. 

Updated here: https://hugodocs.info/content-management/summaries/#hugo-defined-automatic-summary-splitting

BTW, think I should add a third shortcode for a "tip" admonition? Right now I have just "note" and "warning," and "tip" is pretty common. Maybe I can convince Bud to make it pretty for me too.

**Comment by bep** [comment] 2017-07-18 22:15
Close this as a duplicate of #3693

**Closed by bep** 2017-07-18 22:15 UTC
Labels: Enhancement, Keep
