### ISSUE TITLE
Manual content summaries insert with `<p>` tag

### ISSUE THREAD

**Issue by jstamant** [gohugoio/hugo#8910] opened 2021-08-20 23:41 UTC
While designing my own theme, I came across a curious issue:

When using the `{{ .Summary }}` page variable to manually generate a summary in combination with the `<!--more-->` tag in a post, Hugo inserts the summary wrapped with a `<p>` tag.

Here's what I'm expecting:

When using the `{{ .Summary }}` page variable to automatically generate summaries, Hugo simply inserts the summary text in the template - not wrapped with any HTML tags.

<pre>
$ hugo version
hugo v0.87.0+extended linux/amd64 BuildDate=unknown
</pre>

I am using the latest release. So, yes, this issue is reproducible in the latest release.

#### `summary.html` template file
```handlebars
<p class="excerpt">
  {{ .Summary }}
</p>
{{- if .Truncated }}
<p>
  <a href="{{ .RelPermalink }}">Read more...</a>
</p>
{{- end }}
```

### Reproducible erroneous behavior

See this example with manual summary generation:

#### `test.md`
```markdown
---
title: "Test"
date: 2021-08-08T13:33:29-05:00
draft: false
---

Lorem ipsum dolor sit amet.<!--more-->
```
#### Result
```html
<p class="excerpt">
  <p>Lorem ipsum dolor sit amet.</p>
</p>
<p>
  <a href="/posts/test/">Read more...</a>
</p>
```

### Expected behavior

Now compare this to what I'm expecting:

#### `test.md`
```markdown
---
title: "Test"
date: 2021-08-08T13:33:29-05:00
draft: false
---

Lorem ipsum dolor sit amet.
```
#### Result
```html
<p class="excerpt">
  <p>Lorem ipsum dolor sit amet.</p>
</p>
<p>
  <a href="/posts/test/">Read more...</a>
</p>
```

**Comment by jmooring** [comment] 2021-08-21 18:37
The built-in mechanisms for summary assignment and rendering have [created confusion](https://discourse.gohugo.io/search?q=summary) for several years.

<https://gohugo.io/content-management/summaries>

Method|Description|Transformation|Single Lines Wrapped with `<p>`
:--|:--|:--|:--
A|Automatic Summary|Stripped to plain text|false
B|Manual Summary|Markdown processor|true
C|Frontmatter Summary|Markdown processor|false

As a template author, you have no idea whether `.Summary` has been passed through the markdown processor, or if has been stripped to plain text. Additionally, if the `.Summary` has been passed through the markdown processor, you have no idea whether or not it has been wrapped within a `<p>` element.

In no case do you have access to the raw value. 

This is [unexpected](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) and inconsistent with the way we handle `.Content`.

Related:
- <https://github.com/gohugoio/hugo/issues/7926>
- <https://github.com/gohugoio/hugo/issues/7372>
- <https://github.com/gohugoio/hugo/issues/6296>
- <https://github.com/gohugoio/hugo/issues/1503>

Somewhat related, applicable to HTML content pages:
- <https://github.com/gohugoio/hugo/issues/6686>
- <https://github.com/gohugoio/hugo/issues/6513>

Somewhat related (embedded templates):
- <https://github.com/gohugoio/hugo/issues/8562>

**Comment by ptgott** [comment] 2022-01-08 12:06
@bep @jmooring What would you think the solution should be? Looks like some choices are:

- **Returning raw Markdown for all three summary mechanisms with no `<p>` tags:** That way, a template author could call, say, `.RenderString` if they wanted HTML. At the same time, I'm not sure why you'd want an unprocessed summary unless you were creating one manually via frontmatter.
- **Returning processed HTML for all three summary mechanisms:** The downside is that an author might want control over how they render a summary, e.g., in a `<span>` rather than a `<p>`.
- **Changing the `Page` API** to include `.Summary` and `.RawSummary` properties. The first returns processed HTML and the second returns raw Markdown.
- **Leaving this functionality as-is and documenting it:** This won't break any existing templates, at least.

**Comment by okaestne** [comment] 2022-02-15 16:02
I think we all can agree that this is unexpected behavior. I would have never guessed that the `<p>` tags are missing when using the manual summary method just be defining the point using `<!--more-->`. I also stumbled upon this while designing my template because I tried add CSS styles to the p elements.

I can also understand that there are use-cases for a summary in form of raw text. Therefore I would prefer @ptgott 3rd suggestion most.

**Comment by rodrigo-brito** [comment] 2022-02-22 00:54
I'm using this combination of filters to retrieve the RAW Summary:
```
{{ .Summary | plainify | htmlUnescape | chomp }}}
```

**Comment by cskartikey** [comment] 2023-03-30 10:13
The unexpected behavior still exists as of now.

**Comment by jmooring** [comment] 2024-09-19 16:13
Closing in favor of #11440.

**Closed by jmooring** 2024-09-19 16:13 UTC
Labels: Bug, Keep, Feature: Summary
