### ISSUE TITLE
`.Content` doesnt rebuild when dynamically-called partial inside hooks modified

### ISSUE THREAD

**Issue by pamubay** [gohugoio/hugo#10423] opened 2022-11-07 15:42 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.106.0-DEV-77fc74a5b20f50298ac4a1cd88e436932fc2226f+extended linux/amd64 BuildDate=2022-10-28T12:41:15Z VendorInfo=mage
</pre>

### Does this issue reproduce with the latest release?

**Yes**

### Bug

In __server mode__ `.Content` doesnt rebuild when dynamically-called partial template inside markdown render hooks modified

### How-to reproduce

1. start `hugo server`, then open browser.
2. modify `layouts/partials/dynamic-render-link.html`,
3. Add some random character
4. Changes detected, site rebuild but `.Content` doesnt update with new changes

All markdown hooks affected, `link`,`image`, `heading`, `codeblock`. 

Also tested using `--disableFastRender` still __doesnt work__.

### Demo

https://github.com/pamubay/markdown-hooks-dynamic-call

Thank you.

**Comment by jmooring** [comment] 2022-11-07 23:03
Similar to, or perhaps a duplicate of, https://github.com/gohugoio/hugo/issues/8863.

**Comment by bep** [comment] 2022-11-08 08:36
I'm closing this as a duplicate. I'm currently working on a more robust setup that should handle this.

**Closed by bep** 2022-11-08 08:36 UTC
Labels: Bug, Duplicate
