### ISSUE TITLE
Cannot download go modules behing an http proxy since 0.91.0

### ISSUE THREAD

**Issue by ebousse** [gohugoio/hugo#9732] opened 2022-03-30 08:03 UTC
I'm using version `0.91.0` to build a hugo website that relies on go modules. The process is running on a remote Gitlab runner that is behind an http proxy. I made sure that `HTTPS_PROXY` and `HTTP_PROXY` are well set with the right values.

However, when running `hugo`, here is the result:

```
hugo: downloading modules …
go mod download: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5@v5.0.0-20220325140950-3ee572954ab1: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /tmp/modules/filecache/modules/pkg/mod/cache/vcs/03eb10a0f5c758e6f57cba4cdf4b81a47570b50b3518aecff1c475ee0039297d: exit status 128:
	fatal: unable to access 'https://github.com/wowchemy/wowchemy-hugo-modules/': Failed to connect to github.com port 443 after 31426 ms: Operation timed out
Error: failed to download modules: failed to execute 'go [mod download]': failed to execute binary "go" with args [mod download]: go mod download: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5@v5.0.0-20220325140950-3ee572954ab1: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /tmp/modules/filecache/modules/pkg/mod/cache/vcs/03eb10a0f5c758e6f57cba4cdf4b81a47570b50b3518aecff1c475ee0039297d: exit status 128:
	fatal: unable to access 'https://github.com/wowchemy/wowchemy-hugo-modules/': Failed to connect to github.com port 443 after 31426 ms: Operation timed out
 *errors.errorString
hugo: collected modules in 93064 ms
Total in 93066 ms
```

This kind of timeout is typically what happens when the http proxy is not used, that's why I believe this is somehow related to the problem.

But here is the interesting part: **the problem does not appear when using versions `0.89.0`to `0.90.1`.**, and only started happening with `0.91.0` onwards (up until the current `0.95.0`).

**Comment by jmooring** [comment] 2022-03-30 16:06
Duplicate of #9333.

See this comment for required configuration settings:
<https://github.com/gohugoio/hugo/issues/9333#issuecomment-1022435616>

**Closed by jmooring** 2022-03-30 16:06 UTC
Labels: Duplicate

**Comment by ebousse** [comment] 2022-03-31 07:54
Perfect, thank you! Fixed adding this to `config.yml`:

```yaml
security:
  exec:
    osEnv: ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|HOME|SSH_AUTH_SOCK|USERPROFILE|XDG_CONFIG_HOME|HTTP_PROXY|HTTPS_PROXY)$']
```
