### ISSUE TITLE
Bad escape sequence in string at all date formats

### ISSUE THREAD

**Issue by scriptstar** [gohugoio/hugo#7247] opened 2020-05-05 15:34 UTC
What version of Hugo are you using (hugo version)? Hugo 0.69.2
Does this issue reproduce with the latest release? Yes

With the latest version (0.69.2) of HUGO, the datePublished and dateModified are producing a date with a bad escape sequence. The site is failing with Google structured data tool.

<pre>
"dateModified":"2020-05-04 00:00:00 \x2b0000 UTC"
</pre>

<img width="1378" alt="Bad escape sequence in string" src="https://user-images.githubusercontent.com/178812/81084574-f52d4700-8eed-11ea-9cc0-006445b70555.png">

**Comment by bep** [comment] 2020-05-05 15:37
How are you producing this JSON?

**Comment by scriptstar** [comment] 2020-05-05 15:47
Hi @bep Not JSON, it is HTML, and I got it by right-clicking the webpage to see the page source. I don't have the previous versions of Hugo, and I can't confirm that.

**Comment by moorereason** [comment] 2020-05-05 16:33
This looks like a duplicate of #6695.

**Closed** 2020-05-05 17:14 UTC
Labels: Duplicate
