### ISSUE TITLE
Crash when having an unclosed shortcut

### ISSUE THREAD

**Issue by ingorichter** [gohugoio/hugo#7106] opened 2020-03-29 19:32 UTC
I was recently updating my blog and at some point hugo stopped updating. I figured out that I killed hugo with having an unclosed (in this case empty closing tag) shortcut in my draft.

{{< highlight bash >}}
~/projects:
{{< >}}

Other situations with shortcuts like `closing tag for shortcut XX does not match start tag` are handled more gracefully and less disruptive. Perhaps there is a way to do the same here.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.68.3/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by jmooring** [comment] 2020-07-05 13:13
Tested again with 0.73. This:

```
{{< highlight bash >}}
~/projects:
{{< >}}
```

produces this error message:

> failed to extract shortcode: BUG: template info not set

but it does not crash.

**Comment by jmooring** [comment] 2021-03-27 16:23
Duplicate of https://github.com/gohugoio/hugo/issues/6866.

**Closed by jmooring** 2021-03-27 16:23 UTC
Labels: Duplicate
