### ISSUE TITLE
Invalid float value ERROR in 0.56.3

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#6168] opened 2019-08-06 08:45 UTC
I just sent PR https://github.com/gohugoio/hugoThemes/pull/670 to bump the Hugo version used in Netlify to build the Themes Showcase and the ERROR count in the deploy log went up.

The following theme demos are breaking due to `Invalid float value:` for `'min_version'` in `theme.toml` 

@bep Is this something that you can fix or do we need to notify theme authors?

```
11:26:59 AM:  ==== PROCESSING  osprey  ======
11:26:59 AM: Building site for theme osprey using default content to ../themeSite/static/theme/osprey/
11:26:59 AM: Error: failed to read module config for "osprey" in "/opt/build/repo/osprey/theme.toml": unmarshal failed: Near line 8 (last key parsed 'min_version'): Invalid float value: "0.24.1"
11:26:59 AM: FAILED to create exampleSite for osprey


11:27:21 AM:  ==== PROCESSING  hugo-alageek-theme  ======
11:27:21 AM: Building site for theme hugo-alageek-theme using default content to ../themeSite/static/theme/hugo-alageek-theme/
11:27:21 AM: Error: failed to read module config for "hugo-alageek-theme" in "/opt/build/repo/hugo-alageek-theme/theme.toml": unmarshal failed: Near line 8 (last key parsed 'min_version'): Invalid float value: "0.40.3"
11:27:21 AM: FAILED to create exampleSite for hugo-alageek-theme


11:27:21 AM:  ==== PROCESSING  cocoa-eh-hugo-theme  ======
11:27:21 AM: Building site for theme cocoa-eh-hugo-theme using default content to ../themeSite/static/theme/cocoa-eh-hugo-theme/
11:27:21 AM: Error: failed to read module config for "cocoa-eh-hugo-theme" in "/opt/build/repo/cocoa-eh-hugo-theme/theme.toml": unmarshal failed: Near line 8 (last key parsed 'min_version'): Invalid float value: "0.20.2"
11:27:21 AM: FAILED to create exampleSite for cocoa-eh-hugo-theme

11:27:29 AM:  ==== PROCESSING  hugo-theme-zen  ======
11:27:29 AM: Building site for theme hugo-theme-zen using default content to ../themeSite/static/theme/hugo-theme-zen/
11:27:29 AM: Error: failed to read module config for "hugo-theme-zen" in "/opt/build/repo/hugo-theme-zen/theme.toml": unmarshal failed: Near line 8 (last key parsed 'min_version'): Invalid float value: "0.55.0"
11:27:29 AM: FAILED to create exampleSite for hugo-theme-zen


11:28:00 AM:  ==== PROCESSING  beg  ======
11:28:00 AM: Building site for theme beg using config "/opt/build/repo/_script/hugoThemeSite/config-beg.toml" to ../themeSite/static/theme/beg/
11:28:00 AM: Error: failed to read module config for "beg" in "/opt/build/repo/beg/theme.toml": unmarshal failed: Near line 8 (last key parsed 'min_version'): Invalid float value: "0.42.2"
11:28:00 AM: FAILED to create demo site for beg

11:28:21 AM:  ==== PROCESSING  gohugo-theme-ananke  ======
11:28:21 AM: gohugo-theme-ananke is whitelisted
11:28:21 AM: Building site for theme gohugo-theme-ananke using its own exampleSite to ../themeSite/static/theme/gohugo-theme-ananke/
11:28:21 AM: Error: failed to read module config for "gohugo-theme-ananke" in "/opt/build/repo/gohugo-theme-ananke/theme.toml": unmarshal failed: Near line 11 (last key parsed 'min_version'): Invalid float value: "0.30.2"
11:28:21 AM: FAILED to create exampleSite for gohugo-theme-ananke

```

**Comment by XhmikosR** [comment] 2019-08-06 09:54
This is duplicate of #6162

**Comment by bep** [comment] 2019-08-06 10:26
It's a duplicate and I'm not sure what the solution is, but it should ultimately be fixed in the source (theme).

**Closed by bep** 2019-08-06 10:26 UTC

**Comment by onedrawingperday** [comment] 2019-08-06 11:27
Ok. Thanks. I will do the merry-go-round.

**Comment by naz1719** [comment] 2020-06-09 16:01
Hi
By the way the issue is still reproducing following for quickstart tutorial on windows 10
![image](https://user-images.githubusercontent.com/16464652/84171531-96766280-aa83-11ea-92dc-5802ed1a65b9.png)
