### ISSUE TITLE
Slug not overriding folder name in bundle 

### ISSUE THREAD

**Issue by MarkRosemaker** [gohugoio/hugo#7124] opened 2020-04-03 15:05 UTC
I'm using the latest release (v0.68.3-157669A0 windows/amd64 BuildDate: 2020-03-24T12:04:36Z).

I'm creating a site out of generated content files. I want to keep the prefix "gen_" (and a number to sort the files) for generated folders. The slug should not include "gen_" or the number.

I have the following folder structure in content:

- courses
  - gen_1 My Lesson/_index.md
    - gen_1 My Unit/index.md

I defined the `slug` parameters as "my-lesson" and "my-unit", respectively. However, the former is not used. The resulting permalinks are "courses/gen_1-my-lesson/" and "courses/gen_1-my-lesson/my-unit", respectively -- so at least it works for the leaf. 

I know I can define something like

```
[permalinks]
  courses = "/:slug/"
```
in my config, but that has no effect on the lesson/branch page.

Any help is greatly appreciated. Thank you in advance. Stay happy and healthy everybody!

**Comment by MarkRosemaker** [comment] 2020-04-30 15:00
Unfortunately, this issue is not resolved. Can anybody help?

**Comment by MarkRosemaker** [comment] 2020-06-11 11:03
This is a still a problem. What's the process of getting this issue addressed?

**Comment by davidsneighbour** [comment] 2020-06-11 11:33
> Any help is greatly appreciated. 

Put `slug: slugstring` into the frontmatter of gen_1 My Lesson/_index.md

> What's the process of getting this issue addressed?

Go to discourse.gohugo.io and ask the community (this is most probably not a bug in Hugo). Prepare a public repo where we can check the actual structure of your site and how frontmatter and configuration are set up.

For the future: it's always better to go over there first. Most of the time it's not something that needs to be fixed in Hugo, but more something in your theme or setup.

**Comment by adrian-cy** [comment] 2020-06-12 19:15
@davidsneighbour I'm running into the same issue with i18n for a section name. I've tried adding a slug in the front matter of the section's _index.md, but it's not taking it and is generating the pages in the section based on the folder name.

> hugo version
Hugo Static Site Generator v0.70.0/extended darwin/amd64 BuildDate: unknown

**Comment by adrian-cy** [comment] 2020-06-12 19:21
FYI, I've just updated to latest which is v0.72.0 and still having the issue where the slug is being ignored

**Comment by MarkRosemaker** [comment] 2020-06-16 14:10
> Put `slug: slugstring` into the frontmatter of gen_1 My Lesson/_index.md

I've done that and it's exactly my question why that doesn't work?

> Go to discourse.gohugo.io and ask the community (this is most probably not a bug in Hugo). Prepare a public repo where we can check the actual structure of your site and how frontmatter and configuration are set up.

I posted here because I assumed it was a bug if something that is standard practice (putting "slug" in frontmatter) doesn't work. However, I'll post there as well.

[My minimal working example is now set up here.](https://github.com/MarkRosemaker/hugo-mwe-bundle-slugs)

**Comment by MarkRosemaker** [comment] 2020-06-16 16:34
[I've been told in the forum](https://discourse.gohugo.io/t/slug-not-overriding-folder-name-in-bundle/26302) that "a `slug` defined in front matter is applicable to single pages (example: contact.md or index.md), not list pages (example: _index.md)".

This seems very counter-intuitive to me. In [Content Organization](https://gohugo.io/content-management/organization/#index-pages-_indexmd), the documentation says:

> ## Index Pages: _index.md 
> _index.md has a special role in Hugo. It allows you to **add front matter** and content to your list templates.

and then

> ## slug
> A content’s slug is either name.extension or name/. The value for slug is determined by
> - the name of the content file (e.g., lollapalooza.md) OR
> - **front matter overrides**

That seems to suggest that I can override the `slug` in an index page since it's not mentioned anywhere that `slug` only applies to leaf pages.

And why would it not be possible to define a `slug` in an index page and have it cascade down to child pages? That's standard behavior on WordPress, for example.

I ask that this issue be labelled "feature request" or "proposal" so that this might get implemented. Thank you in advance!

**Comment by falcon03** [comment] 2021-05-26 19:58
I can confirm this bug: even with the latest stable version (hugo 0.83.1), the slug specified in the "_index.md" file corresponding to a section is ignored when generating it and the pages that belong to it.

**Comment by internetfreak** [comment] 2021-08-23 01:33
Still an issue with 0.87. This would make localized urls way easier than manually setting any url

**Comment by Ran-n** [comment] 2022-04-08 16:48
this is still an issue. Any workarrounds?

**Comment by rosszurowski** [comment] 2022-04-20 15:35
I'm also running into this. Trying to order content folders alphabetically and then override the name with a `slug` parameter doesn't work for branch bundles:

```
docs/01_introduction/_index.md
docs/01_introduction/instructions/index.md
docs/01_introduction/getting-started/index.md
docs/02_features/_index.md
docs/02_features/feature-a/index.md
docs/02_features/feature-b/index.md
```

Inside either of the `01_introduction/_index.md` files, setting:

```
slug: introduction
```

Doesn't seem to have an impact. The final URL is `/docs/01_introduction` rather than `/docs/introduction`. Setting the `url` parameter explicitly to `url: docs/introduction` does seem to work correctly.

**Comment by Jamesits** [comment] 2022-05-04 12:36
Run into this issue on 0.98.0. Setting `url` works for me as a workaround.

**Comment by johnnovak** [comment] 2022-12-02 07:02
Looks like nobody's fixing bugs around here 😐 This was raised in 2020, and yes, it's still a serious issues, I've just ran into it...

**Comment by varna9000** [comment] 2023-03-13 13:08
Has anyone sorted this even with workaround?

**Comment by jmooring** [comment] 2023-03-13 20:33
Going back to the OP's description, it seems like there are two issues here:

1\) When you set `permalinks` in site configuration, whether the site is monolingual or multilingual, the `permalink` for the given top level section does not apply to the section page itself (e.g., `content/posts/_index.md`). This would be addressed with resolution of https://github.com/gohugoio/hugo/issues/8523.

2\) The existing documentation does not state that `slug` in front matter is not applicable to section pages. This will be addressed shortly with resolution of https://github.com/gohugoio/hugoDocs/issues/1997.

If you want to express your support for https://github.com/gohugoio/hugo/issues/8523, I suggest you "thumbs up" the intitial comment, instead of adding additional "I need this too" comments to the issue. Speaking for myself, I am annoyed by "I need this too" comments and, consequently, sometimes I am less inclined to even look at the issue.

Given the two referenced issues and proposed resolutions, I would like to close this as a duplicate.

**Comment by varna9000** [comment] 2023-03-13 21:02
@jmooring thanks for the thorough reference!

**Comment by johnnovak** [comment] 2023-03-13 21:47
> Speaking for myself, I am annoyed by "I need this too" comments and, consequently, sometimes I am less inclined to even look at the issue.

That's an interesting position from a maintainer...

**Comment by jmooring** [comment] 2023-05-17 19:10
Closing in favor of https://github.com/gohugoio/hugo/issues/8523.

**Closed by jmooring** 2023-05-17 19:10 UTC
