### ISSUE TITLE
404 Support：failed to load Chinese resource

### ISSUE THREAD

**Issue by kiosk404** [gohugoio/hugo#10290] opened 2022-09-18 14:12 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.103.0-beebf2afb09a7be36cf12bdec8a99ae9286504e2 linux/amd64 BuildDate=2022-09-15T16:23:56Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
yes 

Hello , I upgraded to the latest version （103）of hugo ，but failed to load Chinese resource (when url link contains chinese) ，it will show 404 web page。
like this
![2022-09-18_22-06](https://user-images.githubusercontent.com/30208100/190911252-0b390299-93e3-4047-844a-89f5371be5f5.png)

and  version  102  is correct。

![2022-09-18_22-11](https://user-images.githubusercontent.com/30208100/190911354-15d7d9d1-2df3-41ea-8fa4-379499b73647.png)

**Comment by bep** [comment] 2022-09-18 14:49
Duplicate of https://github.com/gohugoio/hugo/issues/10287

**Closed by bep** 2022-09-18 14:49 UTC
Labels: Bug, NeedsTriage
