### ISSUE TITLE
Detect redundant aliases

### ISSUE THREAD

**Issue by geeknoid** [gohugoio/hugo#5732] opened 2019-03-03 15:23 UTC
It'd be great if Hugo flagged when the same alias is used by multiple markdown file. 

Folks have been cutting & pasting files in our site and accidentally copy over aliases. Hugo processes these in some order and one of the definition wins. I'd rather get a build time error.

Thanks.

**Comment by bep** [comment] 2019-03-03 16:19
This is a duplicate of #3113 -- they must at least be fixed by the same patch.

**Closed by bep** 2019-03-03 16:19 UTC
