### ISSUE TITLE
public/ folder is set with an abnormal date

### ISSUE THREAD

**Issue by fu-sen** [gohugoio/hugo#7074] opened 2020-03-20 00:51 UTC
### What version of Hugo are you using (`hugo version`)?

```
> hugo version
Hugo Static Site Generator v0.67.1-4F44227B windows/amd64 BuildDate: 2020-03-15T19:32:32Z
```

### Does this issue reproduce with the latest release?

This is the current latest version: https://github.com/gohugoio/hugo/releases/tag/v0.67.1

___

The `public/` folder created by running `hugo` on Windows has an abnormal date:
![スクリーンショット 2020-03-20 09 45 00](https://user-images.githubusercontent.com/5434159/77127483-00d4c380-6a90-11ea-8bca-ffd6a066aa75.jpg)

Explorer hides this date, but you can see it in some apps. (Eg FileZilla)
This happens at least in Windows 10.

___

It is also reported in discourse:

https://discourse.gohugo.io/t/v67-x-command-hugo-d-set-wrong-date-for-directory-public/24090

**Comment by fu-sen** [comment] 2020-03-20 01:08
I have confirmed that this problem occurs regardless of Windows.
Also, it has already occurred in v0.65.3.
![スクリーンショット 2020-03-20 10 04 59](https://user-images.githubusercontent.com/5434159/77128190-88233680-6a92-11ea-9b46-c27b7e7bd953.jpg)

**Comment by fu-sen** [comment] 2020-03-20 01:09
I updated the information. This happens regardless of Windows.

**Comment by timotk** [comment] 2020-03-21 12:06
Can confirm this issue on Linux with Hugo v0.67.0. It's causing `exa`, a Rust `ls` replacement to fail. That issue is [here](https://github.com/ogham/exa/issues/596).

**Comment by moorereason** [comment] 2020-03-21 14:03
Duplicate of #6161.

**Closed by moorereason** 2020-03-21 14:03 UTC
