### ISSUE TITLE
Hugo crashes with customized permalinks

### ISSUE THREAD

**Issue by max-arnold** [gohugoio/hugo#5200] opened 2018-09-11 12:44 UTC
These two options lead to a crash (Hugo 0.48, MacOS):

```
disableKinds = ["section"]

[permalinks]
articles = "/:sections/:slug/"
```

```
% hugo --cleanDestinationDir

Total in 5 ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2b0 pc=0x18bb943]

goroutine 1 [running]:
github.com/gohugoio/hugo/hugolib.pageToPermalinkSections(0xc00050a000, 0xc0000a2702, 0x8, 0x8, 0xc000018088, 0x1, 0xa)
	/go/src/github.com/gohugoio/hugo/hugolib/permalinks.go:197 +0x53
github.com/gohugoio/hugo/hugolib.pathPattern.Expand(0xc0000a2700, 0x11, 0xc00050a000, 0x8, 0xc0000d7828, 0x1af2101, 0x4)
	/go/src/github.com/gohugoio/hugo/hugolib/permalinks.go:116 +0x2e6
github.com/gohugoio/hugo/hugolib.(*Page).initTargetPathDescriptor(0xc00050a000, 0xc000498418, 0xc000498410)
	/go/src/github.com/gohugoio/hugo/hugolib/page_paths.go:112 +0x2bb
github.com/gohugoio/hugo/hugolib.(*Page).initPaths(0xc00050a000, 0x0, 0x0)
	/go/src/github.com/gohugoio/hugo/hugolib/page_paths.go:153 +0x2f
github.com/gohugoio/hugo/hugolib.(*HugoSites).assemble(0xc0004adb80, 0xc0002439e8, 0x0, 0x0)
	/go/src/github.com/gohugoio/hugo/hugolib/hugo_sites_build.go:211 +0x282
github.com/gohugoio/hugo/hugolib.(*HugoSites).Build(0xc0004adb80, 0x0, 0xc00037dde0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19bb2e0)
	/go/src/github.com/gohugoio/hugo/hugolib/hugo_sites_build.go:65 +0x168
github.com/gohugoio/hugo/commands.(*commandeer).buildSites(0xc0004d2370, 0x0, 0xc000243a80)
	/go/src/github.com/gohugoio/hugo/commands/hugo.go:623 +0x5d
github.com/gohugoio/hugo/commands.(*commandeer).fullBuild.func3(0x0, 0x0)
	/go/src/github.com/gohugoio/hugo/commands/hugo.go:298 +0x2e
github.com/gohugoio/hugo/commands.(*commandeer).fullBuild(0xc0004d2370, 0x0, 0x0)
	/go/src/github.com/gohugoio/hugo/commands/hugo.go:310 +0x16f
github.com/gohugoio/hugo/commands.(*commandeer).build(0xc0004d2370, 0x0, 0x0)
	/go/src/github.com/gohugoio/hugo/commands/hugo.go:343 +0xaf
github.com/gohugoio/hugo/commands.(*commandsBuilder).newHugoCmd.func1(0xc00022ef00, 0xc000493150, 0x0, 0x1, 0x0, 0x0)
	/go/src/github.com/gohugoio/hugo/commands/commands.go:160 +0xc3
github.com/spf13/cobra.(*Command).execute(0xc00022ef00, 0xc0000a0030, 0x1, 0x1, 0xc00022ef00, 0xc0000a0030)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0xc00022ef00, 0xc000492de0, 0xc00023def8, 0x1011e12)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/gohugoio/hugo/commands.Execute(0xc0000a0030, 0x1, 0x1, 0xc, 0xc00023df88, 0x10051e0, 0xc000080058)
	/go/src/github.com/gohugoio/hugo/commands/hugo.go:76 +0xb8
main.main()
	/go/src/github.com/gohugoio/hugo/main.go:27 +0x7a
```

Btw, `articles = "/:section/:slug/"` doesn't crash.

Sample repo https://github.com/max-arnold/testblog (config needs to be tweaked as described above)

**Comment by onedrawingperday** [comment] 2018-09-11 13:14
Of course you would get a runtime error with this combination of options.

Maybe there should be a console error...

**Comment by max-arnold** [comment] 2018-09-11 13:56
Then why it doesn't crash with singular section placeholder `articles = "/:section/:slug/"`(as opposed to plural one `articles = "/:sectionS/:slug/"`)?

**Comment by onedrawingperday** [comment] 2018-09-11 14:11
I don't understand the question. 

You have disabled `"section "`and then you want to use `:sections` in the permalink.? 

Why is that? `:sections` are the children of `"section`" 

And in your second example I suppose that Hugo doesn't crash since you have already disabled `:section` and it returns `nil`

Not sure what you're looking for with this issue. But then again I may be wrong...

**Comment by max-arnold** [comment] 2018-09-11 14:19
As far as I understand, `disableKinds = ["section"]` disables rendering of section index pages. It should not affect page urls.

**Comment by onedrawingperday** [comment] 2018-09-11 14:36
Um no... it disables the entire section + nested sections. The permalink values are drawn from those. See: https://gohugo.io/content-management/urls/#permalink-configuration-values

Anyway this isn't the forum. Feel free to open a topic there to post your questions.

I am closing this issue because this is not a bug. (if the others think otherwise they can re-open)

**Closed by onedrawingperday** 2018-09-11 14:36 UTC

**Comment by max-arnold** [comment] 2018-09-11 14:51
According to the docs, it only disables section indexes, not the pages and their urls:
https://gohugo.io/templates/section-templates/
https://discourse.gohugo.io/t/new-disablekinds-option/5507

**Comment by onedrawingperday** [comment] 2018-09-11 14:56
No... you got this wrong.

`disableKinds` is about [Kinds](https://gohugo.io/templates/section-templates/#page-kinds)

Again, your questions need to be posted in the forum not here...

**Comment by max-arnold** [comment] 2018-09-12 04:38
My (lame) attempt to fix the crash:

```
diff --git a/hugolib/site_sections.go b/hugolib/site_sections.go
index 15b96e1a..b5915307 100644
--- a/hugolib/site_sections.go
+++ b/hugolib/site_sections.go
@@ -166,10 +166,6 @@ func (p *Page) Sections() Pages {
 func (s *Site) assembleSections() Pages {
        var newPages Pages

-       if !s.isEnabled(KindSection) {
-               return newPages
-       }
-
        // Maps section kind pages to their path, i.e. "my/section"
        sectionPages := make(map[string]*Page)

@@ -210,7 +206,9 @@ func (s *Site) assembleSections() Pages {
                        // We only create content-file-less sections for the root sections.
                        sect = s.newSectionPage(p.sections[0])
                        sectionPages[sectionKey] = sect
-                       newPages = append(newPages, sect)
+                       if s.isEnabled(KindSection) {
+                               newPages = append(newPages, sect)
+                       }
                        found = true
                }

@@ -220,10 +218,11 @@ func (s *Site) assembleSections() Pages {
                        if !rootFound {
                                sect = s.newSectionPage(p.sections[0])
                                sectionPages[p.sections[0]] = sect
-                               newPages = append(newPages, sect)
+                               if s.isEnabled(KindSection) {
+                                       newPages = append(newPages, sect)
+                               }
                        }
                }
-
                if found {
                        pagePath := path.Join(sectionKey, sectPageKey, strconv.Itoa(i))
                        inPages.Insert([]byte(pagePath), p)
@@ -245,7 +244,9 @@ func (s *Site) assembleSections() Pages {
                                sect = s.newSectionPage(sectionPath[len(sectionPath)-1])
                                sect.sections = sectionPath
                                sectionPages[sectionKey] = sect
-                               newPages = append(newPages, sect)
+                               if s.isEnabled(KindSection) {
+                                       newPages = append(newPages, sect)
+                               }
                        }
                }
        }
```

**Comment by onedrawingperday** [comment] 2018-09-12 05:55
@max-arnold 

This is not the place to post all that, that's why we have a Forum 

This project is small and has rules. You need to respect the rules.
