### ISSUE TITLE
An empty ul + li pair in {{ .TableOfContents }}

### ISSUE THREAD

**Issue by MKPlato** [gohugoio/hugo#11280] opened 2023-07-23 06:38 UTC
### What version of Hugo are you using (`hugo version`)?
hugo v0.115.3+extended

### Does this issue reproduce with the latest release?

In hugo.yml
```
markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true
    tableOfContents:
      endLevel: 3
      ordered: true
      startLevel: 2
```

In markdown

```
## head 2
##### head 5
text
```

This will output an empty `<ul><li></li></ul>` like this:

```
<nav id="TableOfContents">
  <ul>
    <li><a>head 3</a>
      <ul>
        <li></li>
      </ul>
    </li>
  </ul>
</nav>
```

**Comment by jmooring** [comment] 2023-07-23 06:53
Duplicate of https://github.com/gohugoio/hugo/issues/7128

**Closed by jmooring** 2023-07-23 06:53 UTC
Labels: Bug, NeedsTriage
