### ISSUE TITLE
Empty Li is Generated in Table of Contents When the 1st Item is H3

### ISSUE THREAD

**Issue by dwy6626** [gohugoio/hugo#8903] opened 2021-08-18 14:10 UTC
As title, when I wrote an page with:

```markdown
### H3

## H2

### H3
```

the `.TableOfContents` will generate an extra empty `<li>`:

(in line 3)

```html
<nav id="TableOfContents">
    <ul>
        <li>
        <ul>
            <li><a href="#h3">H3</a></li>
        </ul>
        </li>
        <li><a href="#h2">H2</a>
        <ul>
            <li><a href="#h3-1">H3</a></li>
        </ul>
        </li>
    </ul>
</nav>
```

screenshot: 

![image](https://user-images.githubusercontent.com/31836528/129913398-85e768ac-2432-426d-aa33-44a28490715b.png)

Minmal reproduce code: https://github.com/dwy6626/hugo-toc-test

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.87.0-B0C541E4 linux/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
yes

**Comment by bep** [comment] 2021-08-18 14:39
* What markup would you expect in this case?
* Why do you need this odd heading levels?

**Comment by jmooring** [comment] 2021-08-18 14:51
Duplicate of https://github.com/gohugoio/hugo/issues/7128.

**Closed** 2021-08-18 15:05 UTC

**Comment by dwy6626** [comment] 2021-08-18 16:08
- I expected no extra `<li>` in L3:
```html
    <nav id="TableOfContents">
        <ul>
            <ul>
                <li><a href="#h3">H3</a></li>
            </ul>
            </li>
            <li><a href="#h2">H2</a>
            <ul>
                <li><a href="#h3-1">H3</a></li>
            </ul>
        </ul>
    </nav>
```
![image](https://user-images.githubusercontent.com/31836528/129932759-5e29cc92-5c37-4543-8d8e-2192b2da759a.png)

- If I write an article with title (h1, will not be listed in TOC) -> some small topic (h3) -> another paragraph (h2) -> another small topic (h3), it will encounter this issue.
