### ISSUE TITLE
.File.Anything without backing file throws error instead of warning

### ISSUE THREAD

**Issue by darix** [gohugoio/hugo#12068] opened 2024-02-19 21:15 UTC
### What version of Hugo are you using (`hugo version`)?

```
$ hugo version
hugo v0.123.0+extended linux/amd64 BuildDate=unknown VendorInfo=https://build.opensuse.org/package/show/home:darix:apps/hugo
```
Build description here: https://build.opensuse.org/package/view_file/home:darix:apps/hugo/hugo.spec?expand=1

### Does this issue reproduce with the latest release?

https://github.com/darktable-org/dtdocs.git

`./tools/build-all.sh`

```
build-dtorg[3838]: ERROR render of "taxonomy" failed: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/_default/baseof.html:10:4"
: execute of template failed: template: _default/list.html:10:4: executing "_default/list.html" at <partial "toc.html" .>: error calling partial: "/home/hugo/dtdocs-master/themes/hugo-darkta
ble-docs-pdf-theme/layouts/partials/toc.html:6:4": execute of template failed: template: partials/toc.html:6:4: executing "partials/toc.html" at <partial "toc_gen.html" .>: error calling par
tial: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/partials/toc_gen.html:7:38": execute of template failed: template: partials/toc_gen.html:7:38: executing "partial
s/toc_gen.html" at <.File.UniqueID>: error calling UniqueID: runtime error: invalid memory address or nil pointer dereference
build-dtorg[3838]: ERROR render of "section" failed: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/_default/baseof.html:10:4":
 execute of template failed: template: _default/list.html:10:4: executing "_default/list.html" at <partial "toc.html" .>: error calling partial: "/home/hugo/dtdocs-master/themes/hugo-darktab
le-docs-pdf-theme/layouts/partials/toc.html:6:4": execute of template failed: template: partials/toc.html:6:4: executing "partials/toc.html" at <partial "toc_gen.html" .>: error calling part
ial: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/partials/toc_gen.html:7:38": execute of template failed: template: partials/toc_gen.html:7:38: executing "partials
/toc_gen.html" at <.File.UniqueID>: error calling UniqueID: runtime error: invalid memory address or nil pointer dereference
build-dtorg[3838]: ERROR render of "page" failed: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/_default/baseof.html:10:4": ex
ecute of template failed: template: _default/single.html:10:4: executing "_default/single.html" at <partial "toc.html" .>: error calling partial: "/home/hugo/dtdocs-master/themes/hugo-darkta
ble-docs-pdf-theme/layouts/partials/toc.html:6:4": execute of template failed: template: partials/toc.html:6:4: executing "partials/toc.html" at <partial "toc_gen.html" .>: error calling par
tial: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/partials/toc_gen.html:7:38": execute of template failed: template: partials/toc_gen.html:7:38: executing "partial
s/toc_gen.html" at <.File.UniqueID>: error calling UniqueID: runtime error: invalid memory address or nil pointer dereference
build-dtorg[3838]: INFO  build:  step render pages 935 content 786 duration 2.533136365s
```

**Comment by CamilleScholtz** [comment] 2024-02-19 21:19
I think I am running into the same issue. Builds fine in 0.122. It seems to be something with lists/taxonomies.

Error:

```
Watching for changes in /Users/camille/Developer/Home/reactionair.nl/{assets,content,data,layouts,static}
Watching for config changes in /Users/camille/Developer/Home/reactionair.nl/config.toml
Start building sites …
hugo v0.123.0-3c8a4713908e48e6523f058ca126710397aa4ed5+extended darwin/arm64 BuildDate=2024-02-19T16:32:38Z VendorInfo=brew

ERROR render of "term" failed: "/Users/camille/Developer/Home/reactionair.nl/layouts/_default/list.html:6:10": execute of template failed: template: _default/list.html:6:10: executing "main" at <.File.UniqueID>: error calling UniqueID: runtime error: invalid memory address or nil pointer dereference
Built in 3128 ms
Error: error building site: render: failed to render pages: render of "term" failed: "/Users/camille/Developer/Home/reactionair.nl/layouts/_default/list.html:6:10": execute of template failed: template: _default/list.html:6:10: executing "main" – File is nil; wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}
```

I think that `/layouts/_default/authors.terms.html` is no longer being used for the author taxonomy in this case, where it was used before.

**Comment by jmooring** [comment] 2024-02-19 21:41
@CamilleScholtz Are you calling .File.UniqueID from a template? If yes, what happens if you wrap it as described at the end of the message?

**Comment by CamilleScholtz** [comment] 2024-02-19 21:48
It then fails at some other point (getting an image somewhere, which returns nil). To me it seems that something in the template lookup order changed that makes it fail with 123. I could give you access to my private repository if that helps?

**Comment by jmooring** [comment] 2024-02-19 21:56
> I could give you access to my private repository of the Hugo site in question if that helps

Yes please. My email address is listed on my GitHub profile.

**Comment by jmooring** [comment] 2024-02-19 22:02
@CamilleScholtz I am unable to build your site due to "ERROR failed to fetch remote resource: Forbidden"

**Comment by darix** [comment] 2024-02-19 22:03
A selection of ours that seem to trigger:

- https://github.com/darktable-org/dtorg
- https://github.com/darktable-org/dtdocs
- https://github.com/darktable-org/luadocs

**Comment by CamilleScholtz** [comment] 2024-02-19 22:05
> @CamilleScholtz I am unable to build your site due to "ERROR failed to fetch remote resource: Forbidden"

Just pushed a fix for this, this is also something that before issued a warning (I think) instead of an error ;)

**Comment by jmooring** [comment] 2024-02-19 22:11
@darix Here's what I did:

```text
git clone --recurse-submodules https://github.com/darktable-org/dtorg
cd dtorg
hugo
```

Here's what I got:

```text
                   | EN   
-------------------+------
  Pages            | 462  
  Paginator pages  |  19  
  Non-page files   | 718  
  Static files     |  84  
  Processed images | 429  
  Aliases          |  28  
  Cleaned          |   0  
```

**Comment by darix** [comment] 2024-02-19 22:18
it is the pdf build that fails for the docs.

**Comment by jmooring** [comment] 2024-02-19 22:25
@darix I was able to build both dtdocs and luadocs iusing the `hugo -c config-pdf.yaml` command. No problems.

I am not dismissing your problem. We just haven't figured out how to reproduce it yet.

**Comment by darix** [comment] 2024-02-19 22:33
that's why i mentioned the tools build script above which does those things for you :)

**Comment by jmooring** [comment] 2024-02-19 22:34
@CamilleScholtz Here's what I did:

```text
git clone --recurse-submodules https://github.com/CamilleScholtz/your_private_repo
cd your_private_repo
hugo
```

Same result... ERROR failed to fetch remote resource: Forbidden

**Comment by jmooring** [comment] 2024-02-19 22:39
@darix Here's what I did:

```text
git clone --recurse-submodules https://github.com/darktable-org/dtdocs
cd dtdocs/
./tools/build-pdf.sh
```

Here's what I got:

```text
                   | EN  | FR | DE | EO | ES | GL | IT | PL | PT BR | UK | NL  
-------------------+-----+----+----+----+----+----+----+----+-------+----+-----
  Pages            | 317 |  7 |  7 |  7 |  7 |  7 |  7 |  7 |     7 |  7 |  7  
  Paginator pages  |   0 |  0 |  0 |  0 |  0 |  0 |  0 |  0 |     0 |  0 |  0  
  Non-page files   | 203 |  1 |  1 |  1 |  1 |  1 |  1 |  1 |     1 |  1 |  1  
  Static files     |   2 |  2 |  2 |  2 |  2 |  2 |  2 |  2 |     2 |  2 |  2  
  Processed images |   0 |  0 |  0 |  0 |  0 |  0 |  0 |  0 |     0 |  0 |  0  
  Aliases          |   1 |  0 |  0 |  0 |  0 |  0 |  0 |  0 |     0 |  0 |  0  
  Cleaned          |   0 |  0 |  0 |  0 |  0 |  0 |  0 |  0 |     0 |  0 |  0  
```

**Comment by darix** [comment] 2024-02-19 22:59
i can still reproduce this consistently:

```
#!/bin/bash

HUGO_HOME="/srv/volumes/darktable.org/hugo"
HUGO_HOME_DIR="/home/hugo"
HUGO_ENTRYPOINT="${HUGO_HOME_DIR}/bin/run.sh"

echo "Running dtorg build with '${HUGO_HOME}' mapped to '${HUGO_HOME_DIR}' with entrypoint '${HUGO_ENTRYPOINT}'"

withlock --wait=1 --quiet /srv/volumes/darktable.org/build-dtorg.lock \ 
docker run \
  --volume=${HUGO_HOME}:${HUGO_HOME_DIR} \
  --pull=always \
  --rm -i -t \
  registry.opensuse.org/home/darix/apps/containers/hugo:latest bash
```

```
cd dtdocs-master
```

i modified the build-all.sh to only build pdf

```
#!/usr/bin/env bash

base_url="$1"

#go to project root
PROJECT_ROOT="$(cd `dirname $0`/..; pwd)"
cd "$PROJECT_ROOT"

#generate translated files
./tools/generate-translations.sh --no-update

#build html site
# ./tools/build-html.sh "$base_url"

#build epubs
# ./tools/build-epub.sh

#build pdfs
./tools/build-pdf.sh
```

```
INFO  Translation func for language fr not found, use default.                                                                                                                                
INFO  Translation func for language de not found, use default.                                                                                                                                
INFO  Translation func for language eo not found, use default.                                                                                                                                
INFO  Translation func for language es not found, use default.                                 
INFO  Translation func for language gl not found, use default.                                 
INFO  Translation func for language it not found, use default.                                                                                                                                
INFO  Translation func for language pl not found, use default.                                                                                                                                
INFO  Translation func for language pt_br not found, use default.                                                                                                                             
INFO  Translation func for language uk not found, use default.                                                                                                                                
INFO  Translation func for language nl not found, use default.                                 
Watching for changes in /home/hugo/dtdocs-master/{archetypes,content,data,layouts,static,themes}                                                                                              
Watching for config changes in /home/hugo/dtdocs-master/config-pdf.yaml
Start building sites …                                                                                                                                                                        
hugo v0.123.0+extended linux/amd64 BuildDate=unknown VendorInfo=https://build.opensuse.org/package/show/home:darix:apps/hugo

INFO  static: syncing static files to / duration 222.84µs
INFO  build:  step process substep collect files 2437 files_total 2437 duration 62.492149ms
INFO  build:  step process duration 62.613448ms                                                
INFO  build:  step assemble duration 32.175894ms
INFO  build:  step render substep pages site en outputFormat html duration 841.389796ms
INFO  build:  step render substep pages site en outputFormat rss duration 31.365049ms
INFO  build:  step render substep pages site fr outputFormat html duration 698.525767ms
INFO  build:  step render substep pages site fr outputFormat rss duration 18.119602ms
INFO  dynacache: adjusted partitions' max size evicted 498 numGC 23 limit 2.84 GB alloc 0.27 GB totalAlloc 1.08 GB
INFO  build:  step render substep pages site de outputFormat html duration 850.793079ms
INFO  build:  step render substep pages site de outputFormat rss duration 20.749523ms
ERROR render of "home" failed: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/_default/baseof.html:10:4": execute of template failed: template: index.html:10:4: executing "index.html" at <partial "toc.html" .>: error calling partial: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/partials/toc.html:6:4": execute of template failed: 
template: partials/toc.html:6:4: executing "partials/toc.html" at <partial "toc_gen.html" .>: error calling partial: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/partials/toc_gen.html:7:38": execute of template failed: template: partials/toc_gen.html:7:38: executing "partials/toc_gen.html" at <.File.UniqueID>: error calling UniqueID: runtime error: inva
lid memory address or nil pointer dereference                                                  
ERROR render of "section" failed: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/_default/baseof.html:10:4": execute of template failed: template: _default/list.html:10:4: executing "_default/list.html" at <partial "toc.html" .>: error calling partial: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/partials/toc.html:6:4": execute o
f template failed: template: partials/toc.html:6:4: executing "partials/toc.html" at <partial "toc_gen.html" .>: error calling partial: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/partials/toc_gen.html:7:38": execute of template failed: template: partials/toc_gen.html:7:38: executing "partials/toc_gen.html" at <.File.UniqueID>: error calling UniqueID: 
runtime error: invalid memory address or nil pointer dereference                               
ERROR render of "page" failed: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/_default/baseof.html:10:4": execute of template failed: template: _default/single.html:10:4: executing "_default/single.html" at <partial "toc.html" .>: error calling partial: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/partials/toc.html:6:4": execute 
of template failed: template: partials/toc.html:6:4: executing "partials/toc.html" at <partial "toc_gen.html" .>: error calling partial: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/partials/toc_gen.html:7:38": execute of template failed: template: partials/toc_gen.html:7:38: executing "partials/toc_gen.html" at <.File.UniqueID>: error calling UniqueID:
 runtime error: invalid memory address or nil pointer dereference                              
INFO  build:  step render pages 935 content 786 duration 2.480426778s
INFO  build:  step postProcess duration 21.611µs
INFO  build:  duration 2.57562497s                                                             
Built in 2576 ms                                                                               
Error: error building site: render: failed to render pages: render of "taxonomy" failed: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/_default/baseof.html:10:4": execute of template failed: template: _default/list.html:10:4: executing "_default/list.html" – File is nil; wrap it in if or with: {{ with partial "toc.html" .>: error calling partial: "/home/
hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/partials/toc.html:6:4": execute of template failed: template: partials/toc.html:6:4: executing "partials/toc.html" at <partial "toc_gen.html" .>: error calling partial: "/home/hugo/dtdocs-master/themes/hugo-darktable-docs-pdf-theme/layouts/partials/toc_gen.html:7:38": execute of template failed: template: partials/t
oc_gen.html:7:38: executing "partials/toc_gen.html" at <.File }}{{ .UniqueID }}{{ end }}       
processing language en                                                                         
```

**Comment by jmooring** [comment] 2024-02-19 23:14
@darix What's triggering (not necessarily causing) this in the build is the generate-translations script, which (obviously) didn't run when I ran build-pdf.sh. 

So here are _all_ the steps required to reproduce the problem:

```text
git clone --recurse-submodules https://github.com/darktable-org/dtdocs
cd dtdocs
```

Then replace tools/build-all.sh with this:

<details>
<summary>tools/build-all.sh</summary>

```text
#!/usr/bin/env bash

base_url="$1"

#go to project root
PROJECT_ROOT="$(cd `dirname $0`/..; pwd)"
cd "$PROJECT_ROOT"

#generate translated files
./tools/generate-translations.sh --no-update

#build html site
# ./tools/build-html.sh "$base_url"

#build epubs
# ./tools/build-epub.sh

#build pdfs
./tools/build-pdf.sh
```
</details>
<br>

Then install po4a:

```text
sudo apt install po4a
```

Then build:

```text
./tools/build-all.sh 
```

**Comment by jmooring** [comment] 2024-02-19 23:24
@darix What was the last version you used to build without error?

**Comment by darix** [comment] 2024-02-19 23:25
btw @jmooring if you want i can add more debugging tools/editors to the container than devs do not have to install extra stuff outside. I can also add the patched shell script as build-debug to the repository.

0.122.0. I pretty much update our package + container on the day of the release :) this is the first time we ran into a gotcha with that strategy! We are very happy campers with following hugo releases.

**Comment by jmooring** [comment] 2024-02-19 23:31
@darix

> just let me know what you need

Adding a debug script so we don't have to cut and paste would be helpful, as would anything you can do to speed up the build. The translation step takes forever. This easier and faster this is to reproduce, the more likely it will be looked at soon.

**Comment by jmooring** [comment] 2024-02-19 23:51
@darix This was simple. With v0.122.0 you were seeing (but maybe ignoring) this WARNING:

> WARN  .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}

With v0.123.0 that's now an ERROR, not a warning. To be fair, we've been warning about this for a couple of years...

To fix, do what the message says. Replace this:

```text
{{ .File.UniqueID }}
```

with this:

```text
{{ with .File}}{{ .UniqueID }}{{ end }}
```

Hugo throws the error because some pages rendered by these templates are not backed by a file.

**Comment by jmooring** [comment] 2024-02-19 23:52
@CamilleScholtz Even though I can't build your site, you have the same problem as my previous comment. It used to be a warning, now it's throwing an error.

**Comment by darix** [comment] 2024-02-19 23:53
> @darix This was simple. With v0.122.0 you were seeing (but maybe ignoring) this WARNING:
> 
> > WARN  .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}
> 
> With v0.123.0 that's now an ERROR, not a warning. To be fair, we've been warning about this for a couple of years...
> 
> To fix, do what the message says. Replace this:
> 
> ```
> {{ .File.UniqueID }}
> ```
> 
> with this:
> 
> ```
> {{ with .File}}{{ .UniqueID }}{{ end }}
> ```
> 
> Hugo throws the error because some pages rendered by these templates are not backed by a file.

well I agree that this should be fixed. i was more worried about the invalid memory address error.

**Comment by jmooring** [comment] 2024-02-20 00:00
> switching from warning to error shouldnt trigger an invalid memory error

I'll leave that one to bep.

**Comment by jmooring** [comment] 2024-02-29 13:15
Closing in favor of https://github.com/gohugoio/hugo/issues/12176

**Closed by jmooring** 2024-02-29 13:15 UTC
Labels: Bug, v0.123.0
