### ISSUE TITLE
Unable to decode Exif metadata from image in Hugo 0.88

### ISSUE THREAD

**Issue by hvfrancesco** [gohugoio/hugo#8996] opened 2021-09-26 11:27 UTC
hugo version: hugo v0.88.1-5BC54738 linux/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio

Trying to read EXIF data from jpeg images I get similar warnings:
WARN 2021/09/26 13:16:45 Unable to decode Exif metadata from image: /images/2021_01_30/fulls/DSCF2441.jpg

The Images are accesible as resources and are correctly retrieved and used. An example code snippet that I'm trying to use:

    {{ range (readDir ( print "assets/" .cartella "fulls") )  }} 
        {{ $title := ""}}
        {{ $content := ""}}
        {{ $image :=  resources.Get (print $path "fulls/" .Name) }}
        {{ $thumb :=  resources.Get (print $path "thumbs/" .Name) }}
        {{ with $image.Exif }}<li>{{ .Date}}</li>{{ end }}
        {{ $button := "guarda"}}
        {{ partial "picture" (dict "title" $title "content" $content "image" $image.Permalink "thumb" $thumb.Permalink "button" $button) }}
     {{ end }}
   
The images are Jpeg images taken with a Fujifilm camera and processed in Darktable. The exif data is perfectly readable using any othere tool or library I've tried and is apparently well formed according to standards.

**Comment by hvfrancesco** [comment] 2021-09-26 11:29
Here is an example image in case it could be of any use

![DSCF7782](https://user-images.githubusercontent.com/614123/134805768-1175d5e5-6195-4ca4-8eeb-e84c107b9372.jpg)

**Comment by swartz-k** [comment] 2021-09-26 14:35
This error caused by `exif.NewDecoder` -> `exifDecoder.Decode(image)` -> `_exif.Decode(r)` -> `/Users/jok1r/go/pkg/mod/github.com/rwcarlsen/goexif@v0.0.0-20190401172101-9e8deecbddbd/exif/exif.go:283` -> `/Users/jok1r/go/pkg/mod/github.com/rwcarlsen/goexif@v0.0.0-20190401172101-9e8deecbddbd/tiff/tiff.go:84` -> `/Users/jok1r/go/pkg/mod/github.com/rwcarlsen/goexif@v0.0.0-20190401172101-9e8deecbddbd/tiff/tiff.go:131`

As below code `t.Count` is 0.
```
func DecodeTag(r ReadAtReader, order binary.ByteOrder) (*Tag, error) {
	....
        err = binary.Read(r, order, &t.Count)
	if err != nil {
		return nil, errors.New("tiff: tag component count read failed: " + err.Error())
	}

	// There seems to be a relatively common corrupt tag which has a Count of
	// MaxUint32. This is probably not a valid value, so return early.
	if t.Count == 1<<32-1 {
		return t, errors.New("invalid Count offset in tag")
	}

	valLen := typeSize[t.Type] * t.Count
	if valLen == 0 {
		return t, errors.New("zero length tag value")
	}
        ....
}
```

**Comment by swartz-k** [comment] 2021-09-26 14:56
Maybe should change a exif lib. I use this one [go-exif](https://github.com/dsoprea/go-exif) is ok 

> changed with https://github.com/dsoprea/go-exif/blob/master/exif-read-tool/main.go

![image](https://user-images.githubusercontent.com/49771587/134813042-87147692-d209-4301-b81e-d510c57b8ac5.png)

**Comment by jmooring** [comment] 2021-09-26 15:11
See #8586 and #8761.

**Comment by swartz-k** [comment] 2021-09-26 15:14
> See #8586 and #8761.

Hope this PR will be merged soon.

**Comment by jmooring** [comment] 2021-09-27 18:01
@swartz-k #8761 is blocked by https://github.com/dsoprea/go-exif/pull/63.

**Closed** 2024-07-20 13:56 UTC
Labels: Bug, Keep
