### ISSUE TITLE
.Site.Params.x causes panic when using 'hugo new content'

### ISSUE THREAD

**Issue by stanhoenson** [gohugoio/hugo#11242] opened 2023-07-12 18:45 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.115.2+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

---

### Demonstration
Consider the following archetype:
```markdown
---
title: '{{ replace .Name "-" " " | title }}'
description: "{{ .Site.Params.description }}"
---
```

When running `hugo new content _index.md`, no problems.
Then when running `hugo new content about.md`, it panics:
```
panic: [BUG] no Page found for "/Users/stan/root/code/hugo-test/content/about.md"

goroutine 1 [running]:
github.com/gohugoio/hugo/create.(*contentBuilder).applyArcheType(0xc0000018c0, {0xc0006c5880, 0x39}, {0xc0003b1e10, 0xa})
	github.com/gohugoio/hugo/create/content.go:278 +0x35c
github.com/gohugoio/hugo/create.(*contentBuilder).buildFile(0xc0000018c0)
	github.com/gohugoio/hugo/create/content.go:246 +0x168
github.com/gohugoio/hugo/create.NewContent.func1()
	github.com/gohugoio/hugo/create/content.go:105 +0x2ad
github.com/gohugoio/hugo/create.NewContent(0xc0005e6c80, {0x0, 0x0}, {0x7ff7bfeff429, 0xd}, 0x0)
	github.com/gohugoio/hugo/create/content.go:109 +0x5ff
github.com/gohugoio/hugo/commands.newNewCommand.func1({0x0?, 0x0?}, 0x0?, 0x0?, {0xc000364880, 0x0?, 0x0?})
	github.com/gohugoio/hugo/commands/new.go:65 +0x173
github.com/gohugoio/hugo/commands.(*simpleCommand).Run(0x0?, {0x10265ec28?, 0xc000046310?}, 0x0?, {0xc000364880?, 0x0?, 0x0?})
	github.com/gohugoio/hugo/commands/commandeer.go:595 +0x43
github.com/bep/simplecobra.(*Commandeer).compile.func1(0xc000005800?, {0xc000364880?, 0x1?, 0x1?})
	github.com/bep/simplecobra@v0.3.2/simplecobra.go:113 +0x52
github.com/spf13/cobra.(*Command).execute(0xc000005800, {0xc0003646e0, 0x1, 0x1})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000a4c600)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
	github.com/spf13/cobra@v1.7.0/command.go:1001
github.com/bep/simplecobra.(*Exec).Execute(0xc000014710, {0x10265ec28?, 0xc000046310?}, {0xc0003facc0?, 0x101c1cb20?, 0xc00007b368?})
	github.com/bep/simplecobra@v0.3.2/simplecobra.go:155 +0xd9
github.com/gohugoio/hugo/commands.Execute({0xc0000401c0, 0x2, 0x2})
	github.com/gohugoio/hugo/commands/commandeer.go:66 +0x312
main.main()
	github.com/gohugoio/hugo/main.go:25 +0x65
```

My `hugo.toml` contains the following:
```toml
languageCode = 'en'
title = 'Website'
[params]
  description = 'Welcome to my website'
```

When I remove the `{{ .Site.Params.author }}` from archetype, all works as expected.

It's very easily reproducible when creating a new Hugo project. Change the archetype and the `hugo.toml` and you can reproduce it.

**Comment by deining** [comment] 2023-07-12 21:26
Related:

* #11208
* #9196
* #9204

**Comment by jmooring** [comment] 2023-07-12 21:53
I am unable to reproduce this with:
hugo v0.115.2-8966424e0e521fb1627216a84efd2c5d5917cb0d+extended linux/amd64 BuildDate=2023-07-08T17:06:56Z VendorInfo=gohugoio

Here's the test site I'm using:

```text
git clone --single-branch -b hugo-github-issue-11242 https://github.com/jmooring/hugo-testing hugo-github-issue-11242
cd hugo-github-issue-11242
hugo new content foo.md
```

What's different about your setup, other than macOS instead of Linux?

**Comment by stanhoenson** [comment] 2023-07-13 07:32
I'm having a real hard time replicating the problem now for some reason, however the following steps got me to the problem:

- `hugo new site website`
- `cd website`
- `hugo new foo.md`
  - Succeeds
  - `rm content/foo.md`
- Edit `archetypes/default.md`:

```md
---
title: "{{ replace .Name '-' ' ' | title }}"
date: {{ .Date }}
draft: true
author: "{{ .Site.Params.author }}"
---
```

- Edit `hugo.toml`:

```toml
languageCode = "en"
title = "Hello world"

[params]
  author = "John Doe"
```

- `hugo new foo.md`
  - Succeeds
  - `rm content/foo.md`
- `mkdir content/blog`
- `hugo new blog/foo.md`
  - Succeeds
  - `rm content/blog/foo.md`

- `hugo new theme basic`
- `mv archetypes/default.md mv themes/basic/archetypes/default.md`
- `hugo new foo.md`
  - Succeeds
  - `rm content/foo.md`
- `hugo new blog/foo.md`
  - Succeeds
  - `rm content/blog/foo.md`

- Edit `hugo.toml`:

```toml
languageCode = "en"
title = "Hello world"
theme = "basic"

[params]
  author = "John Doe"
```

- `rm themes/basic/hugo.toml themes/basic/LICENSE themes/basic/theme.toml`
- `hugo new foo.md`
  - Succeeds
  - `rm content/foo.md`
- `hugo new blog/foo.md`
  - Succeeds
  - `rm content/blog/foo.md`

- `rm -r archetypes`
- `hugo new foo.md`
  - Succeeds
  - `rm content/foo.md`
- `hugo new blog/foo.md`
  - Succeeds
  - `rm content/blog/foo.md`

- `rm -r layouts`
- `hugo new foo.md`
  - Succeeds
  - `rm content/foo.md`
- `hugo new blog/foo.md`
  - Succeeds
  - `rm content/blog/foo.md`

- `rm -r static`
- `hugo new foo.md`
  - Succeeds
  - `rm content/foo.md`
- `hugo new blog/foo.md`
  - Succeeds
  - `rm content/blog/foo.md`

- `rm -r data`
- `hugo new foo.md`
  - Succeeds
- `hugo new blog/foo.md`
  - Succeeds
- `hugo new _index.md`
  - Succeeds
- `hugo new bar.md`
  - Fails
- `rm content/_index.md`
- `hugo new _index.md`
  - Succeeds
- `hugo new foobar.md`
  - Fails

I'll try to get to the problem on your repository as well.

**Comment by stanhoenson** [comment] 2023-07-13 08:01
So to reproduce in your repository:

- Add `draft: true` to `archetypes/default.md`
- `rm content/_index.md`
- `hugo new _index.md`
- `hugo new foo.md`

Then to "resolve" the issue:

- Set `draft: false` in `content/_index.md`'s front matter
- `hugo new bar.md`

I'm not sure if this is expected behaviour or a bug.

**Comment by jmooring** [comment] 2023-07-13 14:54
@stanhoenson Thank you for digging into the details. It's a bug; a duplicate of https://github.com/gohugoio/hugo/issues/9196.

**Closed by jmooring** 2023-07-13 14:54 UTC
Labels: Bug, NeedsTriage
