### ISSUE TITLE
Customisable IDs for TableOfContents

### ISSUE THREAD

**Issue by xbc5** [gohugoio/hugo#10371] opened 2022-10-10 21:21 UTC
It's best described with an example.

I have two TOCs: one beside the main copy (for large screens); one in a drawer (for small screens). This results in duplicate IDs: it fails HTML validation; it may lead to JavaScript selection issues.

Inject a configurable and unique ID for each TOC rendered on a single page.

This might not be possible due to each page having one rendered TOC, available only through a variable. I am also assuming that Hugo uses the Goldmark table of contents plug-in -- which (afaik) doesn't support custom IDs.

**Comment by jmooring** [comment] 2022-11-04 18:47
Duplicate of (or would be resolved with) https://github.com/gohugoio/hugo/issues/8338.

**Closed by jmooring** 2022-11-04 18:47 UTC
Labels: NeedsTriage, Proposal
