### ISSUE TITLE
`markdownify` no longer produces smartypants

### ISSUE THREAD

**Issue by XhmikosR** [gohugoio/hugo#6571] opened 2019-12-02 10:52 UTC
With Hugo >= 0.60.0, when using the `markdownify` function, we no longer get smartypants.

```yml
markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
```

```md
description: Get started with Bootstrap, the world's most popular framework for building responsive, mobile-first sites, with BootstrapCDN and a template starter page.
```

and this in a layout:

```html
<p class="bd-lead">{{ .Page.Params.Description | markdownify }}</p>
```

```diff
diff --git "a/C:\\Users\\xmr\\Desktop\\1.html" "b/C:\\Users\\xmr\\Desktop\\2.html"
index 4519767..a797964 100644
--- "a/C:\\Users\\xmr\\Desktop\\1.html"
+++ "b/C:\\Users\\xmr\\Desktop\\2.html"
@@ -1 +1 @@
-Get started with Bootstrap, the world’s most popular framework for building responsive, mobile-first sites, with BootstrapCDN and a template starter page.
+Get started with Bootstrap, the world's most popular framework for building responsive, mobile-first sites, with BootstrapCDN and a template starter page.

```

**Comment by bep** [comment] 2019-12-02 11:28
The typographer extension is enabled by default, but it may behave differently from Blackfriday's.  Which I assume will eventually be fixed if it's important enough. I think your example have been discussed.

**Comment by XhmikosR** [comment] 2019-12-02 11:45
This looks pretty similar https://github.com/yuin/goldmark/issues/39

**Comment by bryanforbes** [comment] 2019-12-17 18:20
According to the author of goldmark, he doesn't use the extension but would welcome PRs to add the functionality. I'm not familiar enough with Go to be able to make the changes or I would.

**Comment by jakejarvis** [comment] 2020-01-14 03:33
Looks like this will be fixed in next goldmark release – https://github.com/yuin/goldmark/pull/88  :)

**Comment by flother** [comment] 2020-01-14 09:52
@jakejarvis It made it into [v1.1.21](https://github.com/yuin/goldmark/releases/tag/v.1.1.21) just a couple of hours after you posted. Once Hugo's dependency on Goldmark is updated this regression (from Blackfriday's behaviour) should be fixed.

**Closed** 2020-01-15 11:07 UTC
Labels: Bug, Upstream
