### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /^[Î‘-ÏŽ]+$/: Range out of order in character class in Tags page

### ISSUE THREAD

**Issue by dbu9** [gohugoio/hugo#10914] opened 2023-04-25 10:00 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.105.0-0e3b42b4a9bdeb4d866210819fc6ddcf51582ffa linux/amd64 BuildDate=2022-10-28T12:29:05Z VendorInfo=gohugoio

</pre>

### Does this issue reproduce with the latest release?
Yes

### Description

On the tags page when a tag is clicked, nothing happens, console shows errors:

![image](https://user-images.githubusercontent.com/118698819/234243027-061ee683-3714-4a8a-834c-8a7e005d97bd.png)

The test site to see the problem: https://www.sbot.lol/tags/

**Comment by jmooring** [comment] 2023-04-25 16:41
Duplicate of https://github.com/gohugoio/hugo/issues/8232.

**Closed by jmooring** 2023-04-25 16:41 UTC
Labels: Bug, Duplicate, NeedsTriage
