### ISSUE TITLE
Shortcodes not parsing for HTML content files with manual summary dividers

### ISSUE THREAD

**Issue by drElektron** [gohugoio/hugo#8205] opened 2021-02-04 14:56 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.80.0-792EF0F4 windows/amd64 BuildDate: 2020-12-31T13:37:57Z
</pre>

### Does this issue reproduce with the latest release?
Yes and with v0.67.1

### Description
 TL;DR = Shortcodes won't parse for HTML content files that have a manual summary divider

[Longer description in this discourse](https://discourse.gohugo.io/t/shortcodes-and-manual-summary-dividers-md-html-content-file-inconsistency/30984). Issue raised as per request.
This works:
```
<p>Some introduction words</p>
<p>Some main content words</p>
{{<a-custom-shortcode with=a-variable>}}
<p>Some other main content words</p>
```
This doesn't
```
<p>Some introduction words</p>
<!--more-->
<p>Some main content words</p>
{{<a-custom-shortcode with=a-variable>}}
<p>Some other main content words</p>
```

[Demo repo for this behaviour is here](https://gitlab.com/trespratique/ShortSum)

There is also another possible issue that is highlighted by this example - .Summary and .Content give different things for MD and HTML content files (although maybe that is intentional?).

**Comment by jmooring** [comment] 2021-03-11 16:03
Use `<!-- more -->` instead of `<!--more-->`.

Yes, there's a problem here somewhere, because the [documentation](https://gohugo.io/content-management/summaries/#manual-summary-splitting) states:

> Be careful to enter `<!--more-->` exactly; i.e., all lowercase and with no whitespace.

**Comment by jmooring** [comment] 2021-03-11 16:39
Duplicate of https://github.com/gohugoio/hugo/issues/6513.

**Comment by jmooring** [comment] 2021-03-11 16:58
> There is also another possible issue that is highlighted by this example - .Summary and .Content give different things for MD and HTML content files

This is described in https://github.com/gohugoio/hugo/issues/6686.

**Closed** 2021-03-28 13:39 UTC
Labels: Duplicate
