### ISSUE TITLE
Collection key type in YAML breaks map range order

### ISSUE THREAD

**Issue by dmgawel** [gohugoio/hugo#4083] opened 2017-11-15 13:26 UTC
When defining a collection in Hugo data file using YAML format it is then parsed as `map[interface {}]interface {}`. This fundamentally differs from TOML and JSON which parses collections to `map[string]interface {}`.

Example (YAML):
```yaml
test:
  a: 1
  b: 2
```
is parsed to:
```go
map[interface {}]interface {}{"a":1, "b":2}
```

Example (TOML):
```toml
[test]
a = 1
b = 2
```
is parsed to:
```go
map[string]interface {}{"a":1, "b":2}
```

Example (JSON):
```json
{
  "test": {
    "a": 1,
    "b": 2
  }
}
```
is parsed to:
```go
map[string]interface {}{"a":1, "b":2}
```

As YAML is a superset of JSON one can suppose the same key type in both formats.

The following have a great effect on ranging over maps. From the [range docs](https://golang.org/pkg/text/template/#hdr-Actions):
> If the value is a map and the keys are of basic type with a defined order ("comparable"), the elements will be visited in sorted key order.

Apparently `string` is comparable, unlike `interface{}`.

**Comment by dmgawel** [comment] 2017-11-15 13:45
I came across another issue with this behaviour. `map[interface {}]interface {}` is not 'jsonifiable'. Given data in `test.yaml` executing: `{{ .Site.Data.test | jsonify }}` outputs:

```
ERROR 2017/11/15 14:43:43 Error while rendering "home": template: index.html:8:23: executing "index.html" at <jsonify>: error calling jsonify: json: unsupported type: map[interface {}]interface {}
```

**Comment by bep** [comment] 2017-11-15 14:14
I assume this is a `go-yaml` upstream issue -- and I think I have seen it before?

**Comment by moorereason** [comment] 2017-11-15 14:29
Duplicate of #2441

**Closed by moorereason** 2017-11-15 14:29 UTC
