### ISSUE TITLE
Use page resources for OpenGraph and Twitter Card images

### ISSUE THREAD

**Issue by tashian** [gohugoio/hugo#5078] opened 2018-08-15 17:41 UTC
For my site I'm using page resources to transform and display cover images for my stories. It's working super well.

But the internal OpenGraph and Twitter Card templates use the "images" param:

https://github.com/gohugoio/hugo/blob/488631fe0abc3667355345c7eb98ba7a2204deb5/tpl/tplimpl/template_embedded.go#L194

Page resources seem like the ideal way to do OpenGraph and Twitter meta tags, too. Does it make sense to migrate the internal templates?

For now I have created my own partials. The image tag looks like this:

    {{ with (.Resources.ByType "image").Match "cover" }}{{ range first 6 . }}
      <meta property="og:image" content="{{ .RelPermalink | absURL }}" />
    {{ end }}{{ end }}

This depends on me having a "cover" resource, but a more generic version of this would just choose the first image resource on the page.

I think the only challenge here is making the change in a non-breaking way.

**Comment by MichaelHierweck** [comment] 2018-09-13 07:57
Would this be fixed by #5157?

**Comment by max-arnold** [comment] 2018-09-13 09:15
I believe that right now Twitter card template already does what you want, and indeed #5157 will bring the same behavior to the OpenGraph template. The lookup order is:

1. Explicit `images` param in a frontmatter
2. Page bundle images which match `*cover*` or `*thumbnail*`
3. Global `Site.Params.images`

**Comment by spech66** [comment] 2018-10-30 06:39
Seems like the Schema template is missing this too.

**Comment by max-arnold** [comment] 2018-10-30 13:39
@spech66 I'll try to submit a PR with something similar for `schema.html` in a few days.

**Comment by max-arnold** [comment] 2018-11-07 13:37
@spech66 Done!

**Comment by TomPichaud** [comment] 2018-11-18 18:42
Could you also update the OpenGraph template please ?

It would be nice to get some kind of cohesion between these 3 templates.

**Comment by max-arnold** [comment] 2018-11-18 19:03
@TomPichaud I did exactly that! The #5378 will bring this behavior to OpenGraph template, and #5415 to Schema.

Hopefully, someone from maintainers will merge these PRs.

**Comment by MichaelHierweck** [comment] 2019-03-18 20:08
Please get this PR merged. (I really don't understand why this bug/PR is still open.)

**Comment by robshep** [comment] 2019-04-14 11:33
Please merge this.  I've locally patched for now.

For me it's not convenience, but to workaround a bug. 

`absURL` from `images` **doesn't** work on page-bundled images. 

`.Permalink` from `resources` **does** work on page-bundled images

**Comment by hacdias** [comment] 2019-04-16 14:18
This would be really nice to have,

/cc @bep

**Comment by max-arnold** [comment] 2019-08-16 03:15
bump

**Comment by meredrica** [comment] 2020-01-02 13:54
Opengraph / Twittercard and Schema still don't generate the propper url when an image is used in a page bundle.

**Comment by max-arnold** [comment] 2020-01-02 17:41
@meredrica Could you provide an example of how you use this feature?

Here is how I tested it: https://github.com/gohugoio/hugo/pull/5157#issuecomment-419701217
And here is an example page bundle: https://github.com/max-arnold/testblog/tree/master/content/articles/post1

**Comment by aormsby** [comment] 2020-04-25 23:56
I've been running some tests on these since I wasn't getting the correct results (which turned out to be my fault), and it really seems to me that everything is working as intended at the moment according to that https://github.com/gohugoio/hugo/pull/5157#issuecomment-419701217.

@meredrica Here were my mistakes just in case you've done the same thing.
1. I had a cover.jpg in a page bundle, but it was inside a subfolder, so the path was something like `mypost/img/cover.jpg`. This doesn't work because this code
https://github.com/gohugoio/hugo/blob/25a6b33693992e8c6d9c35bc1e781ce3e2bca4be/tpl/tplimpl/embedded/templates/opengraph.html#L8
only gets resources from the folder where `index.md` is. (At least, it did that for me. I'm unclear on if this is what is intended.) So I had to move my image out of the subfolder for the cards templates to automatically find it.
2. I tried to use a relative URL in the `images=[]` front matter of my post, but it only accepts absolute URLS.

Perhaps either of my mistakes will help you out.

@max-arnold I actually find it rather frustrating that we can only use absolute URLs for the images array in post front matter. I'd really love to be able to use relative URLs as well since page bundles inherently encourage their use. What would it take to add that functionality? I saw someone on the forum had what looked like a decent suggestion for supporting it [here](https://discourse.gohugo.io/t/links-for-images-videos-audio-in-internal-templates-twitter-cards-and-opengraph/10464?u=aormsby).

**Comment by max-arnold** [comment] 2020-04-26 05:19
I didn't change this behavior in my PRs, and I only brought the existing logic from the TwitterCard template to OpenGraph & Schema templates, so they behave in the same way.

The resulting links should be absolute - I've seen requests from broken bots that can't deal with relative links. Also this https://stackoverflow.com/a/9858694/65523

I'm not sure about the nested resource subfolders, but I believe that the ability to specify relative links in the front matter (and converting them to absolute ones) is useful, because it allows moving page bundles to a different folder without any modifications.

@kaushalmodi Is the approach [you described](https://discourse.gohugo.io/t/links-for-images-videos-audio-in-internal-templates-twitter-cards-and-opengraph/10464) still the best one? I'd be happy to add something linke this to OG/Twitter/Schema templates, but I hope that a more elegant approach does exist.

**Comment by kaushalmodi** [comment] 2020-04-26 12:53
> Is the approach you described still the best one?

Hello, it's been few years since when I suggested that approach! So now I cannot say if that's still the best way. 

But it certainly still works because I am using that for my site.

**Comment by aormsby** [comment] 2020-04-27 22:27
> The resulting links should be absolute

Agreed! I was just thinking about relative link options on the front matter creation side. 🙂 

I would also counter myself and say that it may not be absolutely necessary to support relative link input in my subfolder case since the quick fix was just to move all of my `cover.jpg` files into the root of the page bundle where they would be automatically discovered during a build and then used as thumbnail sources. It was a very minor change in my page bundle organization.

However, for the general case of moving page bundles around, relative links would probably help a lot.

@max-arnold I may have a suggestion. I like how @kaushalmodi's `/` option in `images` is driven by user input, so it's a clear decision to switch from absolute to relative paths, but perhaps that small detail could be easily missed and cause confusion if users are unaware of its use. To make that more clear, I might suggest throwing in a new variable like `relimages` or something similar in order to decide on using absolute versus relative paths. Then the various card templates could easily be updated to check for relative URLs and build out the absolute paths using the data if the `images`variable isn't present.

I'm unsure if this is what you mean by "a more elegant approach", though, since adding variables is not necessarily a good plan. It also seems a little redundant. Just brainstorming over here.

**Comment by meredrica** [comment] 2020-05-13 07:43
Not being able to use relative image paths in the front matter is a real pain.
It breaks scaffolding if you have a default image in your archetype - I have that, I publish a comic and need to replace the image, obviously.

**Comment by jmooring** [comment] 2023-12-24 21:02
@razonyang I'm pretty sure this was addressed with https://github.com/gohugoio/hugo/pull/11688. Please confirm.

**Comment by razonyang** [comment] 2023-12-25 02:09
@jmooring Yes, this can be achieved via the `images` parameter since v0.121.1.

```sh
$ tree content/foo
├── cover1.jpg
├── cover2.jpg
├── cover3.jpg
├── cover4.jpg
├── cover5.jpg
├── cover6.jpg
└── index.md

$ cat content/foo/index.md 
---
images:
  - cover1.jpg
  - cover2.jpg
  - cover3.jpg
  - cover4.jpg
  - cover5.jpg
  - cover6.jpg
---

$ cat layouts/_default/single.html
{{ template "_internal/twitter_cards.html" . }}
{{ template "_internal/opengraph.html" . }}
{{ template "_internal/schema.html" . }}

$ hugo

$ cat public/foo/index.html | grep image
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:image" content="https://example.org/foo/cover1.jpg" /><meta name="twitter:title" content="111"/>
<meta property="og:url" content="https://example.org/foo/" /><meta property="og:image" content="https://example.org/foo/cover1.jpg" /><meta property="og:image" content="https://example.org/foo/cover2.jpg" /><meta property="og:image" content="https://example.org/foo/cover3.jpg" /><meta property="og:image" content="https://example.org/foo/cover4.jpg" /><meta property="og:image" content="https://example.org/foo/cover5.jpg" /><meta property="og:image" content="https://example.org/foo/cover6.jpg" /><meta property="article:section" content="" />
<meta itemprop="wordCount" content="0"><meta itemprop="image" content="https://example.org/foo/cover1.jpg" /><meta itemprop="image" content="https://example.org/foo/cover2.jpg" /><meta itemprop="image" content="https://example.org/foo/cover3.jpg" /><meta itemprop="image" content="https://example.org/foo/cover4.jpg" /><meta itemprop="image" content="https://example.org/foo/cover5.jpg" /><meta itemprop="image" content="https://example.org/foo/cover6.jpg" />
```

**Closed** 2023-12-25 02:11 UTC
Labels: Keep, Feature: Embedded Template
