### ISSUE TITLE
Hugo not made executable using govendor since latest update - Ubuntu 17.04

### ISSUE THREAD

**Issue by Taubin** [gohugoio/hugo#3657] opened 2017-06-28 01:27 UTC
I've run up a new VM of Ubuntu 17.04 and attempted to install Hugo following the instructions listed on the website for installation via Govendor. 

It's a brand new VM with apt updates fully installed, prior to installing hugo. 

Installed Go and verified the installation, same with govendor, and verified the versions for both. 

```
taubin@localhost:~$ go version
go version go1.7.4 linux/amd64

taubin@localhost:~$ ls $HOME/go/src/github.com/gohugoio/hugo
appveyor.yml  config           docshelper      i18n        output            source
bench.sh      CONTRIBUTING.md  examples        LICENSE.md  parser            tpl
benchSite.sh  create           goreleaser.yml  livereload  README.md         transform
bufferpool    deps             helpers         main.go     releaser          utils
cache         Dockerfile       hugofs          Makefile    requirements.txt  vendor
commands      docs             hugolib         media       snapcraft.yaml    watcher

taubin@localhost:~$ hugo version
The program 'hugo' is currently not installed. You can install it by typing:
sudo apt install hugo

taubin@localhost:~$ ls $HOME/go/bin/
govendor
```

Expected output from hugo --version: version installed given

Actual output from hugo --version: The program 'hugo' is currently not installed. You can install it by typing: sudo apt install hugo

**Comment by bep** [comment] 2017-06-28 06:27
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by Taubin** [comment] 2017-06-28 06:32
This is a bug in either your software, or in your directions, so it should belong here. Posting in the discussion forum is not going to fix this, as it cropped up with the latest update to your software. I'm not sure what else you are expecting me to prove to prove that this is a bug. Your instructions, or your software are broken, which makes this a bug that needs correcting if you want people to continue to use your software. 

Posting in a forum about the issue will not get it fixed.

**Comment by anthonyfok** [comment] 2017-06-28 08:40
Hi @Taubin,

> This is a bug in either your software, or in your directions, so it should belong here.

Well, that is the thing: There are many new GitHub issues that come in daily, and someone need to "triage" them to determine whether they are actual bugs or not.  Usually we get them right, but when a report is incomplete or ambiguous, like the one you filed, then we are not so sure.

Please allow me to 

> Subject: Hugo not made executable using govendor since latest update - Ubuntu 17.04

My first reactions when I see that title:

1. Huh?  Govendor creates a `hugo` file but make it with 0644 permission?
2. Since lastest update?  You mean the exact instructions were working before?  When?  Or with which older version?
3. Since latest update of what?  Of Hugo?  Of govendor?  Of Go?

> I've run up a new VM of Ubuntu 17.04 and attempted to install Hugo following the instructions listed on the website for installation via Govendor.

There are many different pages on the Hugo website, sometimes with duplicate information.  Could you please be more specific by providing the actual URL?  Did you mean to say https://gohugo.io/overview/installing#fetch-from-github ?  Or did you find the instruction somewhere else?

> Installed Go and verified the installation, same with govendor, and verified the versions for both.

Which is nice, thank you, but you didn't tell us specifically what commands you ran to arrive at what you have right now, a.k.a. "**Steps to Reproduce**".  Are these the two exact commands that you ran prior to arriving at the current situation?

    go get github.com/kardianos/govendor
    govendor get github.com/gohugoio/hugo

If so, please do spell it out so that others may try to follow your exact steps to reproduce the bug, avoiding ambiguity and potentially preventing a mistriage.  :wink:

So, here is how I would have written if I were you:

----

## Steps to Reproduce

    $ cd ~
    $ export PATH=/tmp/foo
    $ go get github.com/kardianos/govendor
    $ $GOPATH/bin/govendor get -v github.com/gohugoio/hugo

## Expected Result

Like what the Hugo documentation at https://gohugo.io/overview/installing#fetch-from-github says:

> `govendor get` will fetch Hugo and all its dependent libraries to `$HOME/go/src/github.com/gohugoio/hugo`, and compile everything into a final `hugo` (or `hugo.exe`) executable, which you will find sitting inside `$HOME/go/bin/`, all ready to go!

Or, in our case, we should see a file at `$GOPATH/bin/hugo`, i.e. `/tmp/foo/bin/hugo`.

## Actual Result

No `$GOPATH/bin/hugo`, i.e. no `/tmp/foo/bin/hugo`.

----

Apparently, `govendor get` isn't doing what we think it would do, and it is not quite exactly doing what `govendor` claims it would do, i.e.:

    get      Like "go get" but copies dependencies into a "vendor" folder.

No, it is not quite like `go get` at all, as `go get` always builds the library.

Worse yet, I could not get `govendor` to tell me what it is actually doing even if I were to add the `-v` verbose flag to the `govendor get` command, and it happily exits with 0.  Grr...

So, thank you for reporting this issue!  Reopening...

**Comment by bep** [comment] 2017-06-28 08:55
@anthonyfok this issue belongs in the discussion forum. I closed this for a reason. There are plenty of other more important issues floating around that needs attention. If thread started cannot get `govendor` working (it works fine with `make`), I suggest he tries an alternative way of installing.

**Comment by anthonyfok** [comment] 2017-06-28 08:56
/cc @moorereason, see Issue #3153, PR #3181, and commit d6093aba4d0b74804378013c2326deb3cca58d7e

    go get github.com/kardianos/govendor
    cd $GOPATH/src/github.com
    $(go env GOPATH)/bin/govendor get github.com/gohugoio/hugo
    ls -l $GOPATH/bin/hugo

**Comment by anthonyfok** [comment] 2017-06-28 08:56
@bep Let @moorereason or @rdwatters fix it.

**Comment by anthonyfok** [comment] 2017-06-28 09:31
Workaround in documentation added, see https://github.com/gohugoio/hugoDocs/commit/c4e21471adb2ff32250346fcdaa4e1df11d7d7d2.

The changes will appear on the gohugo.io website probably around the time of the next Hugo's stable release, about a month from now.

**Closed by anthonyfok** 2017-06-28 09:31 UTC
Labels: Docs

**Comment by anthonyfok** [comment] 2017-07-28 15:16
Hi @Taubin,

Here is a final wrap up:

It turns out there was an issue with govendor:

* "govendor get" does not create $GOPATH/bin/pkgname like `go get` does (kardianos/govendor#330)

which has been kindly fixed by govendor's author in kardianos/govendor#336 (commit kardianos/govendor@cf990b2) 8 days ago.

Also, in the all new Hugo documentation, copyeditor @rdwatters had carefully included a final `go install` step (since April) at https://gohugo.io/getting-started/installing/#fetch-from-github, which should serve as an elegant catch-all in case the end user is somehow stuck with an older version of govendor.

Last but not least, thank you for bringing up the issue.
