### ISSUE TITLE
Include latest hugo 0.37.1 in Ubuntu 18.04 LTS repos

### ISSUE THREAD

**Issue by gntech** [gohugoio/hugo#4350] opened 2018-01-29 10:45 UTC
I have been testing the alpha of Ubuntu 18.04 in a VM and I noticed that the version of Hugo currently in the repos are 0.26.
Since Ubuntu 18.04 is a LTS and there have been really nice features added to Hugo lately, (like the page image resources handling) should we try to get hugo 0.34 in to the ubuntu repos before release?

**Comment by bep** [comment] 2018-01-29 10:47
/cc @anthonyfok 

I would love for this to happen, but this seems to be a hard task ...

**Comment by gntech** [comment] 2018-02-01 08:20
Most likely it has to go through debian testing before entering the ubuntu repo https://tracker.debian.org/pkg/hugo

**Comment by anthonyfok** [comment] 2018-02-01 17:29
Thank you for the heads up!

> I would love for this to happen, but this seems to be a hard task ...

Me too, it would be great to get the latest Hugo into Ubuntu 18.04 LTS especially because of all the important new features.  My apologies for falling behind.

According to https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule for Ubuntu 18.04 LTS, the Debian Import Freeze will happen on 2018-03-01, though indeed, for a LTS release, the Debian import might be from testing instead of unstable, so Hugo and any new dependencies had better enter "unstable" before 2018-02-21.  Deadline for dependency upload probably around 2018-02-14.

I'd better get on it.

**Comment by anthonyfok** [comment] 2018-02-21 21:30
All thanks to Dr. Tobias Quathamer (@toddy15) who prepared, packaged and uploaded hugo 0.35-1 to Debian on 2018-02-12:
* https://tracker.debian.org/pkg/hugo

which has been imported into Ubuntu "Bionic":
* https://packages.ubuntu.com/bionic/hugo (0.35-1 in [universe])

@toddy15, thank you for doing all the actual work when I was unable to.

Sidenote: hugo 0.36.1 cannot be uploaded to Debian yet because the new dependency golang-github-muesli-smartcrop-dev is still awaiting manual approval: https://ftp-master.debian.org/new.html

**Comment by bep** [comment] 2018-02-21 22:18
There are some serious issues with Hugo < 0.36.1 that, if this is some long term Debian thing, I would prefer if it would be removed rather than added.

Ideally you should wait for 0.37 (Monday).

**Comment by anthonyfok** [comment] 2018-02-21 22:34
> There are some serious issues with Hugo < 0.36.1 that, if this is some long term Debian thing, I would prefer if it would be removed rather than added.
>
> Ideally you should wait for 0.37 (Monday).

Thanks for the heads up!

Since the supposed deadline isn't until March 1, I think we still have a chance to get Hugo 0.37 into Ubuntu 18.04 LTS, perhaps using some kind of manual sync request if needed be.

I am starting to learn about that process here:

* https://wiki.ubuntu.com/UbuntuDevelopment/NewPackages
* https://wiki.ubuntu.com/DebianImportFreeze/Implementation

I will follow up on it to ensure the best version of Hugo ends up in Ubuntu 18.04 LTS.

**Comment by anthonyfok** [comment] 2018-03-06 22:31
Special thanks to @toddy15, @mwhudson and other friends at Ubuntu for filing sync requests on Launchpad, triaging them, and doing the actual sync into Ubuntu 18.04 LTS (bionic).

Here is a quick checklist to keep track of sync requests of related packages.

### Packages that are absolutely needed for hugo (>= 0.37) to enter bionic-release

[ ] [Bug #1753179 “FFe: Sync golang-github-alecthomas-chroma 0.3.0-1 ...” : Bugs : golang-github-alecthomas-chroma package : Ubuntu](https://bugs.launchpad.net/ubuntu/+source/golang-github-alecthomas-chroma/+bug/1753179)
[ ] [Bug #1753180 “FFe: Sync hugo 0.37.1-1 (universe, coming soon) fr...” : Bugs : hugo package : Ubuntu](https://bugs.launchpad.net/ubuntu/+source/hugo/+bug/1753180)
[ ] [Bug #1753838 “Sync golang-github-chaseadamsio-goorgeous 2.0.0+gi...” : Bugs : golang-github-chaseadamsio-goorgeous package : Ubuntu](https://bugs.launchpad.net/ubuntu/+source/golang-github-chaseadamsio-goorgeous/+bug/1753838) to allow golang-blackfriday (1.5.1-1) to migrate from bionic-proposed to bionic-release.

### Other dependencies or related packages

[x] [Bug #1753748 “Sync golang-golang-x-sys 0.0~git20180224.f6cff07-1...” : Bugs : golang-golang-x-sys package : Debian](https://bugs.launchpad.net/debian/+source/golang-golang-x-sys/+bug/1753748) which fixes compilation with gccgo-8
[ ] [Bug #1753767 “FFe: Sync golang-fsnotify 1.4.7-1 (universe) from ...” : Bugs : golang-fsnotify package : Ubuntu](https://bugs.launchpad.net/ubuntu/+source/golang-fsnotify/+bug/1753767) with fewer deadlocks and race conditions
[ ] [Bug #1753829 “FFe: Sync golang-github-revel-revel 0.12.0+dfsg-4 ...” : Bugs : golang-github-revel-revel package : Ubuntu](https://bugs.launchpad.net/ubuntu/+source/golang-github-revel-revel/+bug/1753829) because of my removal of old transitional package names from golang-fsnotify (1.4.7-1)

**Comment by bep** [comment] 2018-03-06 22:58
I will release 0.37.1 with 1 bug fix tomorrow. It's not the most critical bug in the world, but is a regression and hard for the end users to understand; I have been holding off a little waiting for more  ... which did not come, which I guess is a good thing.

**Comment by anthonyfok** [comment] 2018-03-12 07:51
I am happy to report that, thanks to the help of many people, especially @toddy15, @mwhudson, @tsimonq2 and @ginggs, Hugo 0.37.1-1 has finally landed in Ubuntu 18.04 LTS (bionic) (due to be released on 2018-04-26), see https://packages.ubuntu.com/bionic/hugo

(I was helping a friend with installing the Lubuntu flavour of Ubuntu 18.04 LTS daily snapshot, and `sudo apt install hugo` indeed fetched 0.37.1-1!  Hurray!)

**Closed by anthonyfok** 2018-03-12 07:51 UTC
