### ISSUE TITLE
Allow uppercase language codes in urls

### ISSUE THREAD

**Issue by misitebao** [gohugoio/hugo#10375] opened 2022-10-13 15:29 UTC
Hopefully an option can be provided to allow uppercase language codes in URLs, similar to "disablePathToLower", although I fully understand the original intention of defaulting to lowercase, there are still some users who need to use uppercase language codes in URLs, such as: "pt-BR ", "zh-Hans", etc.

**Comment by jmooring** [comment] 2022-10-13 16:10
Isn't this a duplicate of your issue https://github.com/gohugoio/hugo/issues/9404?

**Comment by misitebao** [comment] 2022-10-13 16:31
@jmooring 
Yes, but the question has no follow-up.

**Closed** 2022-10-13 17:02 UTC
Labels: Duplicate, NeedsTriage, Proposal
