### ISSUE TITLE
Tiny YouTube shortcode preview

### ISSUE THREAD

**Issue by wmutschl** [gohugoio/hugo#10175] opened 2022-08-14 10:13 UTC
### What version of Hugo are you using (`hugo version`)?
v0.101.0 extended
<pre>
$ hugo version

</pre>

### Does this issue reproduce with the latest release?
Yes

### Describe the bug

After updating my theme wowchemy academic to v5.6.0, I noticed that the youtube shortcodes don't work as expected, see for example the following picture on my [site](https://mutschler.eu/dynare/identification/dynare-summer-school-2021/):
<img width="821" alt="Screen Shot 2022-08-13 at 22 41 06" src="https://user-images.githubusercontent.com/36013296/184510176-5dd08bdb-8def-4f3a-9ed0-3c476cec5f74.png">
The tiny square is actually the video and I can click it and it runs, but why is it so tiny?
I checked with the theme creator, but he refered me to open the issue here. 

### Technical details:

- Link to your GitHub project: https://github.com/wmutschl/mutschler.eu
- Wowchemy Version (from your `go.mod`): v5.6.0
- Hugo Version (run `hugo version`): 0.101.0
- Browser/OS: Safari/Chrome on macOS
- Wowchemy Template (e.g. Academic): Academic

**Comment by anthonyfok** [comment] 2022-08-14 15:57
Hi @wmutschl,

In your content/dynare/identification/dynare-summer-school-2021.md, for example:

https://github.com/wmutschl/mutschler.eu/blob/3beb3aa01872de5cab8812ef477400d83013394a/content/dynare/identification/dynare-summer-school-2021.md?plain=1#L19-L21

you have:

   ```md
   {{< youtube fBfDRHnTn2I >}}
   ```

i.e., you have placed the `{{< youtube fBfDRHnTn2I >}}` shortcode inside a preformatted code block with syntax highlighting for Markdown code, e.g.:

```markdown
## Sample heading
1. Run `hugo server`
2. Visit [YouTube](https://www.youtube.com/)
```

Your `youtube` shortcode preview will be sized correctly when you remove the surrounding `` ```md `` and `` ``` ``.  `{{< youtube fBfDRHnTn2I >}}` alone suffices.

See the article [How To Make a Responsive 100% Width YouTube iFrame Embed](https://www.h3xed.com/web-development/how-to-make-a-responsive-100-width-youtube-iframe-embed) on how a zero-height container is used to have the embedded YouTube video automatically sized.  Hugo's `youtube` shortcode uses the exact same idea for the "magic", but this magic disappears if the shortcode got embedded inside a code block.

As this is not a bug in Hugo, I am hereby closing this issue.  Hope this helps!

**Closed by anthonyfok** 2022-08-14 15:57 UTC
Labels: Bug, NeedsUserFeedback

**Comment by anthonyfok** [comment] 2022-08-14 16:02
And our standard notice (which I forgot to add):

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by wmutschl** [comment] 2022-08-14 18:31
You are a genius, thank you so much for pointing out the very obvious mistake! And of course I will post next time in the forum, sorry about that!
