### ISSUE TITLE
Emojify break link

### ISSUE THREAD

**Issue by tonka3000** [gohugoio/hugo#7913] opened 2020-11-01 16:32 UTC
Hey,

I've activated emojify (via `enableEmoji = true` in my config.toml) today on my site. It works great, but it breaks some of my links when there is an emoji like part in it.

In my case this is a sharepoint link created from office 365, so I can not change the link.

So the link look like `https://my.sharepoint.com/:x:/g/personal/namehere/KKFASDAskjlsaASDlkj`. The problem is the `:x:`. Hugo make a :x: out of it and so the link breaks. I have a normal markdown link like `[test link](https://my.sharepoint.com/:x:/g/personal/namehere/KKfRIQdgXJJPrFFUwAAsPMcBpGYDTO)`

The only workaround would be a shortlink service, but the site should also work without internet access, so it is not an option for me.

## Expected behavior
Hugo should preserve emoji like syntax in markdown links or links in general.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.77.0-EF290125 windows/amd64 BuildDate: 2020-10-30T10:13:29Z
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by tylerchambers** [comment] 2020-11-09 18:41
Because [RFC 3492](https://tools.ietf.org/html/rfc3492) says URLs with emoji are valid, there are probably two ways we could handle this:

1. Allow the specification of a custom emoji deliminator character(s) in config.toml
2. A flag to prevent the emojification of URLs

1 sounds better to me, because it would be easier. 

I'm going to start working on 1, but if any contributors have other ideas let me know.

**Comment by PushpamKumarTR** [comment] 2022-03-02 19:42
To avoid emojifying, you can URL encode `:` .
eg. /:x:/ => /%3Ax%3A/

**Comment by MartinMMx** [comment] 2022-10-26 12:55
We are also using O365 links, and can confirm the links are broken by Hugo.
This is not the expected behavior of Markdown parsing, however. Links are not supposed to be modified.
And yes, emoji are valid in links - but if you want them there, you probably have a link that already has the emoji properly encoded, and you don't type out the emoji by hand.

So I consider this clearly a bug which should be fixed, to be consistent with other popular Markdown renderers.

**Comment by jmooring** [comment] 2022-10-26 17:17
Related: <https://github.com/gohugoio/hugo/issues/7332>

**Comment by jmooring** [comment] 2023-11-15 19:41
This was resolved in v0.120.0 with https://github.com/gohugoio/hugo/pull/11593

**Closed by jmooring** 2023-11-15 19:41 UTC
