### ISSUE TITLE
Hugo Error

### ISSUE THREAD

**Issue by ailunbolinkenasi** [gohugoio/hugo#9156] opened 2021-11-11 08:59 UTC
[root@i-st2cjork study]# mkdir /tmp/hugo_cache
[root@i-st2cjork study]# hugo
Total in 0 ms
panic: mkdir /tmp/hugo_cache: no such file or directory

goroutine 1 [running]:
github.com/spf13/afero.GetTempDir(0x2966320, 0x381a720, 0x24b5748, 0xa, 0xc0002ef4e0, 0xc00045e628)
        /build/hugo/parts/hugo/go/pkg/mod/github.com/spf13/afero@v1.6.0/util.go:128 +0x2b7
github.com/gohugoio/hugo/helpers.GetTempDir(...)
        /build/hugo/parts/hugo/build/helpers/path.go:441
github.com/gohugoio/hugo/helpers.GetCacheDir(0x2966320, 0x381a720, 0x2966d78, 0xc000495b30, 0x19, 0x29014b4, 0x1, 0x9)
        /build/hugo/parts/hugo/build/helpers/path.go:405 +0x19a
github.com/gohugoio/hugo/cache/filecache.resolveDirPlaceholder(0x2966320, 0x381a720, 0x2966d78, 0xc000495b30, 0x24e94d9, 0x9, 0xc00007f0a0, 0x2, 0x2, 0xc0000a6d48, ...)
        /build/hugo/parts/hugo/build/cache/filecache/filecache_config.go:228 +0x205
github.com/gohugoio/hugo/cache/filecache.DecodeConfig(0x2966320, 0x381a720, 0x2966d78, 0xc000495b30, 0x0, 0x20, 0xaf7acdc351fb499e)
        /build/hugo/parts/hugo/build/cache/filecache/filecache_config.go:170 +0xdd4
github.com/gohugoio/hugo/hugolib.configLoader.collectModules(0x2966d78, 0xc000495b30, 0x2966320, 0x381a720, 0x2969298, 0xc00038ed50, 0x0, 0x0, 0xc0000420e4, 0x19, ...)
        /build/hugo/parts/hugo/build/hugolib/config.go:375 +0x165
github.com/gohugoio/hugo/hugolib.LoadConfig(0x2966320, 0x381a720, 0x2969298, 0xc00038ed50, 0x0, 0x0, 0xc0000420e4, 0x19, 0xc0000420e4, 0x19, ...)
        /build/hugo/parts/hugo/build/hugolib/config.go:154 +0xa30
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc0004a7500, 0xc0004a7500, 0x2932560)
        /build/hugo/parts/hugo/build/commands/commandeer.go:309 +0x385
github.com/gohugoio/hugo/commands.newCommandeer(0x101, 0xc0004a7340, 0x292f820, 0xc00024b510, 0xc00024b6b0, 0x0, 0x0, 0x0, 0x228d8a0, 0x788e01, ...)
        /build/hugo/parts/hugo/build/commands/commandeer.go:193 +0x26a
github.com/gohugoio/hugo/commands.initializeConfig(0x2000101, 0xc0004a7340, 0x292f820, 0xc00024b510, 0xc00024b6b0, 0x2b, 0xc000462420, 0xc00045fce8)
        /build/hugo/parts/hugo/build/commands/hugo.go:125 +0x7f
github.com/gohugoio/hugo/commands.(*commandsBuilder).newHugoCmd.func1(0xc0003ab180, 0x381ac68, 0x0, 0x0, 0x0, 0x0)
        /build/hugo/parts/hugo/build/commands/commands.go:168 +0x155
github.com/spf13/cobra.(*Command).execute(0xc0003ab180, 0xc00003c1f0, 0x0, 0x0, 0xc0003ab180, 0xc00003c1f0)
        /build/hugo/parts/hugo/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003ab180, 0xc00024b510, 0x5, 0x4)
        /build/hugo/parts/hugo/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/gohugoio/hugo/commands.Execute(0xc00003c1f0, 0x0, 0x0, 0x4e3b05, 0xc000048118, 0x1ed82b0, 0x0)
        /build/hugo/parts/hugo/build/commands/hugo.go:92 +0xb9
main.main()
        /build/hugo/parts/hugo/build/main.go:23 +0x76

**Comment by jmooring** [comment] 2021-11-20 16:00
Unable to reproduce with v0.89.4 on Ubuntu 20.04.3 LTS 

```bash
sudo su
cd ~
pwd     # /root
rm -rf /tmp/hugo_cache
mkdir /tmp/hugo_cache
hugo new site foo
cd foo
hugo
```

**Comment by bep** [comment] 2021-11-20 20:58
I'm closing this; it this is still an issue, please reopen with a issue description matching the template (with OS information etc.).

**Closed by bep** 2021-11-20 20:58 UTC
