### ISSUE TITLE
# in URL are not escaped

### ISSUE THREAD

**Issue by camilleroux** [gohugoio/hugo#5100] opened 2018-08-20 15:02 UTC
If I set the following in config.toml

```toml
[permalinks]
  post = "/posts/:title/"
```

Then add a post with a title starting by "#", the URL will be:
`http://localhost:1313/posts/#test` (

The "#" should be escaped or removed, I think.

**Comment by moorereason** [comment] 2018-08-20 15:25
Duplicate of #4926

**Closed by moorereason** 2018-08-20 15:25 UTC
Labels: Duplicate
