### ISSUE TITLE
Make minify rename javascript variables to make javascript even shorter

### ISSUE THREAD

**Issue by kssilveira** [gohugoio/hugo#7311] opened 2020-05-24 13:44 UTC
If I minify javascript using yui-compressor:

```
$ echo "function init() {
  var nodes = document.getElementsByTagName('iframe');
  for (var i = 0; i < nodes.length; i++) {
    var data = nodes[i].getAttribute('data-src');
    if (data) {
      nodes[i].setAttribute('src', data);
    }
  };
}
setTimeout(init, 1500);
" | yui-compressor --type js
```

I get

```
function init(){var a=document.getElementsByTagName("iframe");for(var b=0;b<a.length;b++){var c=a[b].getAttribute("data-src");if(c){a[b].setAttribute("src",c)}}}setTimeout(init,1500);
```

If I use hugo --minify, I get:

```
function init(){var nodes=document.getElementsByTagName('iframe');for(var i=0;i<nodes.length;i++){var data=nodes[i].getAttribute('data-src');if(data){nodes[i].setAttribute('src',data);}};}
setTimeout(init,1500);
```

This request is to make hugo --minify rename javascript variables to make javascript even shorter.

## What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.70.0/extended linux/amd64 BuildDate: 2020-05-13T17:30:34Z
</pre>

### Does this issue reproduce with the latest release?

I think I have the latest release.

**Comment by kssilveira** [comment] 2020-10-04 10:51
I think this is still relevant and valuable because it can make pages load faster.

**Comment by tdewolff** [comment] 2020-10-08 15:03
This has been implemented in https://github.com/tdewolff/minify/releases/tag/v2.9.0 and you should be able to update the minify package manually. Currently Hugo doesn't use the latest version of minify that has this feature.

**Comment by hobiah** [comment] 2020-11-30 19:09
Is there a plan to integrate the last minify release with this feature into hugo? Or shall we stil manually update?

**Comment by jeremielp** [comment] 2020-11-30 19:10
Is there a plan to integrate this update into hugo? Or shall we go with manual update still?

**Comment by moorereason** [comment] 2020-12-01 04:23
@bep, I think we can evaluate updating minify again.

To recap the situation:

We updated from v2.6.2 to v2.9.4 in #7701, but that was reverted in #7792 after [this report from the forums](https://discourse.gohugo.io/t/28696).  I was [able to reproduce the issue](https://discourse.gohugo.io/t/0-76-0-breaks-lazy-loading-on-my-website/28696/14?u=moorereason) at the time but couldn't identify the root cause.

Today, I took another look at the issue reported in the forum, and the problem is fixed in v2.9.9 (specifically, https://github.com/tdewolff/minify/commit/eb4ff2b6ebc6a99aa77d662aebc876948588222f).

Cc: @tdewolff @Hrishikesh-K

**Comment by bep** [comment] 2020-12-01 08:48
I guess this issue is talking about the `--minify` flag, but if you're talking about external JS files, note that js.Build also has an minify option, which I'm pretty sure is doing a great job:

https://gohugo.io/hugo-pipes/js#import-js-code-from-assets

As to updating the upstream minifier. We have had a couple of breaking changes with this recently, and the problem with these breaks is that they don't just put a scratch in your site. We currently don't have a good enough test suite on the Hugo side of the fence to make sure that all is OK, so upgrades requires manual work, and this has not been a priority of me lately.

**Comment by jeremielp** [comment] 2020-12-01 10:12
I though about that too. I have been checking the code proposed by @kssilveira with these 2 methods:
- `hugo --minify`
- asset minification using Hugo Pipes
```
    {{ $js := resources.Get "test.js" }}
    {{ $jsm := $js | resources.Minify }}
```

The output is the same as the one mentioned in the issue.

**Comment by bep** [comment] 2020-12-01 10:23
>The output is the same as the one mentioned in the issue in both cases.

No, I meant something like this:

```bash
{{ $js := resources.Get "test.js" }}
{{ $jsm := $js | js.Build (dict "minify" true) }}
```

**Comment by jeremielp** [comment] 2020-12-01 10:31
Yes, that one renames variables correctly

**Comment by kssilveira** [comment] 2021-01-13 23:03
Thanks, `js.Build` worked indeed for resources. I ran into issues caused by the renaming of global variables (that I wanted to access from other files or that clashed with global variables in other files), this could be one of the reasons for "As to updating the upstream minifier. We have had a couple of breaking changes with this recently".

Another use case I have for this is to call `js.Build` on the result of a partial that generates JS code that is different for each page. Do you have a suggestion for how to do that?

I ran into a few problems:
- `js.Build` expects a resource, so I had to use `resources.FromString`
- `resources.FromString` would cache the resource across pages, so I had to pick a different name for the resources corresponding to each page
- I could not prevent the partial from escaping the JS code (e.g. `<` becomes `&lt;`)

I was experimenting with:

```
{{- $js := partial "main.js" . | safeJS | resources.FromString (printf "%s%s" .Name "partial.js") -}}
{{ $js.Permalink }}
<script type='text/javascript'>
  {{ $js.Content | safeJS }}
</script>
```

And the idea was to do:

```
{{- $js := partial "main.js" . | safeJS | resources.FromString (printf "%s%s" .Name "partial.js") | js.Build (dict "minify" true "format" "cjs") -}}
<script type='text/javascript'>
  {{ $js.Content | safeJS }}
</script>
```

**Comment by kssilveira** [comment] 2021-01-13 23:37
This worked (after creating the file inside `assets/main.js`):

```
{{- $js := resources.Get "main.js" | resources.ExecuteAsTemplate (printf "%s%s" .Name "partial.js") . | js.Build (dict "minify" true) -}}
<script type='text/javascript'>
  {{ $js.Content | safeJS }}
</script>
```

**Comment by jeremielp** [comment] 2021-01-13 23:46
> Another use case I have for this is to call `js.Build` on the result of a partial that generates JS code that is different for each page. Do you have a suggestion for how to do that?

Also interested in this. That would be a good workaround to the upstream minifier issue, at least for my setup.

**Comment by tdewolff** [comment] 2021-01-14 10:47
The problems that @bep mentions are ones from a long time ago and have been fixed since. Using the updated `github.com/tdewolff/minify` package you'll get variable renaming as well (and usually a little faster and better than `esbuild` too). Both are very high-quality libraries by the way, but they serve slightly different purposes.

The lack of tests in Hugo for the minifier was what was holding back the upgrade, however is there such a test set for `esbuild`? If anything, `minify` has a very complete and extensive test set (bigger than `esbuild` and most other parsers). They have had a number of severe bugs as well (any bug will completely break a website by the way, it's hard to make just a scratch), like `minify`, which is completely normal in the development of software. I'm really unsure what the objective reasons are for not upgrading `minify`, besides from the "it broke stuff in the past" rhetoric.

**Comment by regisphilibert** [comment] 2021-11-26 13:53
The Hugo minifier (for html files) should not rename variables by default as you might be using them outside of the internal script ([Alpine.js](https://alpinejs.dev/) is a use case where you needed to and still can add your [data](https://alpinejs.dev/globals/alpine-data) script as internal while needing its declared variable outside of it.

**Comment by jmooring** [comment] 2021-11-26 15:48
1\) We are now using tdewolff/minify 2.9.22 (latest).

2\) The default configuration is `keepVarNames = false`

3\) As JS, this:

```js
function init() {
  var nodes = document.getElementsByTagName('iframe');
  for (var i = 0; i < nodes.length; i++) {
    var data = nodes[i].getAttribute('data-src');
    if (data) {
      nodes[i].setAttribute('src', data);
    }
  };
}
setTimeout(init, 1500);
```

is minified to this:

```hs
function init(){for(var b=document.getElementsByTagName('iframe'),a=0,c;a<b.length;a++)c=b[a].getAttribute('data-src'),c&&b[a].setAttribute('src',c)}setTimeout(init,1500)
```

4\) As an HTML file, this:

```html
<script>
function init() {
  var nodes = document.getElementsByTagName('iframe');
  for (var i = 0; i < nodes.length; i++) {
    var data = nodes[i].getAttribute('data-src');
    if (data) {
      nodes[i].setAttribute('src', data);
    }
  };
}
setTimeout(init, 1500);
</script>
```

is minified (no change) to this:

```html
<script>
function init() {
  var nodes = document.getElementsByTagName('iframe');
  for (var i = 0; i < nodes.length; i++) {
    var data = nodes[i].getAttribute('data-src');
    if (data) {
      nodes[i].setAttribute('src', data);
    }
  };
}
setTimeout(init, 1500);
</script>
```

Unless I'm missing something, this was resolved a while ago.

**Closed by jmooring** 2021-11-26 15:48 UTC
Labels: Enhancement

**Comment by tdewolff** [comment] 2021-11-27 00:11
The minifier does not rename variables that could be referenced outside the script, i.e. all global variable names are kept even as `KeepVarNames == False`. If this is causing a problem, could you open an issue at https://github.com/tdewolff/minify please?

As for @jmooring the JS example looks correct, but the HTML example not, is the JS minifier enabled in that case? It should be!

**Comment by jmooring** [comment] 2021-11-27 00:34
@tdewolff Thank you. You are correct. I have updated my comment.
