### ISSUE TITLE
date of public/css folder has year 1754! Until changed theme.css did not load on live site

### ISSUE THREAD

**Issue by tarskuk** [gohugoio/hugo#6648] opened 2019-12-20 12:10 UTC
<pre>
$ hugo version
Hugo Static Site Generator v0.60.1/extended linux/amd64 BuildDate: unknown
using a modified version of theme hugo-tailwind-journal
</pre>

i am very new to Hugo, so not fully up to speed with syntax in {{ }}, However

- used command "hugo server " which works fine
- used command "hugo" to generate content in public folder
  - uploaded files to server but theme.css would not load
ls -la of public has
```
drwxrwxr-x  2 d d  4096 Dec 20 10:54 categories
drwxr-xr-x  2 d d  4096 Aug 30  1754 css
drwxrwxr-x  6 d d  4096 Dec 20 10:54 dojo
-rw-rw-r--  1 d d 15086 Dec 15 12:07 favicon.ico
drwxr-xr-x  2 d d  4096 Aug 30  1754 images
drwxr-xr-x  2 d d  4096 Aug 30  1754 img
-rw-rw-r--  1 d d  6490 Dec 20 10:54 index.html

```
NB date has year 1754! when i changed it with
`touch -a -m -t 201912200130.00 css`
live server now loads correctly

**Comment by moorereason** [comment] 2019-12-20 13:53
Duplicate of #6161

**Closed by moorereason** 2019-12-20 13:53 UTC
Labels: Duplicate
