### ISSUE TITLE
Wrong Permalink for resource in multihost mode when baseURL in one language has a sub path

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9324] opened 2021-12-26 15:45 UTC
I'm doing some  code simplification and have a test failure that looks like a bug.

I have a case with 
* Multiple language, each with it's own `baseURL`
* The English language also has a sub-path (`baseURL = "https://example.com/docs"`), the others not
* Still, the resources for French gets prefixed with the `/docs` path.

**Comment by jmooring** [comment] 2023-05-29 16:52
Duplicate of https://github.com/gohugoio/hugo/issues/10912.

**Closed** 2024-01-28 09:52 UTC
Labels: Bug, Keep, Feature: Multilingual
