### ISSUE TITLE
`ByTitle` sorting doesn't manage é/à letter 

### ISSUE THREAD

**Issue by CedricRaison** [gohugoio/hugo#9706] opened 2022-03-21 18:57 UTC
### What version of Hugo are you using (`hugo version`)?
0.95

In my `layouts/_default/terms.html`, I have this to show and sort my tags/categories by title:
```
{{ range .Pages.ByTitle }}
<li>
    <a href="{{ .Permalink }}">{{ .Title }}</a>
</li>
{{ end }}
```

I use the `ByTitle` method to sort my tags by alphabetical order. Unfortunately it doesn't manage well `é/à` letter: Here is an example of the current wrong sorting:
```
- alpha
- charlie
- echo
- lima
- papa
- sierra
- zulu
- émotion
```
The expected sorting would have been like this:

```
- alpha
- charlie
- echo
- émotion
- lima
- papa
- sierra
- zulu
```

edit: using the `sort` method this way `{{ range (sort .Pages "Title") }}` produce the same issue. `ByTitle` must be using `sort` under the hood.

**Comment by jmooring** [comment] 2022-03-21 22:32
Related:
- <https://discourse.gohugo.io/t/sort-slice-with-accented-characters/29217>
- <https://github.com/gohugoio/hugo/issues/2180>
- <https://github.com/gohugoio/hugo/issues/9402>

**Comment by bep** [comment] 2022-04-10 18:43
>ByTitle must be using sort under the hood.

It doesn't.

I guess it's time to bite the bullet and start using `golang.org/x/text/collate` (language aware) for sorting of strings. It will certainly be slower, but that may not be a big issue.

**Comment by bep** [comment] 2022-04-10 20:29
Closing this as a duplicate of  #2180

**Closed by bep** 2022-04-10 20:29 UTC
Labels: Duplicate, Enhancement
