### ISSUE TITLE
tpl/strings: Fix confusing error message

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5264] opened 2018-09-29 19:09 UTC
From Twitter:

>Error: Failed to process archetype file "default.md": template: default:3:34: executing "default" at <replace>: wrong number of args for replace: want 3 got 3

**Comment by moorereason** [comment] 2018-11-13 23:47
The reporter [replied to himself]( https://twitter.com/obsidianspork/status/1046091439992709122):

> It turns out I was overcomplicating my archetype defaults. Updated `"{{ getenv "desc" | replace .Name '"' " " | description }}"` to `"{{ getenv "desc" }}"` gave the exact result

So, the error was that he was actually passing 4 args to replace due to the piping.

However, I'm unable to reproduce this error message.  I always get "want 3 got 4."  `tpl/strings.Replace` hasn't changed the last 2 years.  The best I can tell the error message is coming from the Go template engine.

I think we can close this issue.

**Closed** 2018-11-14 00:04 UTC
Labels: Bug
