### ISSUE TITLE
Resources cached in "resources/_gen" published ignoring publishResources = false

### ISSUE THREAD

**Issue by ovoled** [gohugoio/hugo#10595] opened 2023-01-01 10:38 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.109.0-47b12b83e636224e5e601813ff3e6790c191e371 windows/amd64 BuildDate=2022-12-23T10:38:11Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

### Reproduce steps
<pre>
// config.toml

[cascade._build]
publishResources = false
</pre>

<pre>
// layouts/_default/index.html

{{ $imgOriginal := resources.Get "test.jpg" }}
{{ $imgProcessedUnused := $imgOriginal.Fit "100x100" }}
&lt;img src="{{ $imgOriginal.Permalink }}"&gt;
</pre>

1. put "test.jpg" into "assets"
2. clean directories "public" and "resources"
3. run hugo
4. directory public contains "test.jpg"
5. run hugo
6. directory public now contains "test.jpg" and "test_hu360497c2a11d6b503ab55b11082e86dd_9951_100x100_fit_q75_box.jpg"

It seems that if a resource was cached in "resources/_gen" it will appear in "public" even if `publishResources = false` and there are no permalinks to that resource.

**Comment by pamubay** [comment] 2023-01-01 12:23
`publishResources` option only controls **Page Bundle Resources**, your code above using global resources (`assets`)

**Comment by ovoled** [comment] 2023-01-01 13:08
I see the same behavior with pictures from the `content` directory too.
And (in both cases) I believe that two consecutive launches of `hugo` should give the same result in `public`.

**Comment by pamubay** [comment] 2023-01-01 14:41
Any minimal reproducible example repo?

Also note, even `publishResources = false` is set

> Setting this to false will still publish Resources on demand (when a resource’s .Permalink or .RelPermalink is invoked from the templates)

---

> I see the same behavior with pictures from the content directory too

And, make sure the images is live inside **Page Bundle** or Hugo will treat it as static files and copied to `public`

**Comment by ovoled** [comment] 2023-01-01 15:20
ok, here is repo
https://github.com/ovoled/test-hugo-publishResources-bug.git

Rewrote with image inside Page Bundle.

**Comment by jmooring** [comment] 2023-01-01 18:57
Duplicate of https://github.com/gohugoio/hugo/issues/10255

**Closed by jmooring** 2023-01-01 18:57 UTC
Labels: Bug, NeedsTriage
