### ISSUE TITLE
Markdown images from hooks wrapped in <p>

### ISSUE THREAD

**Issue by kraftner** [gohugoio/hugo#6748] opened 2020-01-13 14:32 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.62.2-83E50184/extended linux/amd64 BuildDate: 2020-01-05T18:57:23Z

</pre>

### Does this issue reproduce with the latest release?

Yes

---

When using a Render Hook Template for Image Markdown the image gets wrapped in a `</p>` no matter what the template contains. If the template contains e.g. a `<figure>` this results in invalid HTML since `<figure>` [is not permitted content for `<p>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p).

This issue also show in the example page https://portable-hugo-links.netlify.com/2019/12/30/blog-post/.
See the W3C Validator: https://validator.w3.org/nu/?doc=https%3A%2F%2Fportable-hugo-links.netlify.com%2F2019%2F12%2F30%2Fblog-post%2F

**Comment by bep** [comment] 2020-01-13 15:20
![image](https://user-images.githubusercontent.com/394382/72267529-82d3e680-3620-11ea-8abd-1e57f3222aa0.png)

Maybe I need some more coffee, but I don't see any p-tag wrapping the figure in the above example...?

**Comment by kraftner** [comment] 2020-01-13 15:36
Sorry, I could have been clearer on this since I stumbled over that first myself. That's also the reason why I included the link to the W3C Validation.

The browser automatically "fixes" this by closing the `<p>` before the `<figure>` and opening a new one before the closing `</p>`. But like this you end up with two empty `<p>`'s before and after the figure.

The DOM Inspector already show the fixed DOM, you need to look at it via "View Source": Firefox even  highlights the dangling `</p>`  in red:

![grafik](https://user-images.githubusercontent.com/2428517/72268554-4dc89380-3622-11ea-927b-acbb4e4d459d.png)

**Comment by bep** [comment] 2020-01-13 16:27
You are right, I did need some more coffee.

**Comment by bep** [comment] 2020-01-13 17:24
To me, this boils down to this: CommonMark/Goldmark treats images as inline elements. If you use the `<img>` tag in your hook template, this is fine (at least according to the W3C Validator).

The problem is, we have no (known) way to look at an image in Markdown and tell if it is intended to be displayed inline or not. This question was raised on Twitter some time ago, and I didn't really understand it:

https://twitter.com/lvv_me/status/1210175815012376577?s=20

The user above uses the `.Title` field to determine if it is a block or inline, and since CommonMark does not say anything about this, I guess that is the best you can do. Or you can say that "I have only block images".

But you need to tell Hugo about this, and I assume that it isn't practical to do this on parse time, so perhaps we could add a `{{ .IsBlock }}` signal method that we need to end/remove any surrounding p-s.

This is me thinking out loud. Maybe @yuin has a tip.

**Comment by yuin** [comment] 2020-01-14 05:42
I almost agree with @bep's opinion.

Images are inline elements in CommonMark and no block level image elements exist. Images have URL, alt text and title text. Images can not have other information in markup.

So what we can do in CommonMark is:

1. Define your own rules for images like "An image that has empty alt text is a block level" "A Paragraph that has one image only is a block level image." 
2. Implement the rules in your Markdown processor.
    1. In goldmark, you can use ASTTransformer for transforming nodes.


FYI, [Generic directives/plugins syntax](https://talk.commonmark.org/t/generic-directives-plugins-syntax/444) is being discussed in CommonMark. If we have this syntax, you will be able to use attributes like `![alt](imageurl.png title){display=block}` .

**Comment by HenrySkup** [comment] 2020-01-23 05:43
Few thoughts:

I think @yuin nailed it on the head in both points (and the FYI).

This should be addressed in some way though -- perhaps even just documentation -- since everybody (Hugo, Goldmark, the developer, the editor, etc.) are all doing the "correct" thing, but the browsers are doing something unexpected at page render time.  This means that it is particularly hard to debug and then you have to inject something like :

```
window.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('p:empty')
    .forEach(e => e.remove());
})
```

which is a nascence.

**Comment by kraftner** [comment] 2020-01-23 09:25
@HenrySkup I have to disagree with

> [...] since everybody (Hugo, Goldmark, the developer, the editor, etc.) are all doing the "correct" thing, but the browsers are doing something unexpected at page render time.

The generated HTML is invalid, nesting `<pre>` inside `<p>`, so the browsers are behaving correctly. I think if there is no way to technically solve this to output valid HTML there should at least be documentation explaining that images have to be inline elements to generate valid HTML. So no `<figure>` elements for example.

**Comment by jmooring** [comment] 2021-04-18 01:01
I'm in favor of closing this issue. Here's my (pedantic) reasoning:

- A render hook for a markdown _heading_ should return a _heading_ (example: `<h1>foo</h1>`).
- A render hook for a markdown _link_ should return a _link_ (example: `<a href="foo">foo</a>`).
- A render hook for a markdown _image_ should return an _image_ (example: `<img src="foo">`)

In this issue's original example, the render hook for a markdown _image_ was coded to return a _figure_. This seems like we are hijacking the render hook, asking it do something for which it was not designed.

To me, if you want a `<figure>` in your content, you should put a `<figure>` in your content. It would make sense to use a 
shortcode for this.

Used as intended, the image render hook works as intended. With an image render hook:

1. If you include a markdown image within the body of a markdown paragraph, the image is _not_ wrapped with extra `<p>` tags.

   ```
   Able was I ![alt](a.jpg "title") ere I saw Elba.
   ```

   Produces:

   ```
   <p>Able was I <img alt="alt" src="a.jpg" title="title"> ere I saw Elba.</p>
   ```

2. If you place a markdown image on its own line (not part of another paragraph), the image _is_ wrapped in `<p>` tags. 

   ```
   Able was I
   
   ![alt](a.jpg "title")
   
   ere I saw Elba.
   ```

   Produces:

   ```
   <p>Able was I</p>
   <p><img alt="alt" src="a.jpg" title="title"></p>
   <p>ere I saw Elba.</p>
   ```

And both of these examples conform to the CommonMark specification. You can [test here](https://spec.commonmark.org/dingus/?text=Able%20was%20I%20!%5Balt%5D(a.jpg%20%22title%22)%20ere%20I%20saw%20Elba.%0A%0AAble%20was%20I%0A%0A!%5Balt%5D(a.jpg%20%22title%22)%0A%0Aere%20I%20saw%20Elba.%0A).

**Comment by bep** [comment] 2021-04-20 09:37
Given  what @jmooring says, I'm closing this. A fix for this, if we would want to fix it, is much too much bandwith for this project to handle (without throwing other stuff out with the bath water).

**Closed by bep** 2021-04-20 09:37 UTC
Labels: Bug, Enhancement, Markdown
