### ISSUE TITLE
Cache directory should be specific to user

### ISSUE THREAD

**Issue by kernelwarrior** [gohugoio/hugo#9452] opened 2022-02-01 18:38 UTC
**Nature of issue:**

This feature of current code prevents the use of Hugo in a multi-user operating system (e.g., Gnu/Linux) by more than one user.

The build fails for the second user with the message:
```bash
$ hugo
Total in 1 ms
Error: add site dependencies: create deps: failed to create file caches from configuration: mkdir /tmp/hugo_cache/foo: permission denied
```

**Hugo version/OS:**

Observed in ```hugo v0.83.1+extended linux/amd64``` (built from source)

**Reason for error:** 

the default cache location ```/tmp/hugo_cache``` was created and is owned by the first user and the second user has not got the required write permission.

(Any user without root privileges would be mystified by this error as they may be unaware of other users' existence.)

**How to reproduce error:**

1. Install Hugo on a multi-user OS
2. Log in as user A, create a minimal Hugo project, and run Hugo to build the project
3. Log in as user B, create a minimal Hugo project, and run Hugo to build the project

**Workarounds** (all clumsy): 
1. Get each user to set a personal cache directory in each project's ```config.toml``` (or equivalent).
     - How to do this should be documented [here](https://gohugo.io/getting-started/configuration/#configure-file-caches) but is *not* explained there or anywhere on that page. A reader familiar with Hugo configuration might infer that the following line (or similar) should be added near the top of ```config.toml``` but a beginner would not.
            -  ```cacheDir = "<absolute path to home directory>/tmp/hugo_cache"```
     -  if this key is set to a relative rather than an absolute path, hugo fails with the error (e.g.)
            -   ```Error: "tmp/hugo-cache/foo" must resolve to an absolute directory```
            -  this requirement to use an absolute path isn't documented either.
2. Each user should set an environment variable ```HUGO_CACHEDIR```
3. The installer should set the above environment variable (if Hugo is installed locally rather than globally).
     - some of the installation methods documented [here](https://gohugo.io/getting-started/installing/) result in a global installation, making this workaround problematic.
     - it's unclear why local installations of Hugo default to a global location for the cache.
4. Execute hugo with the following command
     - ```env HUGO_CACHEDIR=foo hugo```

**Suggested solution:**
Change the default cache directory from ```/tmp/hugo_cache```  to (say) ```~/tmp/hugo_cache``` 

**Alternative solution:**
If there is some perceived performance benefit in having the cache directory under ```/tmp/``` or ```/opt/build/cache/```, etc, it should be named ```/tmp/hugo_cache/`whoami` ```, e.g., ```/tmp/hugo_cache/janedoe```.

**Comment by jmooring** [comment] 2022-02-01 19:30
Duplicate of https://github.com/gohugoio/hugo/issues/7391

**Closed by jmooring** 2022-02-01 19:30 UTC
Labels: Duplicate
