### ISSUE TITLE
Hugo memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kusime** [gohugoio/hugo#8190] opened 2021-01-31 03:02 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
$Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z

</pre>

### Does this issue reproduce with the latest release?
yes

**MY ENV**
Linux mylinux 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

>>>hugo server -D
Building sites … panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xfae390]

goroutine 199 [running]:
github.com/gohugoio/hugo/hugolib.(*shortcodeHandler).extractShortcode(0xc000a289c0, 0x0, 0x1, 0xc000ad5a60, 0x1, 0xc000ad5e00, 0x0)
	github.com/gohugoio/hugo/hugolib/shortcode.go:499 +0x550
github.com/gohugoio/hugo/hugolib.(*shortcodeHandler).extractShortcode(0xc000a289c0, 0x2, 0x0, 0xc000ad5a60, 0x1, 0x1, 0x18bd660)
	github.com/gohugoio/hugo/hugolib/shortcode.go:478 +0x30b
github.com/gohugoio/hugo/hugolib.(*pageState).mapContent(0xc000db8b70, 0xc000b7dfc0, 0xc000d8a500, 0xc000bf9480, 0x2114840)
	github.com/gohugoio/hugo/hugolib/page.go:783 +0xb96
github.com/gohugoio/hugo/hugolib.(*pageMap).newPageFromContentNode(0xc0003dd320, 0xc000cb6240, 0xc000b7dfc0, 0x0, 0x0, 0x0, 0x0)
	github.com/gohugoio/hugo/hugolib/content_map_page.go:164 +0x652
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages.func1(0xc000c00270, 0x23, 0x19a2b20, 0xc000cb6240, 0xc000d3dd00)
	github.com/gohugoio/hugo/hugolib/content_map_page.go:358 +0x16d
github.com/armon/go-radix.recursiveWalk(0xc000cb62a0, 0xc000d3ddf0, 0xc52000)
	github.com/armon/go-radix/radix.go:519 +0xf0
github.com/armon/go-radix.recursiveWalk(0xc000cb6270, 0xc000d3ddf0, 0xf88600)
	github.com/armon/go-radix/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc000cb61e0, 0xc000d3ddf0, 0x0)
	github.com/armon/go-radix/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc000c7b230, 0xc000d3ddf0, 0x0)
	github.com/armon/go-radix/radix.go:525 +0x7e
github.com/armon/go-radix.(*Tree).Walk(...)
	github.com/armon/go-radix/radix.go:447
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages(0xc0003dd320, 0x0, 0x0)
	github.com/gohugoio/hugo/hugolib/content_map_page.go:331 +0xec
github.com/gohugoio/hugo/hugolib.(*pageMaps).AssemblePages.func1(0xc0003dd320, 0x408575, 0xc000b8de60)
	github.com/gohugoio/hugo/hugolib/content_map_page.go:721 +0x68
github.com/gohugoio/hugo/hugolib.(*pageMaps).withMaps.func1(0xdd892f, 0x1c7a901)
	github.com/gohugoio/hugo/hugolib/content_map_page.go:788 +0x2e
github.com/gohugoio/hugo/common/para.(*errGroupRunner).Run.func1(0xc000627768, 0xffffffffffffffff)
	github.com/gohugoio/hugo/common/para/para.go:52 +0x2f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000cb6360, 0xc000b7c960)
	golang.org/x/sync/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync/errgroup/errgroup.go:54 +0x66

mylinux > ~/Desktop/blog >> hugo -v
INFO 2021/01/31 11:00:14 Using config file: 
Building sites … INFO 2021/01/31 11:00:14 syncing static files to /home/yangyiming/Desktop/blog/public/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xfae390]

goroutine 330 [running]:
github.com/gohugoio/hugo/hugolib.(*shortcodeHandler).extractShortcode(0xc000633b00, 0x0, 0x1, 0xc0002a9d40, 0x1, 0xc000231160, 0x0)
	github.com/gohugoio/hugo/hugolib/shortcode.go:499 +0x550
github.com/gohugoio/hugo/hugolib.(*shortcodeHandler).extractShortcode(0xc000633b00, 0x2, 0x0, 0xc0002a9d40, 0x1, 0x1, 0x18bd660)
	github.com/gohugoio/hugo/hugolib/shortcode.go:478 +0x30b
github.com/gohugoio/hugo/hugolib.(*pageState).mapContent(0xc000c09f80, 0xc000a54d40, 0xc000189b80, 0xc000b1a2c0, 0x2114840)
	github.com/gohugoio/hugo/hugolib/page.go:783 +0xb96
github.com/gohugoio/hugo/hugolib.(*pageMap).newPageFromContentNode(0xc000200ba0, 0xc000a91650, 0xc000a54d40, 0x0, 0x0, 0x0, 0x0)
	github.com/gohugoio/hugo/hugolib/content_map_page.go:164 +0x652
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages.func1(0xc0006a7350, 0x23, 0x19a2b20, 0xc000a91650, 0xc000c63d00)
	github.com/gohugoio/hugo/hugolib/content_map_page.go:358 +0x16d
github.com/armon/go-radix.recursiveWalk(0xc000a916b0, 0xc000c63df0, 0xc52000)
	github.com/armon/go-radix/radix.go:519 +0xf0
github.com/armon/go-radix.recursiveWalk(0xc000a91680, 0xc000c63df0, 0xf88600)
	github.com/armon/go-radix/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc000a915f0, 0xc000c63df0, 0x0)
	github.com/armon/go-radix/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc000bd2780, 0xc000c63df0, 0x0)
	github.com/armon/go-radix/radix.go:525 +0x7e
github.com/armon/go-radix.(*Tree).Walk(...)
	github.com/armon/go-radix/radix.go:447
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages(0xc000200ba0, 0x0, 0x0)
	github.com/gohugoio/hugo/hugolib/content_map_page.go:331 +0xec
github.com/gohugoio/hugo/hugolib.(*pageMaps).AssemblePages.func1(0xc000200ba0, 0x0, 0x0)
	github.com/gohugoio/hugo/hugolib/content_map_page.go:721 +0x68
github.com/gohugoio/hugo/hugolib.(*pageMaps).withMaps.func1(0x0, 0x0)
	github.com/gohugoio/hugo/hugolib/content_map_page.go:788 +0x2e
github.com/gohugoio/hugo/common/para.(*errGroupRunner).Run.func1(0xc00075f768, 0x0)
	github.com/gohugoio/hugo/common/para/para.go:52 +0x2f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000a91770, 0xc00088b720)
	golang.org/x/sync/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync/errgroup/errgroup.go:54 +0x66

**Comment by kusime** [comment] 2021-01-31 03:04
i can not run hugo after this bug occur,aways panic

**Comment by kusime** [comment] 2021-01-31 03:07
hugo can not work ! even i reboot the conputer !!

**Comment by kusime** [comment] 2021-01-31 03:10
theme : zzo theme 
error occur at  a zzo theme short code :

{{<box>}}

{{<>}}

**Comment by anthonyfok** [comment] 2021-01-31 09:59
> ### What version of Hugo are you using (`hugo version`)?
> $Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z
> 
> ### Does this issue reproduce with the latest release?
> yes

Just so that you know, what you are running, i.e. v0.68.3 (0.68.3-1 in Ubuntu 20.04 LTS) is not the latest Hugo release.

The newest Hugo release is v0.80.0.  Please test again with the Hugo snap (`snap install hugo`), or perhaps try the release binaries on GitHub, or maybe even the 0.80.0-3 .deb in hirsute-proposed (future Ubuntu 21.04) and see if you could still reproduce this issue?  Thanks!

**Comment by kusime** [comment] 2021-02-11 13:17
@anthonyfok 
why i use apt source to install hugo the latest version is 0.68.3 it show
☺  sudo apt install hugo                                                  
[sudo] password for sss: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
hugo is already the newest version (0.68.3-1).

**Comment by anthonyfok** [comment] 2021-02-11 20:40
> theme : zzo theme
> error occur at a zzo theme short code :
> 
> {{}}
> 
> {{<>}}

If possible, please make the source code of your blog, or better yet, a "minimal working example (abbreviated MWE)", available to us, so we test and try to reproduce your error.

I followed the Zzo theme Getting Started instruction at https://zzo-docs.vercel.app/zzo/gettingstarted/installation/ and did the following:

```
hugo new site zzo-myblog
cd zzo-myblog/
git init
git clone https://github.com/zzossig/hugo-theme-zzo.git themes/zzo
cp -a themes/zzo/exampleSite/* .
hugo server
```

Both Ubuntu 20.04 LTS packaging of Hugo 0.68.3 (which I downloaded from http://lug.mtu.edu/ubuntu/pool/universe/h/hugo/hugo_0.68.3-1_amd64.deb) and the latest hugo_0.80.0-1 in Debian are able to render the website perfectly without any error.

Could you please try what I did and see if you still see any error?

I suspect the "memory address or nil pointer dereference" is partly because you haven't set all the necessary parameters required by the Zzo theme.  Please refer to themes/zzo/exampleSite/ as reference, and try to fix your site.

**Comment by kusime** [comment] 2021-02-12 04:33
Okay , today i try the error page . this bug still can show again on my laptop
,and please [clone the this Repositories](https://github.com/kusime/hugo_bug_report)   
------------------
2878 Desktop/hugo git:(master) » hugo version  
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z

**Comment by anthonyfok** [comment] 2021-02-12 14:35
@kusime, thank you for providing an example.

When tested with Hugo 0.68.3, yes, hugo crashed as you described,
but with the latest Hugo 0.80.0:

```
$ hugo -v
INFO 2021/02/12 07:18:55 Using config file: 
Start building sites … 
INFO 2021/02/12 07:18:55 syncing static files to /home/user/web/hugo_bug_report/public/
Total in 98 ms
Error: Error building site: "/home/user/web/hugo_bug_report/content/en/posts/bug_post.md:36:6": failed to extract shortcode: BUG: template info not set
```
so:

1. So please fix your website code accordingly, but, to do so, you'll likely need the latest Hugo which detects errors on your website gracefully without crashing.
2. 那些空的 `{{}}` 和 `{{<>}}` 好像是不允许的，你检查一下。
2. 乖，听话，我前面请你安装 Hugo 0.80.0 你就乖乖照做吧。你 Ubuntu 20.04 LTS 系统上的 0.68.3-1 是我打包的，Ubuntru 20.04 里的 Hugo 版本就定格在那里，不会再更新的了。不是叫你以后不用 apt-get，而是暂时从 GitHub 这里下载 Hugo 的发布，或者使用 Ubuntu (Canonical) 推崇的 snap，也能安装最新的 Hugo 0.80.0。这样，你要 debug 你的网站就简单多了。

我将来如果有精力，可能会给 Hugo 做个 Ubuntu PPA，以便旧版的 Ubuntu 可以安装到最新的 Hugo 版本，不过这个计划早着呢。在你的系统上暂时用 `snap install hugo`，执行 /snap/bin/hugo 吧，那是 Ubuntu 系统支持的方法，效果也还不错。

As Hugo 0.80.0 now exits gracefully when encountering buggy website source code, there is no Hugo bug here in the latest version.  Closing this issue.

**Closed by anthonyfok** 2021-02-12 14:35 UTC
Labels: Invalid
