### ISSUE TITLE
Multilingual Mode - Bug when "url" defined in .md starts with / followed by language

### ISSUE THREAD

**Issue by jeremielp** [gohugoio/hugo#8765] opened 2021-07-16 03:07 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.85.0-724D5DB5 windows/amd64 BuildDate=2021-07-05T10:46:28Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

-----

In Multilingual Mode, I face a problem while defining url of pages in .md files, when these url start by a slash followed by the same letters as the language.

For example, let's assume I have languages [es] and [co] defined

Inside my [es] content directory, i put:
- In one .md file:
`url: "/escuela/"`

- Another .md file:
`url: "/test-escuela/"`

Inside my [co] content directory, i put:
- In one .md file:
`url: "/correccion/"`

- Another .md file:
`url: "/test-correccion/"`

I have not defined the publishDir for any of the language, so I am expecting the files to be located in

```
/public/es/escuela/
/public/es/test-escuela/
/public/co/correccion/
/public/co/test-correccion/

```
Instead of that, I get

```
/public/escuela/
/public/es/test-escuela/
/public/correccion/
/public/co/test-correccion/

```

It works ok if I remove the slash at the beginning, but it complicates the navigation. I fixed temporarily the issue by changing my url so that they don't match the language code. But wondering what's happening.

**Comment by jmooring** [comment] 2021-07-16 19:59
Related to or duplicate of:

- <https://github.com/gohugoio/hugo/issues/8452>
- <https://github.com/gohugoio/hugo/issues/7733>
- <https://github.com/gohugoio/hugo/issues/7907>

**Comment by jeremielp** [comment] 2021-07-19 00:42
Good to know that it is identified and @exoton already wrote the patch. Hopefully it can be committed soon. Thanks!

**Comment by jmooring** [comment] 2024-04-30 15:35
Minimal example:

```text
git clone --single-branch -b hugo-github-issue-8765 https://github.com/jmooring/hugo-testing hugo-github-issue-8765
cd hugo-github-issue-8765
rm -rf public/ && hugo && tree public
```

When building the site with v0.125.4:

```text
public/
├── co/
│   └── index.html
├── correccion/
│   └── index.html
├── es/
│   └── index.html
├── escuela/
│   └── index.html
├── test-correccion/
│   └── index.html
├── test-escuela/
│   └── index.html
├── favicon.ico
└── index.html
```

This is the correct and expected output given that the front matter `url` fields have a leading slash. Per the [documentation](https://gohugo.io/content-management/urls/#url):

> In a multilingual site:
> 
> - A url value with a leading slash is relative to the baseURL.
> - A url value without a leading slash is relative to the baseURL plus the language prefix.

If I remove the leading slash from each of the `url` front matter fields, the output is also correct and expected as described above:

```text
public/
├── co/
│   ├── correccion/
│   │   └── index.html
│   ├── test-correccion/
│   │   └── index.html
│   └── index.html
├── es/
│   ├── escuela/
│   │   └── index.html
│   ├── test-escuela/
│   │   └── index.html
│   └── index.html
├── favicon.ico
└── index.html
```

**Closed by jmooring** 2024-04-30 15:35 UTC
Labels: Feature: Multilingual
