### ISSUE TITLE
Build randomly fails when output format is imported from a Hugo module

### ISSUE THREAD

**Issue by gcushen** [gohugoio/hugo#8591] opened 2021-05-29 14:18 UTC
There appears to perhaps be an edge/race condition in Hugo causing both `hugo` and `hugo mod clean --all` to randomly fail on a site when the output format is imported from the config of a Hugo module, resulting in a single error like

```
Error: from config: failed to resolve output format "WebAppManifest" from site config
```

To reproduce, create a Hugo module with an `index.webmanifest` layout and the following `config`:

```
mediaTypes:
  application/manifest+json:
    suffixes: [webmanifest]
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
```

Then create a site which imports that module (including its config) and loads that module's output format 
```
outputs:
  home: [ "HTML", "WebAppManifest" ]
```

Running any hugo command will randomly fail with the above error message. May be related to cache issues when a user attempts to update the module?

## `hugo mod clean --all` also then fails to delete the cache

Is it expected that `hugo mod clean --all` fails when Hugo cannot build a site? Can we not prevent the cache deletion command failing by just deleting the contents of Hugo's cache folder without attempting to build the site?

## Workaround

After manually deleting Hugo's cache folder, the Hugo commands work fine again without any changes to the code.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo v0.83.1+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by regisphilibert** [comment] 2021-06-08 00:17
I wonder if this could not be caused by branch switching in git after having upgraded the module etc...

**Comment by bep** [comment] 2021-06-10 11:48
While looking at something else, I notice that we "swallow" an error when loading the configuration from the modules. I will fix that. Which goes to say that the above would still fail, but with a more relevant error.

**Comment by jmooring** [comment] 2024-04-08 19:27
I am unable to reproduce this with v0.124.1.

```text
git clone --single-branch -b hugo-github-issue-8591 https://github.com/jmooring/hugo-testing hugo-github-issue-8591
cd hugo-github-issue-8591
rm -rf public && hugo && tree public
```

Then run the last command repeatedly. There are no failures.

**Comment by jmooring** [comment] 2024-04-29 10:31
Closing per previous comment.

**Closed by jmooring** 2024-04-29 10:31 UTC
Labels: Bug
