### ISSUE TITLE
Support to Hugo extend for linux arm64

### ISSUE THREAD

**Issue by fike** [gohugoio/hugo#8745] opened 2021-07-12 01:43 UTC
Hi,

I'm using Hugo Extend for my sites in the Linux Arm server (Ampere), I built Hugo for that, but I think it could be great to release a Hugo Extend version for Linux ARM64. I take a look the goreleaser file, and it seems that it just adds a line there. e.g.:

```
[...]

    id: hugo_extended_linux
    ldflags: -s -w -X github.com/gohugoio/hugo/common/hugo.buildDate={{.Date}} -X github.com/gohugoio/hugo/common/hugo.commitHash={{ .ShortCommit }} -X github.com/gohugoio/hugo/common/hugo.vendorInfo=gohugoio
    env:
      - CGO_ENABLED=1
    flags:
      - -buildmode
      - exe
      - -tags
      - extended
    goos:
      - linux
    goarch:
      - amd64
      - arm64
 
[...]

```

Is it right? I can create PR if a good thing. :)

**Comment by bep** [comment] 2021-07-12 09:02
>I take a look the goreleaser file, and it seems that it just adds a line there.

No, that will not work. 

We build this from one single Docker container and each target GOARCH needs a working build setup for C/C++. Turns out, this isn't trivial (it's easy to do AMD64 OR ARM64, but not both at the same time).

That said, this is duplicate of #8257

**Closed by bep** 2021-07-12 09:02 UTC
Labels: Proposal
