### ISSUE TITLE
create newpost page fail

### ISSUE THREAD

**Issue by wow-yorick** [gohugoio/hugo#10318] opened 2022-09-23 08:41 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.103.1+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
no
![image](https://user-images.githubusercontent.com/3367220/191923224-8d2f5ca2-cb36-4231-9d16-36dfad76bd01.png)

**Comment by wow-yorick** [comment] 2022-09-26 02:06
my postdir  is symbolic links

**Comment by vitbaisa** [comment] 2022-11-25 17:18
I have the same issue in 
`hugo v0.92.2+extended linux/amd64 BuildDate=2022-02-23T16:47:50Z VendorInfo=ubuntu:0.92.2-1`
(after upgrading Ubuntu from 20.04 LTS to 22.04 LTS.

All `./content/*` dirs are symlinks to `./*` dirs. E.g. `./content/books -> ./books`.

Running `hugo new books/xxx.md` fails with:

```
anic: [BUG] no Page found for "/home/xbaisa/eb/content/books/xxx.md"

goroutine 1 [running]:
github.com/gohugoio/hugo/create.(*contentBuilder).applyArcheType(0xc0001fec00, {0xc0009e08a0, 0x24}, {0xc0003681e0, 0x8})
	github.com/gohugoio/hugo/create/content.go:276 +0x354
github.com/gohugoio/hugo/create.(*contentBuilder).buildFile(0xc0001fec00)
	github.com/gohugoio/hugo/create/content.go:244 +0x1ad
github.com/gohugoio/hugo/create.NewContent.func1()
	github.com/gohugoio/hugo/create/content.go:104 +0x297
github.com/gohugoio/hugo/create.NewContent(0xc00044cdc0, {0x0, 0x0}, {0x7ffd96cd225a, 0x8adb05})
	github.com/gohugoio/hugo/create/content.go:108 +0x5fe
github.com/gohugoio/hugo/commands.(*newCmd).newContent(0xc000105c80, 0xc000154280, {0xc0002265b0, 0x1, 0x0})
	github.com/gohugoio/hugo/commands/new.go:83 +0x150
github.com/spf13/cobra.(*Command).execute(0xc000154280, {0xc000226580, 0x1, 0x1})
	github.com/spf13/cobra/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003a0f00)
	github.com/spf13/cobra/command.go:974 +0x3bc
github.com/gohugoio/hugo/commands.Execute({0xc00003c0a0, 0x2, 0x2})
	github.com/gohugoio/hugo/commands/hugo.go:92 +0xb4
main.main()
	github.com/gohugoio/hugo/main.go:23 +0x58
```

And the content of the `./books/xxx.md` is this:

```
---
title: "Content Placeholder"
_build:
  render: never
  list: never
  publishResources: false
---
```

The corresponding `./archetypes/books.md` is this:

```
---
date: {{ dateFormat "2006-01-02" .Date }}
author: 
title: 
subtitle: 
summary: 
started: {{ dateFormat "2006-01-02" .Date }}
finished: 
language: en
tags: [current, favourite, audiobook]
score: 
---

```

**Comment by vitbaisa** [comment] 2022-11-25 17:23
## Does this issue reproduce with the latest release?

Yes. The same behaviour with `hugo v0.107.0-2221b5b30a285d01220a26a82305906ad3291880 linux/amd64 BuildDate=2022-11-24T13:59:45Z VendorInfo=gohugoio`

**Comment by vitbaisa** [comment] 2022-11-25 17:28
Seems like this one is duplicate of [Panic with hugo new if target folder is a symbolic link](https://github.com/gohugoio/hugo/issues/9537)

**Comment by jmooring** [comment] 2022-11-25 17:37
Duplicate of #9537.

Use mounts instead. In site configuration:

```
[[module.mounts]]
source = '/home/jsmith/temp'
target = 'content'
```

**Closed by jmooring** 2022-11-25 17:37 UTC
Labels: Bug, Duplicate, NeedsTriage
