### ISSUE TITLE
A title with a # will generate invalid links

### ISSUE THREAD

**Issue by vanbroup** [gohugoio/hugo#11890] opened 2024-01-15 13:23 UTC
```md
---
date: 2024-01-15 14:00:00
title: A title with a # will generate invalid links
type: post
---

Some content here
```
config.yaml
```
permalinks:
  posts: /:year/:month/:day/:title/
```

Will generate a link like: "/2024/01/15/a-title-with-a-#-will-generate-invalid-links/", where everything after the # will be treated as a fragment.

**Comment by jmooring** [comment] 2024-01-15 15:39
Duplicate of https://github.com/gohugoio/hugo/issues/4926.

Workaround (sort of):

- `posts: /:year/:month/:day/:slug/`
- The `slug` token will return the title if no slug is provided in the front matter
- Set `slug` in the front matter as needed (e.g., `slug: something without a hash mark`)

**Closed by jmooring** 2024-01-15 15:39 UTC
Labels: Bug, NeedsTriage

**Comment by vanbroup** [comment] 2024-01-15 18:13
Thanks @jmooring, sorry that I missed that, that issue is 6y old 🤔

It doesn't sound as difficult problem to resolve, manually setting the slug is not something that is easy to explain to users and this doesn't seem to be an intended behavior.

I was looking to create a quick fix but couldn't find where the urlize runs, I thought in permalink.go any suggestions where this is handled? Maybe I can create a fix including some new tests.

**Comment by jmooring** [comment] 2024-01-15 18:25
I wouldn't spend any time on this until https://github.com/gohugoio/hugo/pull/11830 is merged and the dust settles.
