### ISSUE TITLE
A way to access content after <!--more--> marker

### ISSUE THREAD

**Issue by ghost** [gohugoio/hugo#716] opened 2014-12-15 11:52 UTC
Currently one can get either the summary (`.Summary`) or all the content (`.Content`), but there's no way to access only the content after the  marker, through a variable like `.MoreContent`, for example. In my case the summary and the rest are completely separate entities.

**Comment by anthonyfok** [comment] 2015-03-13 12:16
Hi @opennota,
Is there a reason why you closed this issue before it was fixed?  :-)

**Comment by opennota** [comment] 2015-03-13 12:28
@anthonyfok I don't need it anymore, and it doesn't look like anyone else is interested.

**Comment by abirger** [comment] 2015-03-13 14:11
@opennota, actually I would very much like this feature. I missed #716 and #718 in the first place, and I am glad that I've seen them now.

**Comment by anthonyfok** [comment] 2015-03-13 16:47
Let's reopen this issue then!  ;-)

**Comment by bep** [comment] 2015-03-13 17:20
+1

**Comment by Dr-Terrible** [comment] 2015-05-06 23:10
+1

**Comment by bep** [comment] 2015-05-07 00:13
@Dr-Terrible for the BF related issues, see https://github.com/russross/blackfriday/issues/166

**Comment by Dr-Terrible** [comment] 2015-05-07 09:18
@bep Thank you, your idea about separate entities makes more sense. I didn't think about the ToC either.

**Comment by matthewdolman** [comment] 2016-07-27 08:55
+1

I would like this.  In fact the more that we can define sections in our content the better.

**Comment by matthewdolman** [comment] 2016-07-27 09:08
If anyone is looking for a quick workaround for now you can do this:

{{ $body := replace .Content .Summary "" }}
{{ $body | safeHTML }}

**Comment by bep** [comment] 2017-02-28 19:09
This issue has been automatically marked as stale because it has not been commented on for at least four months.

The resources of the Hugo team are limited, and so we are asking for your help.

If this is a **bug** and you can still reproduce this error on the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still valuable, please open a proposal at https://discuss.gohugo.io/.

This issue will automatically be closed in four months if no further activity occurs. Thank you for all your contributions.

**Comment by bep** [comment] 2017-03-01 09:22
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by f3l1x** [comment] 2017-06-07 06:08
I like an idea. :+1: What can I do for it?

**Comment by edio** [comment] 2019-03-30 02:55
Is there an interest in this?

My PR didn't get any attention and eventually became scale. And yet issue remains open.
I could prepare a PR again, but would like to know first if project maintainers are interested in this feature.

**Comment by rto** [comment] 2021-11-13 18:40
+1 for this enhancement.

Two potential uses for this that immediately jump to mind (I'm longing for the first one)

1) You have a 'read mode' link to expand and show the remainder of the content (potentially useful on a section page where you have some descriptive content (drawn from the relevant _index.md) displayed prior to the list of pages within that section. Especially on mobile you may wish to hide the full content.

2) On a page (err..) page where you want to use 'read more' to trigger some kind of analytics event that the user has engaged with the content.

**Comment by davidsneighbour** [comment] 2021-11-14 01:41
I know this is probably considered "just a workaround", but with [findRE](https://gohugo.io/functions/findre/) you should be able to match "everything after `<-- more -->` for these uncommon use cases.

**Comment by curegit** [comment] 2023-01-30 07:03
I like this idea 👍  because I always put ToC after Summary

**Comment by bwc69151** [comment] 2023-05-13 09:36
My use case (something I did in WP) is to have the read more link in list pages jump straight to the text after the summary when the article opens instead of the beginning.

**Closed** 2024-08-29 14:45 UTC
Labels: Enhancement, Keep, Feature: Summary
