### ISSUE TITLE
Partial Static Sync

### ISSUE THREAD

**Issue by spf13** [gohugoio/hugo#1644] opened 2015-11-29 15:49 UTC
Today Hugo synchronizes the entire static directory each time a file change is detected. While it only copies the changed file(s), it still goes through the process of evaluating all files on both sides to determine which file needs to be synced. This isn't necessary as we already know what file changed. We should just sync that file.

**Comment by anthonyfok** [comment] 2015-12-28 12:10
Hello @ffrizzo,

Thank you for your contribution, @ffrizzo!  But I think I encountered a bug in your current implementation in #1671: the static directory in the theme is not synchronized.  It detects that I changed the style.css (which is inside the theme's static/ directory), but it is probably trying to copy it from the wrong place.

**Comment by ffrizzo** [comment] 2015-12-28 12:32
Hello @anthonyfok ,

I'll take a look on that and I'll submit a new pull request with the fix.

**Comment by Skrylar** [comment] 2016-02-17 00:19
On my box, it actually copies a bit more than just the changed file. Every single file is written to the output directory for every single run of hugo, with the exception of those in the static files directory.

**Comment by spf13** [comment] 2016-02-18 22:26
@Skrylar can you provide more information about that? Can you paste the output running with `--verbose`?

**Comment by Skrylar** [comment] 2016-02-21 06:09
@spf13 
```
INFO: 2016/02/21 00:08:56 hugo.go:439: Using config file: c:\Dev\Hugotest\config.toml
WARN: 2016/02/21 00:08:56 hugo.go:522: Unable to find Theme Static Directory:
INFO: 2016/02/21 00:08:56 hugo.go:542: c:\Dev\Hugotest\static\ is the only static directory available to sync from
INFO: 2016/02/21 00:08:56 hugo.go:580: syncing static files to c:\Dev\Hugotest\public\
INFO: 2016/02/21 00:08:56 site.go:1275: found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
WARN: 2016/02/21 00:08:56 site.go:1995: Unable to locate layout for 404 page: [404.html]
WARN: 2016/02/21 00:08:56 site.go:1971: "404.html" is rendered empty
0 draft content
0 future content
10 pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
in 31 ms
```

If I force the cache directory to be somewhere (ex. in the "cache" folder of the same directory), no files are left behind there. I'm not sure if that's intended or a symptom.

**Comment by jdevoo** [comment] 2016-05-24 08:19
I just wanted to contribute an issue with the static folder not showing the contributed files from the theme on a Windows machine. My post on the forum [here](https://discuss.gohugo.io/t/new-site-misses-theme-css-img-files/3109/9).
When I create the css and img folders manually, the content is correctly added. I thought I would mention this under partial static sync.

**Comment by bep** [comment] 2017-07-01 07:49
This issue has been automatically marked as stale because it has not been commented on for at least six months.

The resources of the Hugo team are limited, and so we are asking for your help.

If this is a **bug** and you can still reproduce this error on the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

This issue will automatically be closed in the near future if no further activity occurs. Thank you for all your contributions.

**Comment by bep** [comment] 2017-07-01 15:02
@jdevoo this issue isn't really about your problem.

**Comment by bep** [comment] 2017-07-01 15:06
But then again, I'm pretty sure that this "syncing issue" described in the first post also should be fixed now, by what I can read in the code and by testing; we only sync the path matching the change event(s). Can you confirm, @spf13 ?

**Closed** 2017-11-27 21:53 UTC
Labels: Enhancement, Keep, NeedsUserFeedback
