### ISSUE TITLE
Term page is empty if slug contains special characters (such as ' or ó)

### ISSUE THREAD

**Issue by CamilleScholtz** [gohugoio/hugo#12086] opened 2024-02-20 21:09 UTC
### Version

0.123, this did not happen in 0.122 and earlier versions.

### Reproduction

I have an authors section/taxonomy, the terms have an _index.md with some frontmatter and a description. I have one author with the name "Tólma", the markdown location of this user is `content/authors/tolma/_index.md`. This makes it so that when iterating over pages in the authors list the tolma page is empty.

If I rename the directory `content/authors/tólma/_index.md` it works, however then the directory name no longer corresponds to the slug, and I will have weird characters in my directory. Also this was not needed in earlier Hugo versions. Is this new intended behavior or a bug?

`removePathAccents` in config is set to true.

A screenshots that should illustrate this problem a bit more visually:

<img width="932" alt="image" src="https://github.com/gohugoio/hugo/assets/5213535/1a4d0141-187f-4c03-b272-80f9d2961be1">

**Comment by jmooring** [comment] 2024-02-21 03:46
The new behavior is intentional, but I'm not sure I understand the problem. Please take this for a spin and let me know what's wrong with it:

```text
git clone --single-branch -b hugo-github-issue-12086 https://github.com/jmooring/hugo-testing hugo-github-issue-12086
cd hugo-github-issue-12086
hugo server
```

**Comment by CamilleScholtz** [comment] 2024-02-22 16:05
This seems to work just fine, also when renaming the directory to `tolma`... I suspect maybe something goes wrong when calling the `.Pages` variable in a taxonomy list template, and not when calling `.RegularPages` in the home template like in your repository? I will test this tonight.

**Comment by jmooring** [comment] 2024-02-24 18:22
@CamilleScholtz In the interest of keep our v0.123.x issue list clean, I am closing this for now. We can re-open if necessary, but everything looks right to me.

**Comment by CamilleScholtz** [comment] 2024-02-25 23:54
Some more elaboration, I still don't know why this is exactly intended behavior, especially because it did work in previous versions.

Everything in the documentation makes it seem that (template-backed term) paths are slugs. All paths in my content directory (unless explicitly overwritten) correspond to the slug. Yet for a term titled `Rainer Wüssle`, where the slug is `rainer -wussle`, the directory should now be named `rainer-wüssle`.

Another case where a term with the title `‘Het Dorp’ Genieter` could previously be in the directory `het-dorp-genieter`, it now requires the name `‘het-dorp’-genieter`. Is this really intended behavior?

**Comment by jmooring** [comment] 2024-02-26 00:26
In a previous comment you wrote, "This seems to work just fine." Is that no longer true?

> Everything in the documentation makes it seem that (template-backed term) paths are slugs.

Please point me to that portion of the documentation and I will make the necessary corrections or clarifications.

> Yet for a term titled Rainer Wüssle, where the slug is rainer-wussle, the directory should now be named rainer-wüssle.

Yes, that is the intended behavior. You have enabled `removePathAccents` which is why Hugo removed the path accents from the URL. But internally Hugo v0.123.0 and later uses [logical paths] to identify content. And a term page is content. As noted in the documentation, a logical path is neither a file path or a URL/slug.


[logical paths]: https://gohugo.io/getting-started/glossary/#logical-path

**Comment by CamilleScholtz** [comment] 2024-02-26 00:38
>Please point me to that portion of the documentation and I will make the necessary corrections or clarifications.

I could not find anywhere explicitly written how they are actually defined. There is [this section](https://gohugo.io/content-management/taxonomies/#add-custom-metadata-to-a-taxonomy-or-term) which uses `bruce-willis` for term `Bruce Willis`, which seemed to me to be a slug. I now understand however that this is a logical path!

 The logical path link cleared things up for me, since I was under the impression these were slugs. Thanks.

**Closed** 2024-02-26 00:39 UTC
Labels: Bug, NeedsUserFeedback, NotSure, v0.123.0
