### ISSUE TITLE
With defaultContentLanguageInSubdir: true, a robots.txt file should be created at the root

### ISSUE THREAD

**Issue by martignoni** [gohugoio/hugo#5160] opened 2018-09-04 12:01 UTC
With `defaultContentLanguageInSubdir: true`, various `robots.txt` files are wrongly created in languages subdirs, and no `robots.txt` is created at the root of the website.

Refs: 
- RFC: https://datatracker.ietf.org/doc/draft-koster-rep/
- https://en.wikipedia.org/wiki/Robots_exclusion_standard

See: https://discourse.gohugo.io/t/multilingual-site-always-get-a-noindex-tag-in-root-index-html

**Comment by divinerites** [comment] 2018-09-04 12:10
Thanks a lot @martignoni.

And I suspect this will lead to the same issue for 404 page (see https://discourse.gohugo.io/t/404-html-not-generated-on-root-if-defaultcontentlanguageinsubdir-true/14048).

A bundle 😸

**Comment by martignoni** [comment] 2019-01-03 09:07
Still present as of Hugo 0.53.

**Comment by davidsneighbour** [comment] 2019-02-19 10:45
I am not sure if I understand that right, but if in Hugo's current configuration there is no robots.txt in the root directory and the language directories have one individual robots.txt each, then this is against the way robots.txt is supposed to work:

https://support.google.com/webmasters/answer/6062596?hl=en

Robots.txt has to be always at the domain root, not in a subfolder. If that is what happens here it should be marked as a bug, not an enhancement.

**Comment by ulziibay** [comment] 2019-05-07 16:45
Hello @martignoni, I believe I ran into issue after reading https://discourse.gohugo.io/t/how-to-have-root-static-folder-with-multilingual-setup/16902/2. I have a quesiton, 
with this issue withstanding, how does your toy website at https://github.com/moodlebox/moodlebox.net/blob/master/config.yml, know to put the `robots.txt`,	`sitemap.xml` at the root of `public` folder as well as in `public/en` and `public/de` and `public/fr`?
With my current config below, I am unable to get `hugo` to copy over the robot.txt file or the sitemap.xml.

At the moment, https://mitpu.org/ DO NOT redirect to https://mitpu.org/en, unliked your website.

Thanks.
```
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
baseURL = "https://mitpu.org/"
languageCode = "en-us"
title = "MITPU"
theme = "timer-hugo"
disqusShortname = "mitpu"

# Enable robots.txt generation
enableRobotsTXT = true

# We do redirects via Netlify's _redirects file, generated by Hugo (see "outputs" below).
disableAliases = true

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/v2/

[languages]
    [languages.en]
        languageName = "English"
        title = "MITPU"
        contentDir = "content/en"
        weight = 2
        baseURL = "https://mitpu.org/en"

        # Site Menus
        [languages.en.menu]
            # Navbar Menus
            [[languages.en.menu.nav]]
                name    = "Hobby Groups"
                url     = "/groups"
                weight  = 2
            [[languages.en.menu.nav]]
                name    = "Podcast"
                url     = "/podcast"
                weight  = 3
            [[languages.en.menu.nav]]
                name    = "Referral"
                url     = "/referral"
                weight  = 4
            [[languages.en.menu.nav]]
                name    = "About"
                url     = "/about"
                weight  = 5
            [[languages.en.menu.nav]]
                name    = "Contact"
                url     = "/contact"
                weight  = 6

        # Site Params
        [params]
            home = "Home"
            dateFormat = "6 January 2006"
            #
            # You can use either an image or text as logo.
            # To use an image use 'logo' (logo itself) and 'logo_alt' (alternative text if image cannot displayed)
            # To use text as logo use 'logo_text'
            logo = "images/logo.png"
            logo_alt = "logo"
            #logo_text = "logo_text"

            # Banner Section
            [params.banner]
                enable  = true
                bgImage = "images/mitpu_background.jpg"
                heading = "Welcome to MITPU & We are a "
                btn     = true
                btnText = "Join now"
                btnURL  = "https://www.facebook.com/groups/582198341944244/"
                [[params.banner.flipText]]
                    title   = "Group of diverse talents"
                [[params.banner.flipText]]
                    title   = "501C certified NPO"
                [[params.banner.flipText]]
                    title   = "Community"

            # Homepage About Section
            [params.about]
                enable  = true
                title   = "MITPU Facts"
                image   = "images/about/mitpu_background.jpg"
                [[params.about.content]]
                    subtitle = "250"
                    description = "members"
                [[params.about.content]]
                    subtitle = "237"
                    description = "active members"
                [[params.about.content]]
                    subtitle = "189"
                    description = "requests that did not meet criteria"
                [[params.about.content]]
                    subtitle = "134"
                    description = "members who completed contact form"
                [[params.about.content]]
                    subtitle = "91"
                    description = "members who introduced #танилцья #introduction"
                [[params.about.content]]
                    subtitle = "190"
                    description = "Total number of posts"
                [[params.about.content]]
                    subtitle = "679"
                    description = "Total number of comments"
                [[params.about.content]]
                    subtitle = "2222"
                    description = "Total number of reactions"
                [[params.about.content]]
                    subtitle = "4"
                    description = "admins"
                [[params.about.content]]
                    subtitle = "5"
                    description = "board members"


            # Portfolio Section On Homepage
            [params.portfolio]
                enable  = true
                title   = "Latest Works"

    [languages.mn]
        languageName = "mongolian"
        baseURL = "https://mitpu.org/mn"
        title = "MITPU"
        contentDir = "content/mn"
        weight = 1
        # Navbar Menus
        [languages.mn.menu]
            [[languages.mn.menu.nav]]
                name    = "Хобби бүлэг"
                url     = "/groups"
                weight  = 2
            [[languages.mn.menu.nav]]
                name    = "Подкаст"
                url     = "/podcast"
                weight  = 3
            [[languages.mn.menu.nav]]
                name    = "Ажлын байрны зууч"
                url     = "/referral"
                weight  = 4
            [[languages.mn.menu.nav]]
                name    = "Бидний тухай"
                url     = "/about"
                weight  = 5
            [[languages.mn.menu.nav]]
                name    = "Холбогдох"
                url     = "/contact"
                weight  = 6

        # Site Params
        [languages.mn.params]
            home = "Нүүр"
            dateFormat = "2006/01/29"
            #
            # You can use either an image or text as logo.
            # To use an image use 'logo' (logo itself) and 'logo_alt' (alternative text if image cannot displayed)
            # To use text as logo use 'logo_text'
            logo = "images/logo.png"
            logo_alt = "logo"
            #logo_text = "logo_text"

            # Banner Section
            [languages.mn.params.banner]
                enable  = true
                bgImage = "images/mitpu_background.jpg"
                heading = "MITPU-д тавтай морил & Бид бол "
                btn     = true
                btnText = "Бидэнтэй нэгдэх"
                btnURL  = "https://www.facebook.com/groups/582198341944244/"
                [[params.banner.flipText]]
                    title   = "Group of diverse talents"
                [[languages.mn.params.banner.flipText]]
                    title   = "501C-р баталгаажсан ашгийн бус байгууллага"
                [[params.banner.flipText]]
                    title   = "Community"

            # Homepage About Section
            [languages.mn.params.about]
                enable  = true
                title   = "MITPU-н үзүүлэлтүүд"
                image   = "images/about/mitpu_background.jpg"
                [[languages.mn.params.about.content]]
                    subtitle = "250"
                    description = "гишүүн"
                [[languages.mn.params.about.content]]
                    subtitle = "237"
                    description = "идэвхтэй гишүүн"
                [[languages.mn.params.about.content]]
                    subtitle = "189"
                    description = "хүсэлтийг шаардлага хангаагүйн улмаас цуцалсан"
                [[languages.mn.params.about.content]]
                    subtitle = "134"
                    description = "гишүүн холбоо барих маягтийг бөглөсөн"
                [[languages.mn.params.about.content]]
                    subtitle = "91"
                    description = "гишүүн өөрсдийгөө танилцуулсан #танилцья"
                [[languages.mn.params.about.content]]
                    subtitle = "190"
                    description = "фб бичвэр/posts"
                [[languages.mn.params.about.content]]
                    subtitle = "679"
                    description = "сэтгэгдэл/comments"
                [[languages.mn.params.about.content]]
                    subtitle = "2222"
                    description = "Хариу үйлдэл / reactions"
                [[languages.mn.params.about.content]]
                    subtitle = "4"
                    description = "админ"
                [[languages.mn.params.about.content]]
                    subtitle = "5"
                    description = "ТУЗ-ийн гишүүн"


            # Portfolio Section On Homepage
            [languages.mn.params.portfolio]
                enable  = true
                title   = "Сүүлийн үед гүйцэтгэсэн ажлууд"


    # Footer section
    [params.footer]
        customized  = true # Set this variable to true if you customized the design.
        copyright_owner = "Themefisher"
        copyright_since = "2018"
        [[params.footer.social]]
            icon = "ion-social-facebook"
            link = "https://www.facebook.com/groups/582198341944244/"
        [[params.footer.social]]
            icon = "ion-social-linkedin"
            link = "https://linkedin.com"
        [[params.footer.social]]
            icon = "ion-social-gitlab"
            link = "https://gitlab.com/mitpu/"
```

**Comment by martignoni** [comment] 2019-05-07 16:53
> with this issue withstanding, how does your toy website at https://github.com/moodlebox/moodlebox.net/blob/master/config.yml, know to put the robots.txt, sitemap.xml at the root of public folder as well as in public/en and public/de and public/fr

`sitemap.xml` is created automatically by Hugo in all language subfolders, but not `robots.txt` and this is the rationale of this issue.

**Comment by ulziibay** [comment] 2019-05-07 16:55
However, in my case sitemap.xml is not even generated at the root, neither is robots.txt

**Comment by martignoni** [comment] 2019-05-07 16:56
This is not a support forum. Ask [here](https://discourse.gohugo.io).

**Comment by ricardoferreiracosta08** [comment] 2020-01-03 14:23
I added in static folder th file robots.txt and worked for me on root site without  enable defaultContentLanguageInSubdir as true

**Comment by yktoo** [comment] 2020-04-09 06:27
The issue is still there in **v0.68.3**, and pressing.

**Comment by nicoduesing** [comment] 2020-06-19 14:43
The issue is still there in **v0.72.0**.

**Comment by davidsneighbour** [comment] 2020-06-19 14:54
I can't believe this is just an issue. A `robots.txt` has to be in the **root directory** of a website. Where _website_ means domain. 

Use case 1: If the language versions are in subdirectories then the robots.txt has to be in the root directory, not the language directories. 

Use case 2: If the language versions are in subdomains the robots.txt needs to be in the root directory of the subdomain. For Hugo this means in the directory where the subdomain of the language is mapped. 

There is no connection to the locations where a Sitemap could/should/might be. Please don't connect these two things. **The `robots.txt` for a domain is in the root directory of that domain.**

**Comment by martignoni** [comment] 2020-06-19 15:11
> There is no connection to the locations where a Sitemap could/should/might be. Please don't connect these two things. The robots.txt for a domain is in the root directory of that domain.

Right. I've updated the description issue.

**Comment by nicoduesing** [comment] 2020-06-19 15:13
If `defaultContentLanguageInSubdir` is 

- `false` the `404.html` and `robots.txt` is generated in the root directory **and** in all language directories.
- `true` it is only generated in all language directories. (Because there is no language rendered in the root directory.) 

So it is wrong in both cases but only gets a problem, if `defaultContentLanguageInSubdir` is set to `true`. In the first case, there are _only_ too many `robot.txt`s.

**Comment by nicoduesing** [comment] 2020-06-19 15:18
In [`hugolib/site_render.go`](https://github.com/gohugoio/hugo/blob/9679023f2b0d7c55b70f23fd94603f301a841079/hugolib/site_render.go#L314) on Lines 314 (and on line 258 for the 404-Page as well) there is `&s.PathSpec.ProcessingStats.Pages` used. I guess each language is it's own "Page", so the robots.txt and 404.html is created on the language directories. 

For the sitemaps there is a differen variable used on line 287: `&s.PathSpec.ProcessingStats.Sitemaps` 

As I'm not a Go developer I don't know, what that variables mean. It is not documented in the code, [where they are declared](https://github.com/gohugoio/hugo/blob/d970327d7b994b495ef3bb468c3e0599b0deef5a/helpers/processing_stats.go#L28), too. I would guess that `Static` should be used or a new type would have to be created. 

Maybe that helps for fixing it.

**Comment by nicoduesing** [comment] 2020-06-20 13:15
I've created a pull request for the `robots.txt` I'm not sure how hugo should behave with the `404.html`. If that should change, too, you can do similar changes for it.

**Comment by martignoni** [comment] 2020-06-20 14:07
AFAIK, `404.html` behavior is currently OK, since its localisation makes sense.

**Closed** 2020-06-20 15:13 UTC
Labels: Enhancement, Keep
