### ISSUE TITLE
`invalid memory address or nil pointer dereference` with latest version of hugo on GitHub Actions

### ISSUE THREAD

**Issue by michaellihs** [gohugoio/hugo#10235] opened 2022-08-31 10:26 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
v0.102.1-e9c3ce16abc391ee5be38f88b0499d0e8e19104c+extended linux/amd64 BuildDate=2022-08-29T12:58:13Z 
</pre>

### Does this issue reproduce with the latest release?

yes

### Description

Since today I am getting the following error in my GH Actions pipeline when building my site via `hugo --minify`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x125c1ea]

goroutine 60 [running]:
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyExpr(0xc000c5ed58, {0x2839be8?, 0x0?}, 0x10)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:862 +0x212a
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyExpr(0xc000c5ed58, {0x2839468?, 0xc0012b2c90?}, 0x1)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:961 +0xba6
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyExpr(0xc000c5ed58, {0x28395e8?, 0xc0012[7](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:8)f7[8](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:9)8?}, 0x0)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:1270 +0x184e
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyExpr(0xc000c5ed58, {0x283[9](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:10)888?, 0xc001292f50?}, 0x1)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:[10](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:11)86 +0x1745
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyExpr(0xc000c5ed58, {0x2839618?, 0xc0012b3[11](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:12)0?}, 0x1)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.[12](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:13).0/js/js.go:1230 +0x2ab
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyExpr(0xc000c5ed58, {0x28395e8?, 0xc00127f7a0?}, 0x0)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:1270 +0x184e
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyExpr(0xc000c5ed58, {0x2839888?, 0xc001292f60?}, 0x1)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:1086 +0x1745
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyExpr(0xc000c5ed58, {0x2839618?, 0xc0012b3170?}, 0x1)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:1228 +0x267
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyExpr(0xc000c5ed58, {0x28395e8?, 0xc00127f7b8?}, 0x0)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:1270 +0x184e
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyStmt(0xc000c5ed58, {0x2839768?, 0xc001292f70?})
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:[13](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:14)8 +0x1765
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyBlockAsStmt(0xc000c5ed58?, 0x36de645?)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:435 +0x92
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyStmt(0xc000c5ed58, {0x28397f8?, 0xc0012b0cc0?})
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:230 +0x7ab
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyStmt(0xc000c5ed58, {0x28398b8?, 0xc0012b3230?})
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:168 +0x4c6
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyBlockStmt(0xc000c5ed58, 0xc0012a3600)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:416 +0x108
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyStmt(0xc000c5ed58, {0x28394f8?, 0xc0012a3600?})
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:179 +0x1330
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyStmt(0xc000c5ed58, {0x28398b8?, 0xc0012b36b0?})
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:168 +0x4c6
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyBlockStmt(0xc000c5ed58, 0xc0012a3400)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:416 +0x108
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyBlockAsStmt(0xc000c5ed58?, 0x36de645?)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:433 +0x79
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyStmt(0xc000c5ed58, {0x28397f8?, 0xc0012b1080?})
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:230 +0x7ab
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyBlockStmt(0xc000c5ed58, 0xc0012aab38)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:416 +0x108
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyFuncDecl(0xc000c5ed58, 0xc0012aab00, 0x0)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:6[15](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:16) +0x30b
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyStmt(0xc000c5ed58, {0x2839858?, 0xc0012aab00?})
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:325 +0x11f3
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyBlockStmt(0xc000c5ed58, 0xc00127a7c8)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:416 +0x108
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyFuncDecl(0xc000c5ed58, 0xc00127a790, 0x1)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:615 +0x30b
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyExpr(0xc000c5ed58, {0x2839828?, 0xc00127a790?}, 0x11)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:1242 +0x1030
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyExpr(0xc000c5ed58, {0x2839558?, 0xc0012b9ce0?}, 0x1)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:1185 +0x5ba
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyExpr(0xc000c5ed58, {0x28395e8?, 0xc00127e1e0?}, 0x0)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:1270 +0x184e
github.com/tdewolff/minify/v2/js.(*jsMinifier).minifyStmt(0xc000c5ed58, {0x2839768?, 0xc001293680?})
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:138 +0x1765
github.com/tdewolff/minify/v2/js.(*Minifier).Minify(0xc00004c338, 0xc0007b3380?, {0x2828ac0, 0xc000c91c80}, {0x282bc20?, 0xc000d441e0?}, 0x4d557f?)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/js/js.go:63 +0x238
github.com/tdewolff/minify/v2.(*M).MinifyMimetype(0xc00007aa00, {0xc000fea258, 0x[16](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:17), 0x16}, {0x2828ac0, 0xc000c91c80}, {0x282bc20, 0xc000d441e0}, 0x0?)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/minify.go:210 +0x[17](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:18)c
github.com/tdewolff/minify/v2/html.(*Minifier).Minify(0xc00004c698, 0xc00007aa00, {0x2828ac0, 0xc000c91c80}, {0x2828a80, 0xc000fc0ae0}, 0x58000?)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/html/html.go:139 +0x1026
github.com/tdewolff/minify/v2.MinifierFunc.Minify(...)
	/root/project/gomodcache/github.com/tdewolff/minify/v2@v2.12.0/minify.go:41
github.com/gohugoio/hugo/minifiers.Client.Transformer.func1({0x28353c8?, 0xc000d3efc0?})
	/root/project/hugo/minifiers/minifiers.go:51 +0xa3
github.com/gohugoio/hugo/transform.(*Chain).Apply(0xc000c5f6e0, {0x2828ac0, 0xc000d19110}, {0x2828a80, 0xc0008af440})
	/root/project/hugo/transform/chain.go:108 +0x3af
github.com/gohugoio/hugo/publisher.DestinationPublisher.Publish({{_, _}, {_, _}, _}, {{0x2828a80, 0xc0008af440}, {{0x2[18](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:19)6[19](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:20)b, 0x4}, {{0x[21](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:22)87dcf, ...}, ...}, ...}, ...})
	/root/project/hugo/publisher/publisher.go:107 +0x1a5
github.com/gohugoio/hugo/hugolib.(*Site).renderAndWritePage(0xc000840000, 0xc0000ed7d0, {0xc00094b5c0, 0x54}, {0xc000a6e378, 0x11}, 0xc00093c7b0, {0x2835378, 0xc0002d80f0})
	/root/project/hugo/hugolib/site.go:1777 +0x795
github.com/gohugoio/hugo/hugolib.pageRenderer(0x115e[26](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:27)5?, 0xc000840000, 0xc00006f7d0?, 0x115e1e6?, 0xc00063ab40?)
	/root/project/hugo/hugolib/site_render.go:138 +0x[28](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:29)7
created by github.com/gohugoio/hugo/hugolib.(*Site).renderPages
	/root/project/hugo/hugolib/site_render.go:[74](https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true#step:4:75) +0x108
```

Since the change in the Markdown seems not to be related to the problem, I am expecting an error in Hugo itself.

See https://github.com/ultra-cycling/blog/runs/8110836547?check_suite_focus=true

Thanks for looking into this!

~Michael

P.S. temporarily solved by downgrading to an older version which apparently fixes the problem.

**Comment by bep** [comment] 2022-08-31 10:38
Duplicate of #10230 (will create a new patch release now)

**Closed by bep** 2022-08-31 10:38 UTC
Labels: Bug, NeedsTriage
