### ISSUE TITLE
HAHAHUGOSHORTCODE-s8-HBHB errors for shortcodes

### ISSUE THREAD

**Issue by SmarterBoy** [gohugoio/hugo#10704] opened 2023-02-07 13:04 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.109.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes.

While using shortcodes `ref` with `{{< ref "/content/abc/ddd.md" >}}`, I got `HAHAHUGOSHORTCODE-s8-HBHB` warning, and if I switched to `{{% ref ... %}}` style, it's resolved. But `{{< >}}` is recommended in Hugo docs.

**Comment by jmooring** [comment] 2023-11-25 16:06
Duplicate of https://github.com/gohugoio/hugo/issues/7416, and the `{{< >}}` notation is not "recommended" anywhere in the documentation.

**Closed by jmooring** 2023-11-25 16:06 UTC
Labels: Duplicate
