### ISSUE TITLE
Sort-by-field of a map doesn't work as documented

### ISSUE THREAD

**Issue by chalin** [gohugoio/hugo#8335] opened 2021-03-17 01:04 UTC
### Hugo version?

```console
$ hugo version
hugo v0.81.0+extended darwin/amd64 BuildDate=unknown
$ type hugo
hugo is hashed (/opt/brew/bin/hugo)
```

### Does this issue reproduce with the latest release?

Yes.

### Details

Suppose we have the following in a site's config:

```
[params]
[params.authors]
  [params.authors.Joe]
    firstName = "Joe"
    lastName  = "Bergevin"
  [params.authors.Derek]
    firstName = "Derek"
    lastName  = "Perkins"
  [params.authors.Tanner]
    firstName = "Tanner"
    lastName  = "Linsley"
```

The data above is from the **[sort](https://gohugo.io/functions/sort/) function page**, except that the two map entries have been swapped. That shouldn't affect sorting on `lastName`, which is documented like this:

```
Authors: {{ range sort .Site.Params.authors "lastName" "desc" }}{{ .lastName }} {{ end }}

→ Outputs Authors: Perkins Linsley Bergevin
```

I don't get this output, instead I get the following:

```
Sort authors "lastName" "desc":
→ Output: Linsley Bergevin Perkins 
→ Expect: Perkins Linsley Bergevin
```

Here is the `test.html` shortcode that I'm using:

```html
<pre><code>Sort authors:
→ Output: {{ range sort .Site.Params.authors }}{{ .firstName }} {{ end }}
→ Expect: Derek Joe Tanner

Sort authors "lastName":
→ Output: {{ range sort .Site.Params.authors "lastName" }}{{ .lastName }} {{ end }}
→ Expect: Bergevin Linsley Perkins

Sort authors "lastName" "desc":
→ Output: {{ range sort .Site.Params.authors "lastName" "desc" }}{{ .lastName }} {{ end }}
→ Expect: Perkins Linsley Bergevin

Sort authors "value":
→ Output: {{ range sort .Site.Params.authors "value" }}{{ .firstName }} {{ end }}
→ Expect: Derek Joe Tanner

Authors:
{{ .Site.Params.authors }}
</code></pre>
```

Strangely, if I change the sort arguments in one place, it affects the sort results in other places in the test -- as if `sort` was destructive.

(I can submit a PR over hugoDocs repo with the test files if you'd like.)

---

Here is the full output from the shortcode:

```
Sort authors:
→ Output: Derek Joe Tanner 
→ Expect: Derek Joe Tanner

Sort authors "lastName":
→ Output: Bergevin Perkins Linsley 
→ Expect: Bergevin Linsley Perkins

Sort authors "lastName" "desc":
→ Output: Linsley Bergevin Perkins 
→ Expect: Perkins Linsley Bergevin

Sort authors "value":
→ Output: Joe Derek Tanner 
→ Expect: Derek Joe Tanner

Authors:
map[derek:map[firstname:Derek lastname:Perkins] joe:map[firstname:Joe lastname:Bergevin] tanner:map[firstname:Tanner lastname:Linsley]]
```

Possibly relevant links:
- https://github.com/gohugoio/hugo/blob/ce96895debb67df20ae24fb5f0f04b98a30cc6cc/tpl/collections/sort_test.go
- https://github.com/gohugoio/hugo/blob/edc5c4741caaee36ba4d42b5947c195a3e02e6aa/tpl/collections/sort.go

**Comment by chalin** [comment] 2021-03-17 13:58
cc @nate-double-u @zacharysarah

**Comment by moorereason** [comment] 2021-03-17 15:51
The issue is that hugo is lowercasing the params map keys.  Your `sortByField` parameter should be lowercased to match:

```
{{ range sort .Site.Params.authors "lastname" }}{{ .lastName }} {{ end }}
```

**Comment by chalin** [comment] 2021-03-17 16:07
Using `"lastname"` as a sort-by-field name gives the expected results.

A few followup questions:

- Is this a bug or a feature?
- If a lowercase comparison is unavoidable, shouldn't the `Sort()` func just lowercase the `sortByField` parameter?
- It would be nice if `sort` reported an error when the named `sortByField` doesn't exist.
- Do you know why using `"value"` as a `sortByField` doesn't sort by keys? (See the output given above.)

**Comment by moorereason** [comment] 2021-03-17 17:48
> Is this a bug or a feature?

The lowercasing of the params keys is a feature.  How sort treats the sortByField is maybe debatable.

> If a lowercase comparison is unavoidable, shouldn't the Sort() func just lowercase the sortByField parameter?

We also need to support things like `{{ sort .Site.RegularPages ".File.FileName" }}` which is case-sensitive.

> It would be nice if sort reported an error when the named sortByField doesn't exist.

Perhaps.

> Do you know why using "value" as a sortByField doesn't sort by keys? (See the output given above.)

I'm assuming it's because not all values (such as maps) are comparable.  So a map of maps will likely not work and leave the sorting unchanged.  May also be another opportunity to provide feedback to the user.

**Comment by jmooring** [comment] 2021-03-24 18:16
Closing. Will be addressed with https://github.com/gohugoio/hugoDocs/issues/1365.

**Closed by jmooring** 2021-03-24 18:16 UTC
