### ISSUE TITLE
Currency format without fractional values

### ISSUE THREAD

**Issue by raoulb** [gohugoio/hugo#9141] opened 2021-11-08 04:09 UTC
The function `lang.FormatCurrency` works as expected with 2 or more decimals:

`{{ 123 | lang.FormatCurrency 4 "EUR" }}`  -> `123,0000 €`

Sometimes one might wish to get outputs like `123 €` f.e. for readability concerns.
These calls:

`{{ 123 | lang.FormatCurrency 0 "EUR" }}`  -> `123,00 €`
`{{ 123 | lang.FormatCurrency 1 "EUR" }}`  -> `123,00 €`
`{{ 123 | lang.FormatCurrency 2 "EUR" }}`  -> `123,00 €`

all give two digits. Instead I would expect the following:

`{{ 123 | lang.FormatCurrency 0 "EUR" }}`  -> `123 €`
`{{ 123 | lang.FormatCurrency 1 "EUR" }}`  -> `123,0 €`
`{{ 123 | lang.FormatCurrency 2 "EUR" }}`  -> `123,00 €`

If for some reason this is not possible, one should extend the [documentation](https://gohugo.io/functions/lang/#langformatcurrency) explaining `precision >= 2`.

**Comment by jmooring** [comment] 2021-11-08 20:03
Duplicate of https://github.com/gohugoio/hugo/issues/8858.

Addressed with https://github.com/gohugoio/hugo/pull/8950.

<img alt="Screen capture" width="70%" src="https://user-images.githubusercontent.com/335669/140809562-cda6ad0c-76cc-4f65-bf6a-0f7557e62101.png">

If you think the documentation needs additional clarification, please create an issue or pull request in https://github.com/gohugoio/hugoDocs. Thanks.

**Closed by jmooring** 2021-11-08 20:03 UTC
Labels: Proposal

**Comment by raoulb** [comment] 2021-11-09 03:23
Never mind. Hidden in plain sight!

Still unfortunate that we can't resolve the "stylistic printing" issue as explained in https://github.com/gohugoio/hugo/issues/8858.
