### ISSUE TITLE
Hugo cant make resources.GetRemote requests on WSL Version 2

### ISSUE THREAD

**Issue by bensonshaji** [gohugoio/hugo#10092] opened 2022-07-15 19:10 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

<pre>
Start building sites … 
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
WARN 2022/07/16 00:28:16 error calling resources.GetRemote: Post "": unsupported protocol scheme ""
WARN 2022/07/16 00:28:16  error calling resources.GetRemote: Post "": unsupported protocol scheme ""
</pre>

However, the issue does not occur when executing the same code Hugo.exe file generated for Windows

<pre>
$hugo.exe version
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
</pre>

WSL Information

<pre>
PS C:\Users\benz_> wsl --status
Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 15-07-2022
The Windows Subsystem for Linux kernel can be manually updated with 'wsl --update', but automatic updates cannot occur due to your system settings.
To receive automatic kernel updates, please enable the Windows Update setting: 'Receive updates for other Microsoft products when you update Windows'.
For more information please visit https://aka.ms/wsl2kernel.

Kernel version: 5.10.16
</pre>

**Comment by jmooring** [comment] 2022-07-23 17:07
I am unable to reproduce the problem as described.

```
PS C:\WINDOWS\system32> wsl --status
Default Distribution: Ubuntu-20.04
Default Version: 2

Windows Subsystem for Linux was last updated on 7/23/2022
WSL automatic updates are on.

Kernel version: 5.10.102.1
```

Tested with:

```
{{ with resources.GetRemote "https://gohugo.io/img/hugo-logo.png" }}
  <img src="{{ .RelPermalink }}" width="{{ .Width }}"  height="{{ .Height }}" alt="Hugo logo">
{{ end }}
```

**Comment by istr** [comment] 2022-12-09 21:39
I would tend to close this issue. Connectivity problems in WSL2 are common in all sorts of scenarios because the network setup between the WSL2 VM and the Windows host is convoluted. Wild guess: some firewall rule in the Windows host allows traffic only for one of the two calls.

**Closed** 2022-12-09 21:43 UTC
Labels: Bug, CantReproduce
