### ISSUE TITLE
Generate pages from other data sources

### ISSUE THREAD

**Issue by JamesTheHacker** [gohugoio/hugo#5630] opened 2019-01-22 21:11 UTC
For some time users have requested a feature similar to Jekyll that allows you to load content from a data source and produces pages from that content. But as of yet I'm not aware on any developments with this.

I have a lot of data in different formats: cvs, json, database etc. I would like to use these data sources to construct pages. I really don't want to have to go elsewhere.

At the moment I'm writing Python scripts to generate markdown. I feel like this is a feature that's desperately needed. The use case for hugo has shifted beyond the blog imho.

This is such a needed feature for me that I wouldn't mind giving this feature a shot. Is there any work already done on this that I may have missed?

**Comment by moorereason** [comment] 2019-01-22 22:48
Duplicate of #5074

**Closed by moorereason** 2019-01-22 22:48 UTC
