### ISSUE TITLE
Pagination: page 1 redirect should be able to use relative links

### ISSUE THREAD

**Issue by ItalyPaleAle** [gohugoio/hugo#5557] opened 2018-12-23 06:24 UTC
I'm using the pagination module to list articles. On the `page/1.html` file, it correctly creates a redirect to my `index.html`. However, the redirect uses absolute permalinks even if my site is configured with `relativeURLs: true` and `canonifyURLs: false`.

This is the content of `page/1.html` generated (line breaks added for legibility):

````html
<!DOCTYPE html>
<html>

<head>
	<title>https://withblue.ink/</title>
	<link rel="canonical" href="https://withblue.ink/" />
	<meta name="robots" content="noindex">
	<meta charset="utf-8" />
	<meta http-equiv="refresh" content="0; url=https://withblue.ink/" />
</head>

</html>
````

What I'm expecting:

````html
<!DOCTYPE html>
<html>

<head>
	<title>https://withblue.ink/</title>
	<link rel="canonical" href="../index.html" />
	<meta name="robots" content="noindex">
	<meta charset="utf-8" />
	<meta http-equiv="refresh" content="0; url=../index.html" />
</head>

</html>
````

**Comment by felicianotech** [comment] 2018-12-26 20:05
That redirect is powered by Hugo Aliases. According to the docs, they are absolute URLs no matter what. I was going to see if I could make a change but then I learned that aliases support custom templates. You'll be able to make your own template that uses relative links instead.

https://gohugo.io/content-management/urls/#customize

**Comment by felicianotech** [comment] 2018-12-26 20:14
Though the way I understand this, this is basically a duplicate of https://github.com/gohugoio/hugo/issues/5314.

**Comment by ItalyPaleAle** [comment] 2019-01-01 18:14
I think it's a similar issue to #5314, meaning that could fix the issue as well (although requires more awareness). Is there a reason why the Aliases module can't support UglyURLs settings?

**Comment by jmooring** [comment] 2021-04-12 14:40
This is not a duplicate of #5314.
This issue is related to `relativeURLs = true`. It is _not_ related to `uglyURLs = true`.
There is a workaround: create a custom template (layous/alias.html) using [this](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/alias.html) as a starting point.

This could be resolved in the embedded template  if `.Site.relativeURLs` were exposed to templates, but I expect that would make the relative/canonify/webroot-in-subdir confusion worse.

**Comment by jmooring** [comment] 2023-05-13 23:14
<https://gohugo.io/content-management/urls/#relative-urls>

> **Relative URLs** 
> Do not enable this option unless you are creating a serverless site, navigable via the file system.
> 
> If enabled, Hugo performs a search and replace after it renders the page. It searches for site-relative URLs (those with a leading slash) associated with action, href, src, srcset, and url attributes. It then transforms the URL to be relative to the current page.

To get something like this in /public/posts/page/1.html

```
<meta http-equiv="refresh" content="0; url=../../posts.html">
```

1\) Override the [built-in alias template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/alias.html) to call .`RelPermalink` instead of `.Permalink`.

   ```html
   <!DOCTYPE html>dd
   <html{{ with site.LanguageCode | default site.Language.Lang }} lang="{{ . }}"{{ end }}>
     <head>
       <title>{{ .Permalink }}</title>
       <link rel="canonical" href="{{ .RelPermalink }}">
       <meta name="robots" content="noindex">
       <meta charset="utf-8">
       <meta http-equiv="refresh" content="0; url={{ .RelPermalink }}">
     </head>
   </html>
   ```

2\) Change your site configuration:

```toml
relativeURLs = true
uglyURLs = true
```

**Closed by jmooring** 2023-05-13 23:14 UTC
Labels: Enhancement
