### ISSUE TITLE
Taxonomy page with duplicate entries

### ISSUE THREAD

**Issue by earthboundkid** [gohugoio/hugo#12191] opened 2024-03-01 20:57 UTC
On my list of pages by topic, topics with commas or single quotes in the name are listed twice. One listing uses the appropriate _index.md file as metadata, and the other does not.

See #12174.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.7-312735366b20d64bd61bff8627f593749f86c964+extended darwin/arm64 BuildDate=2024-03-01T16:16:06Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes.

**Comment by earthboundkid** [comment] 2024-03-01 21:44
If you take this

```
git clone --single-branch -b hugo-github-issue-12193 https://github.com/jmooring/hugo-testing hugo-github-issue-12193
cd hugo-github-issue-12193
rm -rf public && hugo && cat public/authors/index.html
```

And change "John Smith" in books-1.md and books-2.md to "Smith, John", this will reproduce.

**Comment by jmooring** [comment] 2024-03-02 00:31
Author terms were also applied to the home page. So, 3 places. You changed only 2.

```text
git clone --single-branch -b hugo-github-issue-12191 https://github.com/jmooring/hugo-testing hugo-github-issue-12191
cd hugo-github-issue-12191
hugo server
```

Works fine.

**Comment by earthboundkid** [comment] 2024-03-02 04:02
@jmooring My site is still broken in 123. A failed attempt at making a minimal repro is not a reason to close the issue.

**Comment by jmooring** [comment] 2024-03-02 04:05
I'll re-open, but we need to be able to reproduce the problem. If we can't reproduce the problem, the issue will be closed. The ball is in your court.

**Comment by earthboundkid** [comment] 2024-03-02 11:51
The reproducer is to clone https://github.com/spotlightpa/poor-richard and build it with v122 and v123 and look at /investigations/. I can work on minimizing the reproduction next week.

**Comment by jmooring** [comment] 2024-03-02 23:05
I am not able to reproduce the problem with duplicate terms listed on the investigations (series) taxonomy page, but there are three terms that are not behaving as desired. As shown in the the content front matter of the news articles, the three terms are:

```text
series = ["One Vote, Two Pennsylvanias"]
series = ["Shapiro's Promises"]
series = ["Unproven, Unsafe"]
```

These are the only _terms_ (not titles) in the series taxonomy that contain punctuation. In the short term, the simplest solution is to remove the punctuation from the term assignments, as you have done for other terms that ultimately obtain their _punctuated_ title from a term page (e.g., `series = ["Short Days Big Benefits"]`).

Longer term this isn't great if you punctuate terms. Not only because you need to punctuate the file path, but also because Windows disallows certain characters (* " / \ < > : | ?). Which means I can use the term "a > b" on Linux/Mac, but that's not going to work on Windows.

**Comment by jmooring** [comment] 2024-03-02 23:15
Setting punctuation aside for a moment (we need to figure out what to do there), note that with v0.123.7 you can do this:

```text
{{ $series = (site.Taxonomies.series.Get .).Page }}
```

instead of this:

```text
{{ $series = (site.Taxonomies.series.Get (lower .)).Page }}
```

and never do this:

```text
{{ $series = (site.Taxonomies.series.Get (urlize .)).Page }}
```

See <https://github.com/gohugoio/hugo/pull/12180>.

**Comment by jmooring** [comment] 2024-03-03 00:37
Possible approaches:
1. Documentation: do not include any punctuation in your terms
2. Error checking: throw an error if there's punctuation in a term
3. Error checking: throw an error if the term includes characters disallowed in Windows file paths
4. Remove punctuation when creating the logical path

**Comment by earthboundkid** [comment] 2024-03-04 13:30
From my perspective, this is a regression because there was no problem using commas and hyphens before. If taxonomy terms must be "letters" does this mean users who don't use the Roman alphabet can't use taxonomies? ISTM it would be a shame if in spite of all the work in supporting localized sites, you couldn't use one of Hugo's major features with non-English languages or even "résumés" and "cafés".

**Comment by jmooring** [comment] 2024-03-04 13:43
@earthboundkid Your issue title is "Taxonomy page with duplicate entries." May I re-title this? Because I don't see any duplicate entries.

**Comment by jmooring** [comment] 2024-03-04 14:12
@earthboundkid Everything in the string "résumés" is a letter. So this works as it always has:

```text
---
tags: ['résumés']
---
```

```text
content/
├── tags/
│   └── résumés/
│       └── _index.md
└── _index.md
```

**Comment by earthboundkid** [comment] 2024-03-04 15:23
> The workaround fix is to rename the term folder in the series folder from the urlized version to the full version (eg. rename /series/shapiros-promises to "/series/Shapiro's Promises".

This workaround isn't compatible with Hugo 122 and creates duplicates in that version. :-/

**Comment by jmooring** [comment] 2024-03-04 15:39
Regarding v0.122.0 compatibility... we've had this discussion. This was an intentional breaking change. While you may not agree with it, the change stands.

Also, while you may not agree with it, I am closing this issue. Please create a separate issue if you wish to propose new functionality.

**Closed by jmooring** 2024-03-04 15:39 UTC
Labels: Bug, NeedsTriage, NeedsUserFeedback, v0.123.0
