### ISSUE TITLE
relref with a dot error out

### ISSUE THREAD

**Issue by afranke** [gohugoio/hugo#9918] opened 2022-05-23 11:43 UTC
I have the following (partial) structure:
```
content/
  blog/
    20160323-GNOME-3.20-release-party.md
    20170921-GNOME-3.26-release-party.md
```

`20170921-GNOME-3.26-release-party.md` has a `relref` to `20160323-GNOME-3.20-release-party`. When I run `hugo` in versions after 0.64.1, I get the following error:

```
REF_NOT_FOUND: Ref "20160323-GNOME-3.20-release-party": "/home/afranke/www/content/blog/20170921-GNOME-3.26-release-party.md:11:151": page not found
```

I have many `relref` in my blog, and four of them bring up this error. The common trait amongst them is they all have a `.` character in the slug, so I’d say this is the culprit.

0.64.1 is the latest version that works correctly in such cases. This issue was introduced in 0.65. I have confirmed it can be reproduced with all of 0.65.x, 0.66 and 0.99 (latest at the time of filing this).

This is a variant of #6952 but the fix for that one doesn’t work here.

**Comment by jmooring** [comment] 2022-05-23 17:50
If your target filename contains more than one period, include the extension.

```
{{< relref "20160323-GNOME-3.20-release-party.md" >}}
```

**Comment by afranke** [comment] 2022-05-24 13:40
Ok, that indeed works around the issue. Is the behaviour I reported expected though? I failed to find any documentation that would have warned me that I would run into the problem.

**Comment by jmooring** [comment] 2023-05-14 16:49
Duplicate of https://github.com/gohugoio/hugo/issues/10864.

**Closed by jmooring** 2023-05-14 16:49 UTC
Labels: Bug
