### ISSUE TITLE
Code generated in ``` block is not friendly to screenreaders

### ISSUE THREAD

**Issue by chrisreddington** [gohugoio/hugo#8758] opened 2021-07-15 08:45 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.1-5AFE0A57+extended windows/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes - Upgraded to hugo v0.85.0-724D5DB5 windows/amd64 BuildDate=2021-07-05T10:46:28Z VendorInfo=gohugoio

### Summary

I've been focusing on accessibility on my website, using the [accessibility insights for web](https://accessibilityinsights.io/en/) tools. I've fixed the majority in my local environment, but have found an issue when generating a codeblock. (e.g. using the ''' bash variable=content ''' syntax - of course, using backticks instead of quotes - GitHub parses the backticks, so i could not use those in this issue).

The issue is **Elements that have scrollable content must be accessible by keyboard**.  It looks like a [relatively simple fix](https://accessibilityinsights.io/info-examples/web/scrollable-region-focusable/) by adding tabindex="0" to the generated codeblock. However, I don't know the Hugo codebase well enough to know where to make the PR, so wanted to raise this as an issue.

Hope that this helps, but please let me know if there's any additional questions!

**Comment by bep** [comment] 2021-07-15 08:57
I assume this is with `codeFences: true`, which is what we can control in this repo anyway.

**Comment by jmooring** [comment] 2021-07-15 14:18
This looks like a duplicate of https://github.com/gohugoio/hugo/issues/7194, which has a related pull request https://github.com/gohugoio/hugo/pull/8568.

**Closed** 2021-07-15 14:46 UTC
Labels: Duplicate, Enhancement

**Comment by chrisreddington** [comment] 2021-07-15 14:47
Ah, yes it is - thanks for pointing that out @jmooring - I'll follow that one for updates.
