### ISSUE TITLE
Template debugging

### ISSUE THREAD

**Issue by pjebs** [gohugoio/hugo#5620] opened 2019-01-19 11:18 UTC
Currently recommend approach to template debugging is:

https://gohugo.io/templates/template-debugging/

```
{{ printf "%#v" $.Site }}
{{ printf "%#v" .Permalink }}
{{ printf "%#v" . }}
```

It would be far more convenient and more powerful if https://github.com/davecgh/go-spew was added as a template function so we can do something like:

```
{{ spew $.Site }}
```

**Comment by bep** [comment] 2019-01-19 15:35
How does your last example work/look like?

**Comment by pjebs** [comment] 2019-01-19 20:14
```
template.FuncMap{
    "spew": func(input interface{}) string {
      return fmt.Sprintf("%v", spew.Sdump(input))
    },
  }
```

**Comment by pjebs** [comment] 2019-01-19 20:17
You'll have to try it and experience it to witness and feel the full benefits.

**Comment by pjebs** [comment] 2019-02-07 11:43
It will look like this sort of thing:

```
(main.Foo) {
 unexportedField: (*main.Bar)(0xf84002e210)({
  flag: (main.Flag) flagTwo,
  data: (uintptr) <nil>
 }),
 ExportedField: (map[interface {}]interface {}) {
  (string) "one": (bool) true
 }
}
```

instead of:

```
hugolib.Pages{(*hugolib.Page)(0xc0003c7400), (hugolib.Page)(0xc0008b5400), (hugolib.Page)(0xc0008b4a00), (*hugolib.Page)(0xc0008b4f00)}
```

**It will recursively dereference pointers.**

**Comment by moorereason** [comment] 2019-03-07 17:56
Duplicate of #3957

**Closed by moorereason** 2019-03-07 17:56 UTC
Labels: Duplicate
