### ISSUE TITLE
hugo serve does not work on Fedora 32

### ISSUE THREAD

**Issue by Mebus** [gohugoio/hugo#7773] opened 2020-10-04 18:10 UTC
Hallo,

my hugo version is:

<pre>
$ hugo version
Hugo Static Site Generator v0.75.1 linux/amd64 BuildDate: 2020-09-19T15:38:20Z
</pre>

When I try to run `hugo serve` on Fedora 32, I get this error:

```
→ hugo serve
Start building sites … 
WARN 2020/10/04 20:08:39 Page.RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}

                   | EN  
-------------------+-----
  Pages            | 17  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     | 22  
  Processed images |  0  
  Aliases          |  5  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 54 ms
Watching for changes in /home/something/something/{archetypes,content,data,layouts,static,themes}
Error: too many open files
```

I already tried to change the `ulimit`:

```
→ ulimit
65536
```

But it didn't fix the problem. Can somebody please help?

Mebus

**Comment by santosh** [comment] 2020-10-08 17:39
Can you reproduce this error after a system reboot?

Maybe Hugo is not the problem.

**Comment by Mebus** [comment] 2020-10-10 14:19
Hey,

it works right after the restart, but then after some time I cannot start it again. How can I fix this?

Mebus

**Comment by santosh** [comment] 2020-10-10 15:16
First, you need to find the culprit who is using all the quota. 

After a quick search on _how to debug too many open files_, [I found](https://askubuntu.com/a/181408/49715) this command:

    lsof | awk '{ print $2; }' | uniq -c | sort -rn | head

The output of this command will print the number of open files in the first column and process ID in the second.

Run this command right after system startup, and again when you start seeing the problem. 

_Tip_: You can then use `ps -p <process id> -o command` to find the executable. <sub>[source](https://superuser.com/a/632987/103134)</sub>

**Comment by Mebus** [comment] 2020-10-10 15:22
> 
> ```
> lsof | awk '{ print $2; }' | uniq -c | sort -rn | head
> ```
> 
> The output of this command will print the number of open files in the first column and process ID in the second.

It turns out, that it's Firefox. When it runs, I cannot run hugo serve....

**Comment by santosh** [comment] 2020-10-11 16:13
Maybe you should report this to Firefox team.

**Comment by krobelus** [comment] 2020-10-20 14:25
We had the same problem, increasing these two limits fixed it:

```
# sysctl fs.inotify.max_user_instances
# sysctl fs.inotify.max_user_watches
```

**Comment by RichieEscarez** [comment] 2021-01-11 23:32
In Knative we have been using these commands to get past that error on Mac (which ive opened a PR for here https://github.com/google/docsy/pull/410):

https://github.com/knative/website/blob/master/DEVELOPMENT.md#file-descriptors-in-server-mode

```
sudo launchctl limit maxfiles 65535 200000
ulimit -n 65535
sudo sysctl -w kern.maxfiles=100000
sudo sysctl -w kern.maxfilesperproc=65535
```

**Comment by moorereason** [comment] 2021-01-12 00:06
Closing since this is not something Hugo can fix.

**Closed by moorereason** 2021-01-12 00:06 UTC
