### ISSUE TITLE
Build extended version for ARM

### ISSUE THREAD

**Issue by mukhtharcm** [gohugoio/hugo#6991] opened 2020-03-01 08:00 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
latest source
</pre>

### Does this issue reproduce with the latest release?
yes
## can't cross compile for arm in **solus**..
running 
```
GOOS=linux GOARCH=arm build --tags extended 
```
gives an error.
 ```
build github.com/bep/golibsass/internal/libsass: cannot load github.com/bep/golibsass/internal/libsass: no Go source files
```
## and in **ubuntu**
```
../../go/pkg/mod/github.com/bep/golibsass@v0.5.0/libsass/transpiler.go:15:2: build constraints exclude all Go files in /home/mukhtharcm/go/pkg/mod/github.com/bep/golibsass@v0.5.0/internal/libsass
```
is there any way to fix this?  
Or Is there any place I can get hugo extended for **arm**?

**Comment by bep** [comment] 2020-03-01 09:34
>Or Is there any place I can get hugo extended for arm?

Not that I know of.

**Comment by mukhtharcm** [comment] 2020-03-01 10:08
Then how can I rectify this problem?
Is this a bug that I am not able to build for **ARM**?

**Comment by bep** [comment] 2020-03-01 10:09
>Then how can I rectify this problem?

You need to ask questions on the forum.

**Comment by anthonyfok** [comment] 2020-03-01 12:13
@mukhtharcm Cross compiling is more complicated especially with the C/C++ libSass

How about natively built ARM version for Ubuntu?  :-D

See https://launchpad.net/ubuntu/+source/hugo/ for the latest build there, right now at 0.63.2:

* armhf build: https://launchpad.net/ubuntu/+source/hugo/0.63.2-1/+build/18774760
* arm64 build: https://launchpad.net/ubuntu/+source/hugo/0.59.1-1.1/+build/18611564

**Comment by anthonyfok** [comment] 2020-03-01 12:17
@mukhtharcm Cross compiling is more complicated especially with the C/C++ libSass

How about natively built ARM version for Ubuntu? :-D

See https://launchpad.net/ubuntu/+source/hugo/ for the latest build there, right now at 0.63.2 (focal, i.e. the upcoming Ubuntu 20.04):

* armhf build: https://launchpad.net/ubuntu/+source/hugo/0.63.2-1/+build/18774760
* arm64 build: https://launchpad.net/ubuntu/+source/hugo/0.63.2-1/+build/18774759

Also, ARM (armel, armhf, arm64) builds in Debian, now at the latest hugo 0.65.3:

* https://packages.debian.org/sid/hugo

**Comment by mukhtharcm** [comment] 2020-03-01 12:27
Sorry, I am running ubuntu  bionic on linux deploy. Thanks anyway for pointing me to this.  
I am probably gonna install debian instead of Debian.

**Comment by mukhtharcm** [comment] 2020-03-03 10:34
@anthonyfok I installed it in debian sid and works great! :). Thank you!  
@bep It is available in debian sid built by @anthonyfok .

**Comment by mukhtharcm** [comment] 2020-03-04 18:18
@anthonyfok as you have made packages for debian, I assume that you should have builded the executable file. If you dont mind, it'll be very cool if you shared it anywhere, so we can use it on other os-es too.

**Comment by anthonyfok** [comment] 2020-03-08 02:59
> @anthonyfok as you have made packages for debian, I assume that you should have builded the executable file. If you dont mind, it'll be very cool if you shared it anywhere, so we can use it on other os-es too.

Everything that is packaged for Debian is free (both zero cost and freedom) for anyone to download,  so it has been already "shared anywhere"...

... and as a matter of fact, all things packaged for Debian are used directly or indirectly by Debian derivatives including Ubuntu.  Ubuntu normally picks up the latest versions from Debian too, though it has its own autopkgtest which ensures that any potential regressions are resolved with other packages before the latest version is pulled in.

Others are of course free to take the /usr/bin/hugo binary file from the .deb packages and use it wherever they like, but it may not work though because Debian's hugo is not packaged as a static binary:

```
$ ldd /usr/bin/hugo 
	linux-vdso.so.1 (0x00007ffeca7c6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0782d35000)
	libsass.so.1 => /usr/lib/x86_64-linux-gnu/libsass.so.1 (0x00007f0782a81000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f07828c1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0782d96000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f07828bc000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f07826ef000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f07825aa000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f078258e000)
```

so make sure you have the correct versions of the necessary C/C++ libraries.

If you want to run a pre-built Hugo "extended" version on just about any other Linux OS, Snap might be a good option, and indeed it is available on `armhf` architecture.  That would definitely work well with your Ubuntu bionic (18.04LTS) environment.  See instructions here:

* https://gohugo.io/getting-started/installing#snap-package
* https://snapcraft.io/hugo

And, for your information, Hugo Snaps are automatically built here:
* https://bugs.launchpad.net/~gohugoio/+snap/hugo-extended-dev

**Closed** 2020-03-08 16:34 UTC
Labels: Wish

**Comment by rootsongjc** [comment] 2020-07-05 03:58
On raspberry pi 4, you can install Hugo extended directly.

```bash
sudo apt-get install hugo
```

The hugo version is `Hugo Static Site Generator v0.54.0/extended linux/arm BuildDate: 2019-06-04T19:16:36Z`

**Comment by apoorvmote** [comment] 2021-01-18 07:58
I wrote blog post on how to install Hugo on ARM

https://apoorv.blog/posts/install-update-hugo-extended-for-arm.html
