### ISSUE TITLE
Two way references

### ISSUE THREAD

**Issue by lucasew** [gohugoio/hugo#8600] opened 2021-06-01 13:42 UTC
Hugo has a pretty convenient template engine, shortcodes have pretty interesting handling about markdown extensibility so Hugo is a nice candidate to preview and publish digital gardens, but it lacks a two-way linking reference.

The proposition is basically a method on Page data structure that exposes a slice of relative references to the current page.

This can then be used in a template to generate quick jumping links and also a JSON manifest to generate things like graph views. Hugo just generates that metadata of the page. The rest can be handled by a template.

An extra idea about this is that linking can be labeled like `/some/page#label` then the label is stripped out the ref then on that slice it returns a struct with the relative href from the baseurl to the referenced page and the label as something like the state.

I was looking to do this and send a PR. No idea where to start xD. Is there already a shared index on the server mode? Should I do it from scratch? How can I listen to file modifications to efficiently update the index? Does Hugo already have an index like to the links a file is referencing?

**Comment by jmooring** [comment] 2021-06-01 13:59
Duplicate of https://github.com/gohugoio/hugo/issues/8077

**Closed by jmooring** 2021-06-01 13:59 UTC
Labels: Duplicate, Proposal
