### ISSUE TITLE
Use PublishDate rather than Date in rss's pubDate

### ISSUE THREAD

**Issue by bendem** [gohugoio/hugo#8357] opened 2021-03-23 14:17 UTC
Currently, the default embedded template for the rss feed uses the date the page was created at instead of the date of publication. Since the `.PublishDate` falls back to `.Date` when it is not defined, would it make sense to use that variable instead? People who define that variable probably expect it to be used, and there won't be any changes for those that do not use it.

https://github.com/gohugoio/hugo/blob/97934779ededfcfef0ee2621e7dacad0127ef4b5/tpl/tplimpl/embedded/templates/_default/rss.xml#L32

**Comment by jmooring** [comment] 2021-03-26 17:26
Duplicate of https://github.com/gohugoio/hugo/issues/3918.

**Closed by jmooring** 2021-03-26 17:26 UTC
Labels: Duplicate, Proposal
