### ISSUE TITLE
v0.112.3 build times for a project are ~30x slower than v0.111.3

### ISSUE THREAD

**Issue by davidfmiller** [gohugoio/hugo#11038] opened 2023-05-28 17:43 UTC
I recently upgraded Hugo to `v1.112.3` and build times for my site are now >30 seconds.

`v1.111.3` builds the same site in ~1 second (on slightly different hardware, but not so different to cause a 30× decrease in performance).

Info below:

```
⚡ hugo version
hugo v0.112.3+extended darwin/amd64 BuildDate=unknown

⚡ hugo 
Start building sites … 
hugo v0.112.3+extended darwin/amd64 BuildDate=unknown

                   | EN-CA | EN-UK | EN-US | FR-CA  
-------------------+-------+-------+-------+--------
  Pages            |   386 |   386 |   389 |   386  
  Paginator pages  |     0 |     0 |     0 |     0  
  Non-page files   |     0 |     0 |     0 |     0  
  Static files     |    35 |    35 |    35 |    35  
  Processed images |     0 |     0 |     0 |     0  
  Aliases          |    11 |    10 |    10 |    10  
  Sitemaps         |     2 |     1 |     1 |     1  
  Cleaned          |     0 |     0 |     0 |     0  

Total in 36577 ms
```

---

```
⚡ hugo version
hugo v0.111.3+extended darwin/arm64 BuildDate=unknown

⚡ hugo 
Start building sites … 
hugo v0.111.3+extended darwin/arm64 BuildDate=unknown

                   | EN-CA | EN-UK | EN-US | FR-CA  
-------------------+-------+-------+-------+--------
  Pages            |   386 |   386 |   389 |   386  
  Paginator pages  |     0 |     0 |     0 |     0  
  Non-page files   |     0 |     0 |     0 |     0  
  Static files     |    38 |    38 |    38 |    38  
  Processed images |     0 |     0 |     0 |     0  
  Aliases          |    11 |    10 |    10 |    10  
  Sitemaps         |     2 |     1 |     1 |     1  
  Cleaned          |     0 |     0 |     0 |     0  

Total in 1130 ms
```

**Comment by bep** [comment] 2023-05-28 18:03
Thanks for the report. Unfortunately I'm not able to reproduce this (the benchmarks we have actually show slightly improved performance) with any of the sites I have tested with.

If you can somehow share the source with me (my email address is in the GitHub profile), I'm sure we can fix it.

**Comment by bep** [comment] 2023-05-30 18:46
@davidfmiller  A unrelated question, where did you get the binaries?

```
⚡ hugo version
hugo v0.112.3+extended darwin/amd64 BuildDate=unknown

⚡ hugo 
Start building sites … 
hugo v0.112.3+extended darwin/amd64 BuildDate=unknown

```

The output above does not match anything I know about and we should fix that.

**Comment by kentf** [comment] 2023-05-30 22:35
Just a thought... Are both Macs with Apple Silicon?

I see one architecture is `amd64`, while the other is `arm64` in the above table, where `amd64` version is the slow one. I haven't done any tests myself, but it would explain it if you're emulating `amd64` on `arm64` hardware.

**Comment by davidfmiller** [comment] 2023-05-30 22:42
Both Macs have Apple Silicon. The Mac w/ `v0.112.3` (the one with slow build times) _is_ running Terminal under Rosetta... but the build time for my project is/was normal using `v0.111.3` on both computers in both environments. 

FWIW `v0.112.5` on this machine is seeing the same (slow) build times as `v0.112.3` was. 

Could be something about the version of Hugo distributed via `brew`, er...?

**Comment by kentf** [comment] 2023-05-30 22:53
I _think_ brew may be confused by running under Rosetta, and downloading the `amd64` version, but don't quote me on that. I'm just a newish Apple Silicon user.

However, I've been a dev for many years and I would try to actually make sure you're comparing apples and apples by using the same architecture on both computers, as in, both should report `darwin/arm64`.

**Comment by davidfmiller** [comment] 2023-05-30 22:55
S'alright, computers confuse me, too... as well.

For my computer that is now experiencing slow build times w/ hugo, nothing has changed in its environment/setup _other_ then upgrading to `v0.112.x` from `v0.111.3`.

If I'm the only person experiencing this problem then the issue can be closed invalid, just figured I'd pipe up about it.

**Comment by jmooring** [comment] 2023-06-05 18:51
@davidfmiller Have you investigated the details described by @kentf as the possible cause? I'd like to close this because (a) we cannot reproduce the behavior, and (b) there have been no additional reports of performance degradation.

**Closed** 2023-06-05 19:10 UTC
Labels: Bug, CantReproduce, NeedsUserFeedback
