### ISSUE TITLE
Code blocks with syntax highlighting nested in a list break list layout.

### ISSUE THREAD

**Issue by sanderson** [gohugoio/hugo#6091] opened 2019-07-17 18:29 UTC
Somewhere between 0.55.1 and 0.55.6, using syntax highlighting on nested code blocks breaks the layout for the order and unordered lists. It appears as though nested highlighted code blocks prevent the closing `</ol>` and `</ul>` tags.

Code blocks without syntax highlight work as expected, so I'm not sure if this is an issue with Blackfriday or Chroma.

Here are some examples:

The following markdown:
~~~

1. This is a line item with a nested codeblock with the syntax specified.

    ```sh
    This code block renders correctly but breaks the next li.
    For some reason, the fenced code blocks prevent the closing </ol> and </ul> tags.
    ```

2. This `<li>` is nested under the first `<li>` when it shouldn't be.

    ```
    But this nested code block renders as it should, but nested under the nested `<li>`.
    ```

3. And this next line item is also nested under the first `<li>`.
~~~

Renders as:
![image](https://user-images.githubusercontent.com/181484/61400115-c970a000-a88c-11e9-8d71-762a0696f934.png)

But if I remove the syntax specification from the code block, it works fine:

~~~

1. This is a line item with a nested codeblock **without** the syntax specified.

    ```
    This code block and the following line items render correctly.
    ```

2. This `<li>` is works as it should.

    ```
    But this nested code block renders as it should, but nested under the nested `<li>`.
    ```

3. As does this one.
~~~

Renders as:
![image](https://user-images.githubusercontent.com/181484/61400302-371ccc00-a88d-11e9-8c0f-b750166c0817.png)

BUT, if there are two nested syntax highlighted code blocks in a list, the 2nd is rendered outside of what should be its parent list and the rest of the list renders as it should:

~~~
1. This is a line item with a nested codeblock with the syntax specified.

    ```sh
    This code block renders correctly but breaks the next li.
    For some reason, the fenced code blocks prevent the closing </ol> and </ul> tags.
    ```

2. This `<li>` gets nested.

    ```sh
    But this code block DOES NOT get nested under the line item or the ordered list.
    It is outside of the above `<ol>`.
    ```

3. This `<li>` renders correctly.
~~~

Renders as:
![image](https://user-images.githubusercontent.com/181484/61400625-e78ad000-a88d-11e9-8fde-3ee627daa185.png)

**Comment by moorereason** [comment] 2019-07-17 20:28
Duplicate of #6040

**Closed by moorereason** 2019-07-17 20:28 UTC
Labels: Duplicate
