### ISSUE TITLE
Heading Render Hook output mismatch

### ISSUE THREAD

**Issue by Erbenos** [gohugoio/hugo#8094] opened 2020-12-25 19:16 UTC
### What version of Hugo are you using (`hugo version`)?
Hugo Static Site Generator v0.79.0/extended windows/amd64 BuildDate: unknown

### Does this issue reproduce with the latest release?
Version above is currently latest.

### Issue
Perhaps I am misusing markdown heading render hook, but I am getting quite weird behavior here:

Markdown:
```
#### lorem ipsum dolor sit *amet* **[xd](https://google.com)**
```

Heading render hook template:
```
<h{{ .Level }} id="{{ .Anchor | safeURL }}">{{ .Text | safeHTML }}</h{{ .Level }}> 
```

Outputs:
```
lorem ipsum dolor sit <em>amet</em> <strong><h4 id="lorem-ipsum-dolor-sit-amet-xdhttpsgooglecom"><a href="https://google.com" class="special-link"><span data-desc="xd">xd</span></a></strong></h4>
```

As you can see, the output doesn't match to what is expected:

```
<h4 id="lorem-ipsum-dolor-sit-amet-xdhttpsgooglecom">lorem ipsum dolor sit <em>amet</em> <strong><a href="https://google.com" class="special-link"><span data-desc="xd">xd</span></a></strong></h4>
```

The HTML structure is off, as the entire segment should be wrapped in ```<h4>```

**Comment by jmooring** [comment] 2021-03-09 17:52
I am unable to reproduce this problem when building Hugo from source (https://github.com/gohugoio/hugo/commit/18074d0c2375cc4bf4d7933dd4206cb878a23d1c).

markdown

```md
#### lorem ipsum dolor sit *amet* **[xd](https://google.com)**
```

layouts/_default/_markup/render-heading.html

```
<h{{ .Level }} id="{{ .Anchor | safeURL }}">{{ .Text | safeHTML }}</h{{ .Level }}>
```

results

```html
<h4 id="lorem-ipsum-dolor-sit-amet-xdhttpsgooglecom">lorem ipsum dolor sit <em>amet</em> <strong><a href="https://google.com">xd</a></strong></h4>
```

Please close this issue.

**Closed** 2021-03-09 19:09 UTC

**Comment by Erbenos** [comment] 2021-03-09 19:12
Thanks for looking into it @bep and @jmooring
