### ISSUE TITLE
Rendering hooks and Mardownify

### ISSUE THREAD

**Issue by ssbanerje** [gohugoio/hugo#7461] opened 2020-07-06 05:38 UTC
### What version of Hugo are you using?
```
$ hugo version
Hugo Static Site Generator v0.73.0/extended darwin/amd64 BuildDate: unknown
```

### Issue
Calling `markdownify` in HTML templates does not use the rendering hooks described [here](https://gohugo.io/getting-started/configuration-markup/#render-hook-templates).

Is this the expected behavior? Documentation does not specify this.

### Does this issue reproduce with the latest release?
Yes

**Comment by pamubay** [comment] 2020-07-06 06:17
You need to use [`.RenderString`](https://gohugo.io/functions/renderstring/)

From documentation:
> Note that this method is more powerful than the similar markdownify function as it also supports Render Hooks and it has options to render other markup formats.

**Comment by ssbanerje** [comment] 2020-07-06 07:38
That seems to work! Thanks!

Maybe there should be a pointer in the render hooks documentation pointing back to this function. Otherwise, this can be quite hard to find.

**Comment by jmooring** [comment] 2021-03-09 17:57
Duplicate of #6650. Please close this issue.

**Closed** 2021-03-09 20:00 UTC
