### ISSUE TITLE
sitemap.xml from layouts is getting mangled

### ISSUE THREAD

**Issue by limbicrevision** [gohugoio/hugo#8276] opened 2021-02-22 23:21 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.81.0-59D15C97+extended linux/amd64 BuildDate=2021-02-19T17:07:12Z VendorInfo=gohugoio

</pre>

### Does this issue reproduce with the latest release?
yes

I am using hugo-elate-theme but I don't think this is the issue.
Firstly, I cannot get the config disableKinds list to prevent tags and/or categories in the automatic sitemap generation so I am using a generated file in the /layouts/sitemap.xml (another problem):
<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">

<url>
  <loc>https://www.limbicrevision.com/</loc>
  <lastmod>2021-02-20T14:19:39+00:00</lastmod>
  <priority>1.00</priority>
</url>
<url>
  <loc>https://www.limbicrevision.com/index.html</loc>
  <lastmod>2021-02-20T14:19:39+00:00</lastmod>
  <priority>0.80</priority>
</url>

</urlset>

Unfortunately when hugo "creates" sitemap in the root directory the first less-than sign is translated to &lt;  everything else is as should be.  I've checked the file in emacs and it is utf-8.

Can you help with this?

**Comment by jmooring** [comment] 2021-03-11 18:45
I think this is a duplicate of https://github.com/gohugoio/hugo/issues/7400. See [this comment](https://github.com/gohugoio/hugo/issues/7400#issuecomment-645523800) for a fix.

**Closed** 2021-03-28 13:52 UTC
Labels: Duplicate
