### ISSUE TITLE
AppArmor configuration for snap install

### ISSUE THREAD

**Issue by sheljohn** [gohugoio/hugo#3837] opened 2017-08-26 01:54 UTC
I am on Ubuntu 16.04 running Hugo installed with `snap`.
I have reported an issue [on the forum](https://discourse.gohugo.io/t/where-does-hugo-put-sites-with-absolute-path/8107), and I think I have narrowed it down to the AppArmor configuration of the snap application, which might be missing certain rules to allow the user to create sites everywhere.

More about the configuration of my system:
```
$$ cat /proc/version
Linux version 4.10.0-32-generic (buildd@lcy01-01) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017

$$ hugo version
Hugo Static Site Generator v0.26 linux/amd64 BuildDate: 2017-08-07T08:54:34+01:00

$$ which hugo
/snap/bin/hugo
```

The AppArmor configuration is in file `/var/lib/snapd/apparmor/profiles/snap.hugo.hugo` and I have pasted it [here](https://pastebin.com/KchkwNRL). I think the relevant lines in that file are 392-404.

As I reported in the forum, the app does not seem to allow me to create new sites anywhere else than in subfolders of the home directory, but I would like to create sites on a different partition (mounted from the fstab).

**Comment by sheljohn** [comment] 2017-09-13 15:06
Any news on this side?

**Comment by dacodekid** [comment] 2017-09-26 15:08
@anthonyfok I got hit by this as well. Could you plz give us an update on this?

**Comment by anthonyfok** [comment] 2017-09-26 17:47
Please read https://gohugo.io/getting-started/installing/#snap-package and #3143.

For better or for worse, that is Snap's confinement security model by design.
There are ways around it using the so-called "classical confinement" model, but I'm not sure if we want to go there.

**Comment by itc-ger** [comment] 2017-11-01 15:19
I'm wondering why Hugo's Snap doesn't implement Snap's **removable-media** interface as a slot.
I can't see any severe security related concerns in granting access to this interface.

**Comment by anthonyfok** [comment] 2018-01-30 21:31
Hi @itc-ger,

Sorry for my late reply.  Had been away from GitHub for a while, but now finding time to come back.

> I'm wondering why Hugo's Snap doesn't implement Snap's **removable-media** interface as a slot.
I can't see any severe security related concerns in granting access to this interface.

Because I didn't know about it?  :flushed:

Thank you for your suggestion!  It should be trivial to add this.  :-)

**Comment by anthonyfok** [comment] 2018-01-31 04:37
Note to self:

With the new comments, almost the same but not quite duplicate of #3143.

Check to see if adding the `removable-media` interface as a slot solves @Talis's problem without resorting to the use of the snap `--classic` flag.

**Closed** 2018-01-31 09:02 UTC
