### ISSUE TITLE
hugo --minify breaks HTML element extraction

### ISSUE THREAD

**Issue by Traumflug** [gohugoio/hugo#7567] opened 2020-08-15 22:48 UTC
```
$ ../hugo/hugo version
Hugo Static Site Generator v0.74.3/extended linux/amd64 BuildDate: unknown
```
... where 'unknown' should be 'today'.

Let code speak:
```
$ ../hugo/hugo
[...]
$ wc -l hugo_stats.json 
196 hugo_stats.json
$ ../hugo/hugo --minify
[...]
$ wc -l hugo_stats.json 
176 hugo_stats.json
```
Which means, minification looses 20 HTML elements for unknown reasons. Which breaks my site :-)

#### Further diagnosis:
This shorter list contains this line:
```
{
  "htmlElements": {
    "tags": [
      [...]
      "img",
      "imgdefer.length;i++){if(imgdefer[i].hasattribute('data-src')){imgdefer[i].setattribute('src',imgdefer[i].getattribute('data-src'));imgdefer[i].removeattribute('data-src');}}}\u003c/script",
      "li",
[...]
```
This long line is certainly not a HTML tag, but similar to this chunk in one of the partials:
```
<script type="text/javascript">
  window.onload = function () {
    var imgDefer = document.getElementsByTagName('img');

    for (var i = 0; i < imgDefer.length; i++) {
      if (imgDefer[i].hasAttribute('data-src')) {
        imgDefer[i].setAttribute('src', imgDefer[i].getAttribute('data-src'));
        imgDefer[i].removeAttribute('data-src');
      }
    }
  }
</script>
```

**Comment by Traumflug** [comment] 2020-08-15 22:51
It looks like HTML parsing trips over the JavaScript `<`. It also looks like HTML extraction happens after minification, which might be not the best idea for consistent results.

**Comment by Traumflug** [comment] 2020-12-19 15:36
This still happens with latest master, `Hugo 0.80.0-DEV`.

**Comment by davidsneighbour** [comment] 2020-12-19 16:25
Some more triage ;)

- What is the diff of both runs on the json file? Meaning, not what is inside the minified one, but what actual differences are there?
- Are you aware, that there is a `<` in ` for (var i = 0; i < imgDefer.length; i++) {` - I think that might be the issue here. 

As far as I remember you need to somehow printf the javascript code in connection with a [safeJS](https://gohugo.io/functions/safejs/#readout). 

If you can, move the javascript into a static file outside of the layout file. 

I think this is a limitation of what is going on, not a bug per se. Maybe opening a thread over at discourse.gohugo.io might bring a speedy-er solution.

**Comment by Traumflug** [comment] 2020-12-19 20:38
Well, the simple solution is to not minify, distinction is less than a kilobyte for a small site. Workarounds around this bug are of no help, because the next user will run into it again. That's not how a reliable software should deal with issues.

That said, here's a diff with Hugo 0.79.0, IIRC it used to be larger with earlier versions:
```diff
$ diff -u hugo_stats.json hugo_stats.json.minify
--- hugo_stats.json	2020-12-19 21:30:30.559248875 +0100
+++ hugo_stats.json.minify	2020-12-19 21:30:20.487292074 +0100
@@ -1,7 +1,6 @@
 {
   "htmlElements": {
     "tags": [
-      "!--",
       "!doctype",
       "a",
       "article",
@@ -23,7 +22,7 @@
       "html",
       "i",
       "img",
-      "img\n",
+      "imgdefer.length;i++){if(imgdefer[i].hasattribute('data-src')){imgdefer[i].setattribute('src',imgdefer[i].getattribute('data-src'));imgdefer[i].removeattribute('data-src');}}}\u003c/script",
       "li",
       "link",
       "meta",
```

**Comment by davidsneighbour** [comment] 2020-12-20 04:42
Isn't it weird, that there is an "img" and an "img\n" in that list on un-minified pages? Could it be that some weird line ending is introduced in one of the partials and while browsers display the image nicely the HTML(XML) is not valid? Can you provide a unminified page sample and test it in a validator? https://validator.w3.org/

Hugo is only running the command. The problem is upstream in how the tags get extracted.

**Comment by Traumflug** [comment] 2020-12-20 10:24
Well, in HTML, a newline is perfectly valid whitespace. I often spread tags across multiple lines to make them readable.

> Hugo is only running the command.

Which command or project would this be?

**Comment by davidsneighbour** [comment] 2020-12-20 11:13
> Which command or project would this be?

Let's ask @bep... internals are not something I can compute :+1: 

And regarding your answer to the two img tags... i would expect the parser to know, that a newline is a whitespace. so it should know that img and img-newline is the same. that is what I am saying. for the parser to acknowledge this as two separate instances of something might be an error in the parser, or a known inability depending on how the files get parsed. If some windowless browser is involved, it might fix things somehow.

I am not saying the newline is an error in your document, I am saying it might be an indicator that the parser somehow mis-qualifies one specific img tag because there is some weird new lining going on that irritates it.

**Comment by davidsneighbour** [comment] 2020-12-20 11:18
There is no note in the code about how this get's extracted when I search for write stats

https://github.com/gohugoio/hugo/search?q=writeStats

**Comment by philoserf** [comment] 2021-03-27 10:30
I believe #8180 fixed this.

**Comment by merchantsedition** [comment] 2021-04-05 14:46
With Hugo v0.81.0 (and  v0.82.0), which includes #8180, it gets not perfect, but closer:
```diff
$ diff -u hugo_stats.json hugo_stats.json.minify
--- hugo_stats.json	2021-04-05 16:23:07.790034356 +0200
+++ hugo_stats.json.minify	2021-04-05 16:23:17.842074077 +0200
@@ -1,10 +1,10 @@
 {
   "htmlElements": {
     "tags": [
-      "!--",
       "!doctype",
       "a",
       "article",
+      "b.length;a++)b[a].hasattribute('data-src')\u0026\u0026(b[a].setattribute('src',b[a].getattribute('data-src')),b[a].removeattribute('data-src'))}\u003c/script",
       "body",
       "button",
       "code",
```

**Comment by Traumflug** [comment] 2021-04-06 13:16
D'oh. I just see I was logged in with my other account. @merchantsedition, that's me :-)

**Comment by davidsneighbour** [comment] 2021-04-06 13:30
The truth comes to light ;D

**Comment by bep** [comment] 2021-04-06 15:31
>It also looks like HTML extraction happens after minification, which might be not the best idea for consistent results.

We just listen to the stream written to disk and look for HTML elements, which is extremely fast compared to doing a full scan.

 With the above, there will be false positives (e.g. the script example above, which we should skip), but I don't any example of a false negative in any of the examples above, which would be more useful.

**Comment by bep** [comment] 2021-04-06 17:10
I have added a PR patch that fixes the obvious part of this bug, but without any "failing input" example, this is not possible to verify.

**Comment by merchantsedition** [comment] 2021-04-07 14:30
Thanks for the work. I just gave it a go and find no distinction in the output.

To find out what's going on, I added some printf-debugging (I'm a PHP guy, so this is normal):
```diff
diff --git a/publisher/htmlElementsCollector.go b/publisher/htmlElementsCollector.go
index d9479aaf..f2c35190 100644
--- a/publisher/htmlElementsCollector.go
+++ b/publisher/htmlElementsCollector.go
@@ -19,6 +19,7 @@ import (
 	"sort"
 	"strings"
 	"sync"
+	"fmt"
 
 	"github.com/gohugoio/hugo/helpers"
 	"golang.org/x/net/html"
@@ -118,7 +119,9 @@ func (w *cssClassCollectorWriter) Write(p []byte) (n int, err error) {
 					continue
 				}
 
+				fmt.Print("\n");
 				s := w.buff.String()
+				fmt.Print(s, "\n");
 
 				w.buff.Reset()
 
@@ -129,6 +132,7 @@ func (w *cssClassCollectorWriter) Write(p []byte) (n int, err error) {
 				key := s
 
 				s, tagName := w.insertStandinHTMLElement(s)
+				fmt.Print("tagName: ", tagName, "\n");
 				el := parseHTMLElement(s)
 				el.Tag = tagName
 				if w.isPreFormatted(tagName) {
```
This gives the following output without `--minify`, note the empty _tagName_:
```
$ ../hugo/hugo | grep -C8 'has[aA]ttribute'

</i

</a

</div

< imgDefer.length; i++) {
      if (imgDefer[i].hasAttribute('data-src')) {
        imgDefer[i].setAttribute('src', imgDefer[i].getAttribute('data-src'));
        imgDefer[i].removeAttribute('data-src');
      }
    }
  }
</script
tagName: 
```
... and with `--minify`:
```
$ ../hugo/hugo --minify | grep -C4 'has[aA]ttribute'
</a

</div

<b.length;a++)b[a].hasAttribute('data-src')&&(b[a].setAttribute('src',b[a].getAttribute('data-src')),b[a].removeAttribute('data-src'))}</script
tagName: b.length;a++)b[a].hasattribute('data-src')&&(b[a].setattribute('src',b[a].getattribute('data-src')),b[a].removeattribute('data-src'))}</script

<script type=text/javascript src=../js/jquery.min.js
tagName: script
```
To me it looks like the mismatch happens earlier already, this entire JS snippet is recognized as tag. Only with minification, because minification removes the space between `<` and the following word. Accordingly, the new `isPreFormatted()` doesn't recognize the script snippet as such.

**Comment by dirkolbrich** [comment] 2021-04-14 09:59
There definitely seems to be some error in the minify functionality. If I put some basic ftm.Println() into `htmlElementsCollector.go` and the corresponding test, minify send some garbled stream to the collector. But all test pass.

in `publish/htmlElementsCollector.go`:
```go
func (w *cssClassCollectorWriter) Write(p []byte) (n int, err error) {
	fmt.Println(string(p)) // <- add this test fmt.Println()
```

in `publish/htmlElementsCollector_test.go`:
```go
for _, minify := range []bool{false, true} {
			c.Run(fmt.Sprintf("%s--minify-%t", test.name, minify), func(c *qt.C) {
				w := newHTMLElementsCollectorWriter(newHTMLElementsCollector())
				fmt.Println(test.html) // <- add this test fmt.Println()
				if minify {
					if skipMinifyTest[test.name] {
						c.Skip("skip minify test")
					}
					v := viper.New()
					m, _ := minifiers.New(media.DefaultTypes, output.DefaultFormats, v)
					m.Minify(media.HTMLType, w, strings.NewReader(test.html))
				} else {
					fmt.Fprint(w, test.html)
				}
				got := w.collector.getHTMLElements()
				c.Assert(got, qt.DeepEquals, test.expect)
			})
		}
```

This gives:

```bash
➜  publisher git:(master) go test -v -run TestClassCollector
=== RUN   TestClassCollector
=== RUN   TestClassCollector/basic--minify-false
<body class="b a"></body>
<body class="b a"></body>
=== RUN   TestClassCollector/basic--minify-true
<body class="b a"></body>
<body
 
class
=
"b a"
>
</body>

=== RUN   TestClassCollector/duplicates--minify-false
<div class="b a b"></div>
<div class="b a b"></div>
=== RUN   TestClassCollector/duplicates--minify-true
<div class="b a b"></div>
<div
 
class
=
"b a b"
>
</div>

...
// lots of other test prints left out for clarity
...

=== RUN   TestClassCollector/Textare_tags_content_should_be_skipped--minify-false
<textarea class="textareaclass"><span>foo</span><span>bar</span></textarea><div class="foo"></div>
<textarea class="textareaclass"><span>foo</span><span>bar</span></textarea><div class="foo"></div>
=== RUN   TestClassCollector/Textare_tags_content_should_be_skipped--minify-true
<textarea class="textareaclass"><span>foo</span><span>bar</span></textarea><div class="foo"></div>
<textarea
 
class
=
textareaclass
>
<span>foo</span><span>bar</span>
</textarea>
<div
 
class
=
foo
>
</div>

--- PASS: TestClassCollector (0.01s)
    --- PASS: TestClassCollector/basic--minify-false (0.00s)
    --- PASS: TestClassCollector/basic--minify-true (0.00s)
    --- PASS: TestClassCollector/duplicates--minify-false (0.00s)
    --- PASS: TestClassCollector/duplicates--minify-true (0.00s)
    --- PASS: TestClassCollector/single_quote--minify-false (0.00s)
    --- PASS: TestClassCollector/single_quote--minify-true (0.00s)
    --- PASS: TestClassCollector/no_quote--minify-false (0.00s)
    --- PASS: TestClassCollector/no_quote--minify-true (0.00s)
    --- PASS: TestClassCollector/thead--minify-false (0.00s)
    --- PASS: TestClassCollector/thead--minify-true (0.00s)
    --- PASS: TestClassCollector/minified_a_href--minify-false (0.00s)
    --- PASS: TestClassCollector/minified_a_href--minify-true (0.00s)
    --- PASS: TestClassCollector/AlpineJS_bind_1--minify-false (0.00s)
    --- PASS: TestClassCollector/AlpineJS_bind_1--minify-true (0.00s)
    --- PASS: TestClassCollector/Alpine_bind_2--minify-false (0.00s)
    --- PASS: TestClassCollector/Alpine_bind_2--minify-true (0.00s)
    --- PASS: TestClassCollector/Alpine_bind_3--minify-false (0.00s)
    --- PASS: TestClassCollector/Alpine_bind_3--minify-true (0.00s)
    --- PASS: TestClassCollector/Alpine_bind_4--minify-false (0.00s)
    --- PASS: TestClassCollector/Alpine_bind_4--minify-true (0.00s)
    --- PASS: TestClassCollector/Alpine_bind_5--minify-false (0.00s)
    --- PASS: TestClassCollector/Alpine_bind_5--minify-true (0.00s)
    --- PASS: TestClassCollector/Alpine_transition_1--minify-false (0.00s)
    --- PASS: TestClassCollector/Alpine_transition_1--minify-true (0.00s)
    --- PASS: TestClassCollector/Vue_bind--minify-false (0.00s)
    --- PASS: TestClassCollector/Vue_bind--minify-true (0.00s)
    --- PASS: TestClassCollector/Apostrophe_inside_attribute_value--minify-false (0.00s)
    --- PASS: TestClassCollector/Apostrophe_inside_attribute_value--minify-true (0.00s)
    --- PASS: TestClassCollector/Script_tags_content_should_be_skipped--minify-false (0.00s)
    --- SKIP: TestClassCollector/Script_tags_content_should_be_skipped--minify-true (0.00s)
    --- PASS: TestClassCollector/Pre_tags_content_should_be_skipped--minify-false (0.00s)
    --- PASS: TestClassCollector/Pre_tags_content_should_be_skipped--minify-true (0.00s)
    --- PASS: TestClassCollector/Textare_tags_content_should_be_skipped--minify-false (0.00s)
    --- PASS: TestClassCollector/Textare_tags_content_should_be_skipped--minify-true (0.00s)
PASS
ok      github.com/gohugoio/hugo/publisher      0.330s
```

I am on:
```bash
hugo git:(master) ✗ hugo version                   
hugo v0.82.0+extended darwin/amd64 BuildDate=unknown
hugo git:(master) ✗ git rev-parse --short HEAD     
fa432b17
```

**Comment by dirkolbrich** [comment] 2021-04-14 23:13
first find:
`tdewolff/minify/v2/html.Minifier` should be configured with `KeepQuotes: true`, the default is `false`:

in `minifiers/config.go`:

```go
var defaultTdewolffConfig = tdewolffConfig{
	HTML: html.Minifier{
		KeepDocumentTags:        true,
		KeepConditionalComments: true,
		KeepEndTags:             true,
		KeepDefaultAttrVals:     true,
		KeepQuotes:              true,  // <- should be added
		KeepWhitespace:          false,
	},
```

For the other part of the "garbled" string from minifiy, I was mistaken and didn't understood the stream of data. Minify does not send the complete string or complete html tags to the html extraction. It sends token chunks of the start tag, if it has ids, classes or other attributes. It will leave end tags complete.

**Comment by dirkolbrich** [comment] 2021-04-16 09:44
Reactivating my former deleted comment: for the skipped test on minified `<script>...</script>` html content.
If adding test `fmt.Printf()`statements: 

```go
func (w *cssClassCollectorWriter) Write(p []byte) (n int, err error) {
	n = len(p)
	i := 0
	fmt.Printf("%v\n", string(p)) // <-- added test print
```

```go
for _, minify := range []bool{false, true} {
			c.Run(fmt.Sprintf("%s--minify-%t", test.name, minify), func(c *qt.C) {
				w := newHTMLElementsCollectorWriter(newHTMLElementsCollector())
				fmt.Printf("%v\n", test.html) // <- added test print
```

the incoming stream from minify for `<script>...</script>` html content just breaks off. Minify seem to delete anything behind the start tag.

```bash
=== RUN   TestClassCollector/Script_tags_content_should_be_skipped--minify-false
<script><span>foo</span><span>bar</span></script><div class="foo"></div>
<script><span>foo</span><span>bar</span></script><div class="foo"></div>
=== RUN   TestClassCollector/Script_tags_content_should_be_skipped--minify-true
<script><span>foo</span><span>bar</span></script><div class="foo"></div>
<script
>
    htmlElementsCollector_test.go:126: 
        error:
          values are not deep equal
        diff (-got +want):
            publisher.HTMLElements{
                Tags: []string{
          +             "div",
                        "script",
                },
          -     Classes: nil,
          +     Classes: []string{"foo"},
                IDs:     nil,
            }
        got:
          publisher.HTMLElements{
              Tags:    {"script"},
              Classes: nil,
              IDs:     nil,
          }
        want:
          publisher.HTMLElements{
              Tags:    {"div", "script"},
              Classes: {"foo"},
              IDs:     nil,
          }
        stack:
          /Users/dirkolbrich/Coding/gohugo/hugo/publisher/htmlElementsCollector_test.go:126
            c.Assert(got, qt.DeepEquals, test.expect)
```

Using:
```bash
➜  publisher git:(master) ✗ hugo version
hugo v0.82.0+extended darwin/amd64 BuildDate=unknown
➜  publisher git:(master) ✗ git rev-parse --short HEAD        
fa432b17
```

**Comment by liam-silvatech** [comment] 2022-07-19 10:34
I think this is related to my issue. For example without minify I can pass through say an entity of 0 (`&#x30;`). But with minify it replaces it with 0. Without minify it displays correctly in the HTML file with the entity. Is this related or should a new issue be raised?

**Comment by jmooring** [comment] 2023-07-06 19:16
Closing. If you feel this is still a problem, please open a new issue with a minimal reproducible example (i.e., a repository we can clone and test with).

**Closed by jmooring** 2023-07-06 19:16 UTC
Labels: Bug, NeedsInvestigation
