### ISSUE TITLE
Multihost doesn't handle a mix of baseURLs with and without a /path

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#10912] opened 2023-04-24 09:25 UTC
I'm doing some consolidation config work -- and there's a test case failing that should have passed.

Basically this config:

```toml
[Languages]
[Languages.en]
baseURL = "https://example.com/docs"
[Languages.fr]
baseURL = "https://example.fr"
```

**Comment by bep** [comment] 2023-04-26 07:49
OK, the above is actually a caching issue restricted to e.g. `resources.FromString` and not a general issue. Still a bug.

**Comment by bep** [comment] 2023-04-26 09:01
OK, I will wait a little before I fix this. For now the workaround would be to use .Permalink for shared resources.

**Comment by jmooring** [comment] 2023-05-29 19:17
Another symptom...

On a multilingual, multihost site where one of the baseURLs has a path, if you define menu entries in the root of the configuration (i.e., not under the language keys), the `.URL` returned from setting the `pageRef` property is incorrect for the site with a path in the baseURL.

**Comment by jmooring** [comment] 2024-01-20 04:50
Duplicate of #9324

**Closed by jmooring** 2024-01-20 04:50 UTC
Labels: Bug, NotSure, Feature: Multilingual
