### ISSUE TITLE
Make `.Summary` word limit configurable

### ISSUE THREAD

**Issue by gaow** [gohugoio/hugo#3693] opened 2017-07-10 16:17 UTC
Currently there is a 70 words limit for `.Summary`. This does not work very well for CJK languages because the summary will only show 70 characters without properly matching the end of the sentences. (symbol 。in Chinese). I'm wondering if word limit for `.Summary` can be made configurable? Thanks!

**Comment by mdhender** [comment] 2017-07-18 17:18
The default of 70 is set in `helpers/helpers.go`. You can work around that by using `<!-- more -->` in your markdown file. Would that work for your use?

**Comment by bep** [comment] 2017-07-18 17:29
This reasonable request, but I'm pretty sure it is a duplicate of another issue.

**Comment by mdhender** [comment] 2017-07-18 21:50
#1142 is very similar

**Comment by Xeoncross** [comment] 2017-08-14 22:00
Looks like one workaround would be to expose [Truncate()](https://github.com/gohugoio/hugo/blob/master/tpl/strings/truncate.go#L42) to the templates so you can do: `{{ Truncate .Summary 50 }}`

**Comment by bep** [comment] 2017-08-14 22:15
@Xeoncross We have a `truncate` template func. See the docs.

**Comment by bep** [comment] 2017-10-13 06:55
This was fixed recently. Use `summaryLength` config option.

**Closed by bep** 2017-10-13 06:55 UTC
Labels: Enhancement
