### ISSUE TITLE
Option to disable `findRE` global flag 

### ISSUE THREAD

**Issue by adhadse** [gohugoio/hugo#10825] opened 2023-03-12 11:51 UTC
For a simple capture of Submatch, the global flag makes it hard to capture the substring:
![image](https://user-images.githubusercontent.com/56764399/224542267-aadd1622-8c19-40d4-bb6d-717c2169a264.png)

But with 
![image](https://user-images.githubusercontent.com/56764399/224542245-f773816e-5340-4862-867c-3d1efcaac517.png)

I'm trying to capture the `id` attribute of `h2` using `findRESubmatch`, but ideally this should work with `findRE` as well. 

**I'm really having hard time capturing group using any of the Regex function provided by Hugo**

```html
<h2 id="implicit-deref-coercions">Implicit Deref Coercions 
<a href="#implicit-deref-coercions" class="anchor" aria-hidden="true">#</a>
</h2>
```

### What version of Hugo are you using (`hugo version`)?

<pre>
0.110.0
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by pamubay** [comment] 2023-03-12 14:14
Hugo/Golang using RE2 regex flavour, you can use `U` Ungreedy flag.

![regex](https://user-images.githubusercontent.com/18132440/224550310-51028e5b-eac5-4316-88eb-f55ab7c634ae.jpg)

Demo: https://regex101.com/r/3SYen0/1

**Comment by adhadse** [comment] 2023-03-12 15:22
@pamubay Why this does not capture the `id` attribute?

**Comment by pamubay** [comment] 2023-03-13 05:35
> @pamubay Why this does not capture the `id` attribute?

if you want capture the `id` then just add the `id`, `id=\"(?U:.+)\"`

Also this is not a bug, so please close this issue and always use https://discourse.gohugo.io/ for troubleshooting.

**Comment by bep** [comment] 2023-03-13 08:08
Have you looked at the recent addition of https://gohugo.io/functions/findre/#findresubmatch

**Comment by bep** [comment] 2023-03-13 08:15
As to the original request -- I have looked at the Hugo code for this and

* We don't add anything special to the regex, we just pass it to `regexp.Compile` in the Go stdlib.
* And the we just pass the input to `FindAllString`

**Comment by adhadse** [comment] 2023-03-15 00:22
I did looked into `findRESubmatch` but that didn't worked as well. It was capturing the whole sentence, instead of just the group because of global flag, I guess.

**Closed** 2023-05-20 19:33 UTC
Labels: Proposal
