### ISSUE TITLE
readDir behavior not restored by #9605

### ISSUE THREAD

**Issue by stefanv** [gohugoio/hugo#9611] opened 2022-03-04 20:14 UTC
Unfortunately, it does not look as though https://github.com/gohugoio/hugo/pull/9605 restored readDir behavior from 0.92.

I am comparing:

```
hugo v0.92.2-CDF6A0D6 linux/amd64 BuildDate=2022-02-11T14:17:39Z VendorInfo=gohugoio
hugo v0.93.2-643B5AE9 linux/amd64 BuildDate=2022-03-04T12:21:49Z VendorInfo=gohugoio
```

It looks like `readDir` now uses the project directory as base, instead of the theme directory—*even for partials in the theme*.

Confusingly, I think the new behavior is probably *more correct*, but it is still not the same as it was in 0.92.

**Comment by bep** [comment] 2022-03-04 21:00
I'll close this as duplicate of #9609 -- I'm not able to fix this in the near term, however, but others are welcome to chime in.

**Closed by bep** 2022-03-04 21:00 UTC
Labels: Bug, NeedsTriage

**Comment by stefanv** [comment] 2022-03-07 18:21
If it would be helpful, I can provide a git hash of a repository that builds with 92 but not 93.

We've now worked around the issue by using assets throughout.
