### ISSUE TITLE
Different behaviour between "hugo" & "hugo server" for baseURL 

### ISSUE THREAD

**Issue by divinerites** [gohugoio/hugo#7376] opened 2020-06-10 16:57 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.72.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
yes

I just noticed that I had a different behaviour between `hugo server` and `hugo` when it comes to  (I think) multi-language and trailing /.

So i created a minimal repo (https://github.com/divinerites/mytest) where you can see it happening. I also commited the /public folder so you can also see the problem on the generated HTML.

- my baseURL is : `baseURL = "https://www.mysite.org"`
- there is one section `highres` in 3 languages.
- When you run `hugo server` it works fine. You can click and link to all my pages and translations.

The line showing this problem is :@
```go-html-template
{{ .Lang }} : <a href="{{ site.BaseURL | absURL }}{{ .Lang }}">{{ site.BaseURL | absURL }}{{ .Lang }}</a><br>
```

In this (right) "live server" generated code you can see that i get a `/` after the `absURL`.
```html
en : <a href="http://localhost:1313/en">http://localhost:1313/en</a><br>
nl : <a href="http://localhost:1313/nl">http://localhost:1313/nl</a><br>
```

When I generate the HTML using just `hugo`, the `/` after the `absURL` is not generated 

This comes from the `public` folder :
```html
en : <a href="https://www.mysite.orgen">https://www.mysite.orgen</a><br>
nl : <a href="https://www.mysite.orgnl">https://www.mysite.orgnl</a><br>
```

I have this live on one of my site for this specific code. 
All the remaining (complex) code works fine.

For the record this is my real code :

```
<a class="btn btn-main" href="{{ .Site.GetPage "section" "highres" | relLangURL }}highres/">{{ i18n "highres" }} <i class="tf-ion-android-open"></i></a>
```

**Comment by khayyamsaleem** [comment] 2020-06-10 23:32
yep. not just trailing slash as well; if you have a baseURL like `abc.com/test/`, only `/test` is retained in the baseURL.

**Comment by divinerites** [comment] 2020-06-11 02:47
> yep. not just trailing slash as well; if you have a baseURL like `abc.com/test/`, only `/test` is retained in the baseURL.

I do not see this behaviour (0.72.0). i get `abc.com/test` (and the original problem of course)

```html
en : <a href="https://www.mysite.org/testen">https://www.mysite.org/testen</a><br>
```

**Comment by khayyamsaleem** [comment] 2020-06-11 06:36
@divinerites correct, i was mistaken.

**Comment by divinerites** [comment] 2020-06-12 17:13
And to be clear, the point is not "do I have a trailing `/` or not on baseURL", whatever rule is fine by me. I remember some talk/change (?) about this some months ago.

But why do we have a **different** behaviour between `hugo server` and `hugo`

**Comment by sergioagm** [comment] 2021-11-23 15:43
I'm having a somewhat related issue while trying to check if a page is active in a menu. I also am using multilanguage and I think I'm missing a trailing slash. 

The issue is in this line:

`{{ $active = or $active (eq (.URL | relLangURL) $current.RelPermalink) }}`

`hugo serve`: $active is true
`hugo`: $active is false

I noticed that the url generated with `hugo serve` is `http://localhost:1313/en/` with a trailing slash, so then the URL matches with RelPermalink and the menu entry is highlighted.

When I build the site with `hugo` the url is `http://localhost:1313/en` without a trailing slash, so the URL does not match and the menu entry is not highlighted .

 I've tried a build on netlify and also using python's `http.server` as a server and both have the same incorrect result when using the public build from `hugo.`

**Comment by sergioagm** [comment] 2021-11-23 16:37
Just did some testing and I was able to fix my issue by using `url` instead of `pageref` for the menu entry of the site config.yaml.

**Comment by jmooring** [comment] 2023-05-20 20:52
Simple example:

```
{{ warnf "%s" site.BaseURL }}
```

Then run:

```text
hugo        --baseURL http://example.org/docs   --> http://example.org/docs
hugo server --baseURL http://example.org/docs   --> http://example.org:1313/docs/  # trailing slash
```

This behavior has been around for years, at least as far back as v0.54.0, and probably much earlier.

Avoid this by always including a trailing slash in site configuration. Per the [docs](https://gohugo.io/getting-started/configuration/#baseurl):

> **baseURL** 
>
> The absolute URL (protocol, host, path, **and trailing slash**) of your published site (e.g., `https://www.example.org/docs/`).

I wish `site.BaseURL` wasn't exposed to the templates (this approach is fragile), but that ship sailed a long time ago. Site and theme authors should be using [absURL](https://gohugo.io/functions/absurl/) and [absLangURL](https://gohugo.io/functions/abslangurl/) instead, or using `.GetPage` / `resources.Get` / `.ResourcesGet` and then reference the `.Permalink` value. 

Adding a trailing slash, if missing, when running `hugo` will cause undesirable side effects for some sites.

Removing the trailing slash when running `hugo server` seems like a better idea, but that may break some stuff too.

**Comment by bep** [comment] 2023-05-20 21:06
>wish site.BaseURL wasn't exposed to the templates

I agree, but once we get a grip of what is the actual API and generate reference docs from it, we can at least start by hiding stuff that should not be exposed in the first place, e.g. `baseURL`.

**Comment by jmooring** [comment] 2023-11-25 20:52
Closing as duplicate of https://github.com/gohugoio/hugo/issues/11669.

**Closed by jmooring** 2023-11-25 20:52 UTC
Labels: NeedsInvestigation
