### ISSUE TITLE
Single-page template lookup order doesn't behave as documented

### ISSUE THREAD

**Issue by geealbers** [gohugoio/hugo#3809] opened 2017-08-17 04:47 UTC
When a page has both a `type` and a `layout`, according to [this example in the documentation](https://gohugo.io/templates/lookup-order/#example-my-second-post-md), Hugo will look for various templates in your project that explicitly match your layout name, say `layout: grid`, but will eventually fallback to the other defaults, all the way down to `/themes/<THEME>/layouts/_default/single.html`. However, the more generic fallbacks aren't actually built into the system, and **if Hugo does not find a template with the explicit layout name, the page fails to build** completely.

Here's a sample warning you get with `--verbose` that (I assume) shows all the places Hugo tried to look for a template for rendering the given page with `layout: grid`:

```
WARN 2017/08/16 16:58:52 [en] Unable to locate layout for "page": [post/grid.html.html post/grid.html _default/grid.html.html _default/grid.html theme/post/grid.html.html theme/post/grid.html theme/_default/grid.html.html theme/_default/grid.html]
```

The inner workings of Hugo and Go are a bit beyond my skills, but the issue seems to arise in the fact that Hugo assigns any page without an explicit `layout` to be equivalent to `layout: single`. So then, the template lookup order is either going to include the custom layout value, or the `single` default layout value, but can never include both custom and `single`. I believe the relevant code starts in `hugo/output/layout.go` lines 270–72, and then proceeds from there:

```go
if layout == "" {
  layout = "single"
}
```

I discovered the issue when trying to use the layout parameter to simply add classes to an existing page layout. (So, I didn't have or need a template file, just an `{{ if eq .Params.layout "grid" }}` call in the default page template.) This of course can be accomplished any number of other ways, but regardless, it seems like the underlying inconsistency should be addressed either by editing the documentation to match the current behavior, or by changing the Hugo layout code to match the documentation. Depending on the maintainers'/community's desired outcome.

Happy to help with the documentation part, but if the the Go is to be rewritten instead, afraid I'll need to leave that to someone else.

**Comment by bep** [comment] 2017-08-17 07:06
@geealbers thanks for this detailed report. Yes, I see what you mean and how this can be surprising. I rewrote the whole template lookup logic earlier this year to make it easier to test and extend, but I'm pretty sure that I followed the old logic.

That assumption would make the documentation wrong, but looking at it now I think the current behaviour is surprising and should be changed -- and changing it should not break (too much).

@rdwatters I assume you wrote the doc part on this... thoughts?

**Comment by rdwatters** [comment] 2017-08-17 17:56
Thanks @geealbers for pointing this out. So it seems like there are maybe two ideas being discussed here:

1. Correcting current docs.
2. Enhancements to current lookup order.

**1**

If this is a matter of just correcting the docs, I'll open up a separate issue in hugoDocs. I think the small gotcha is worth calling out; i.e., if you declare a layout and Hugo doesn't find the declared layout, it will not fall back to, in this case, `_default/single.html`. Just a matter of creating a `note` admonition at the bottom of the referenced example, as well as removing #'s 3,4,5,8,9,& 10 from the list in the docs.

**2**

Using the [same example](https://gohugo.io/templates/lookup-order/#example-my-second-post-md), I think what you're talking about would be documented as follows, @geealbers? I'm only mentioning this for my own clarification and since @bep marked this as an **enhancement**:

> 1. `/layouts/review/reviewarticle.html` 
> 2. `/layouts/posts/reviewarticle.html`
> 3. `/layouts/review/single.html`
> 4. `/layouts/posts/single.html`
> 5. `/layouts/_default/reviewarticle.html`
> 6. `/layouts/_default/single.html`
> 7. `/themes/<THEME>/layouts/review/reviewarticle.html`
> 8. `/themes/<THEME>/layouts/posts/reviewarticle.html`
> 9. `/themes/<THEME>/layouts/review/single.html`
> 10. `/themes/<THEME>/layouts/posts/single.html`
> 11. `/themes/<THEME>/layouts/_default/reviewarticle.html`
> 12. `/themes/<THEME>/layouts/_default/single.html`

Seems this would be a better separation of concerns for content files that that only declare a `layout` but allow Hugo to assume the`type` or for content files that only want to add `type` for content files that deviate from other files in a section. 

That said, with output formats, bundles, etc, my assumption is that this is a pretty big ask, @bep? Thanks!

**Comment by geealbers** [comment] 2017-08-17 18:51
Thanks to you both. I think if it's not too much trouble to change the behavior and allow Hugo to always fallback to a `single.html` template, that's ideal from a user perspective. And in that case, yes @rdwatters, your second (2) approach to the docs list looks good to me, though perhaps #5 in the list would move up to the third position and #11 would move to the ninth position? So, in effect, Hugo looks everywhere for the layout-specific template `reviewarticle.html` first, and then if it doesn't find it, it goes back to those same locations to look for then `simple.html` template instead. 

1. `/layouts/review/reviewarticle.html`
2. `/layouts/posts/reviewarticle.html`
3. `/layouts/_default/reviewarticle.html`
4. `/layouts/review/single.html`
5. `/layouts/posts/single.html`
6. `/layouts/_default/single.html`
7. `/themes/<THEME>/layouts/review/reviewarticle.html`
8. `/themes/<THEME>/layouts/posts/reviewarticle.html`
9. `/themes/<THEME>/layouts/_default/reviewarticle.html`
10. `/themes/<THEME>/layouts/review/single.html`
11. `/themes/<THEME>/layouts/posts/single.html`
12. `/themes/<THEME>/layouts/_default/single.html`

**Comment by Jonarod** [comment] 2018-02-18 22:39
I was about to open issue for exactly this same problem... Check [my post on the forum](https://discourse.gohugo.io/t/template-lookup-order/10619) if new ideas are welcome as well, but generally speaking `_default` should just act as default... :)

**Comment by Jonarod** [comment] 2018-02-18 22:41
@bep is there a specific reason to postpone this and not make it a Bug ?

**Comment by bep** [comment] 2018-02-19 08:02
>@bep is there a specific reason to postpone this and not make it a Bug ?

A bug is something that is not expected/designed. This is exactly as expected.

**Comment by Jonarod** [comment] 2018-02-19 14:23
Well, I understand it is expected for the developer but it is clearly not expected for the user. Can I help in any manner ?

**Comment by Jonarod** [comment] 2018-02-19 14:32
Here is an extract from [this page](https://gohugo.io/templates/lookup-order/):

Example | OutputFormat | Suffix | Template Lookup Order
-- | -- | -- | --
Single page in "posts" section with layout set | HTML | html | [layouts/posts/demolayout.html.html  layouts/posts/single.html.html layouts/posts/demolayout.html  layouts/posts/single.html layouts/_default/demolayout.html.html  layouts/_default/single.html.html layouts/_default/demolayout.html  layouts/_default/single.html]
-- | -- | -- | --

As you can see, one expects to have `layouts/_default/single.html` act as a fallback if the layout doesn't exist. So there is definitely a bug here, whether in the docs or in the code.
Like @geealbers I'd be happy to help to correct that but I might not grasp all consequences of modifying `hugo/output/layout.go` and have it accepted as a PR.
If you point me to the right direction I could eventually jump to the code and try something.

**Comment by Jonarod** [comment] 2018-02-19 20:44
Going a bit further, I found homepage lookup rules are broken as well:

Example | OutputFormat | Suffix | Template Lookup Order
-- | -- | -- | --
Home page | HTML | html | [layouts/page/index.html.html layouts/page/home.html.html  layouts/page/list.html.html layouts/page/index.html  layouts/page/home.html layouts/page/list.html layouts/index.html.html  layouts/home.html.html layouts/list.html.html layouts/index.html  layouts/home.html layouts/list.html layouts/_default/index.html.html  layouts/_default/home.html.html layouts/_default/list.html.html  layouts/_default/index.html layouts/_default/home.html  layouts/_default/list.html]
Home page with type set | HTML | html | [layouts/demotype/index.html.html layouts/demotype/home.html.html  layouts/demotype/list.html.html layouts/demotype/index.html  layouts/demotype/home.html layouts/demotype/list.html  layouts/index.html.html layouts/home.html.html layouts/list.html.html  layouts/index.html layouts/home.html layouts/list.html  layouts/_default/index.html.html layouts/_default/home.html.html  layouts/_default/list.html.html layouts/_default/index.html  layouts/_default/home.html layouts/_default/list.html]
Home page with layout set | HTML | html | [layouts/page/demolayout.html.html layouts/page/index.html.html  layouts/page/home.html.html layouts/page/list.html.html  layouts/page/demolayout.html layouts/page/index.html  layouts/page/home.html layouts/page/list.html  layouts/demolayout.html.html layouts/index.html.html  layouts/home.html.html layouts/list.html.html layouts/demolayout.html  layouts/index.html layouts/home.html layouts/list.html  layouts/_default/demolayout.html.html layouts/_default/index.html.html  layouts/_default/home.html.html layouts/_default/list.html.html  layouts/_default/demolayout.html layouts/_default/index.html  layouts/_default/home.html layouts/_default/list.html]
-- | -- | -- | --


The lookup order is just inconsistent, I really struggle to understand how I should organize my themes to render one simple page... 
- `home.html` is not recognized for homepage
- if layout is set in `./content/_index.md`, it is not recognized either
- if type is set in `./content/_index.md`, it is not recognized either
- ...
in fact nothing works at all: the only rule working is to have a `./layouts/index.html` or `./layouts/list.html` template. That's about it.

If neither `type` nor `layout` has effect on homepages, how one should change homepages depending on special events ? I think homepage is the most changed/animated page, and having `layout` disappear for this specific page kind is just a deal breaker... One should be able to have multiple homepages like `christmasPage`, `blackFridayPage`, `whateverPage`: the only option I see is using `layout` to switch template accordingly. If one should delete/replace `index.html` at each new event... it will soon become unpractical.
@bep Is it the expected behavior ?

**Comment by bep** [comment] 2018-02-19 20:53
>@bep Is it the expected behavior ?

You shold take questions on the forum. Do not hijack remotely related issues. 

But I would advise you to update to the latest Hugo to avoid confusion. Note that the table you have copy-and-pasted is generated from the **actual implementation**, so it is correct.

**Comment by jmooring** [comment] 2023-05-08 04:19
The template lookup order documentation is generated from code; it correctly describes the behavior. I suspect a number of related things have changed since this issue was created 6 years ago.

**Closed by jmooring** 2023-05-08 04:19 UTC
Labels: Enhancement
