### ISSUE TITLE
Multi-language server base URL mismatch

### ISSUE THREAD

**Issue by Wirone** [gohugoio/hugo#12123] opened 2024-02-23 01:41 UTC
### What version of Hugo are you using (`hugo version`)?

Currently I use 0.111.3 and it works well. The problem occurs for Hugo 0.112.4 and is reproducible with 0.123.2 (both on `floryn90/hugo` image or Hugo from Homebrew).

### The problem

When I run the server on the newest version, I get summary:

```
hugo-1  |                    | EN  | PL   
hugo-1  | -------------------+-----+------
hugo-1  |   Pages            | 116 | 125  
hugo-1  |   Paginator pages  |   4 |   4  
hugo-1  |   Non-page files   |   0 |   0  
hugo-1  |   Static files     |  36 |  36  
hugo-1  |   Processed images |   0 |   0  
hugo-1  |   Aliases          |  43 |  48  
hugo-1  |   Cleaned          |   0 |   0  
hugo-1  | 
hugo-1  | Built in 1629 ms
hugo-1  | Environment: "DEV"
hugo-1  | Serving pages from disk
hugo-1  | Web Server is available at http://localhost:1314/ (bind address 0.0.0.0) en
hugo-1  | Environment: "DEV"
hugo-1  | Web Server is available at http://localhost:1313/ (bind address 0.0.0.0) pl
hugo-1  | Press Ctrl+C to stop
```

At first it looks OK, but the URLs are incorrectly labelled - the actual languages are swapped. When I enter `http://localhost:1314/` I have `pl` version, but the weirdest thing is that when I click the logo, the port is changed and I switch the language, and when I want to display single post I get 404 because URL has port pointing to one language, but slug is from the other one (posts with the same slug work properly).

On 0.111.3 and PaperMod `efe4cb45` it works properly, and when I update Hugo (and PaperMod for compatibility), the outcome of the `hugo server` is invalid.

I have multi-language site with such `config/_default/languages.yml`:

```yaml
pl:
  contentDir: content/pl
  baseURL: https://blog.codito.pl/
  languageName: ':poland:'
  languageCode: pl
  paginatePath: strona
  title: Codito.pl
  weight: 1
  taxonomies:
    category: kategorie
    tag: tagi
    series: serie
  params:
    languageAltTitle: Polski
  menu:
    main:
      - name: Serie
        url: /serie
        weight: 1
      - name: Kategorie
        url: /kategorie
        weight: 2
      - name: Tagi
        url: /tagi
        weight: 3
      - name: 🔍
        url: /szukaj
        weight: 4
      - name: ℹ️
        url: /o-mnie
        weight: 5

en:
  contentDir: content/en
  baseURL: https://blog.codito.dev/
  languageName: ':gb:'
  languageCode: en
  title: Codito.dev
  weight: 2
  taxonomies:
    category: categories
    tag: tags
    series: series
  params:
    languageAltTitle: English
  menu:
    main:
      - name: Series
        url: /series
        weight: 1
      - name: Categories
        url: /categories
        weight: 2
      - name: Tags
        url: /tags
        weight: 3
      - name: 🔍
        url: /search
        weight: 4
      - name: ℹ️
        url: /about
        weight: 5
```

I am aware of [changes in 0.112.0](https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120), but even if I move my `taxonomies` under `params` and modify templates accordingly, I still get URL mismatch and just can't work on the blog comfortably.

Is there something that I'm missing, or is it just a bug in Hugo? It looks like `absLangURL`'s behaviour has changed (at least for development, I did not try to build production pages yet).

PS. Thanks for your great work!

**Comment by jmooring** [comment] 2024-02-23 03:14
I am unable to reproduce the problem as described, testing with v0.123.2.

```text
git clone --single-branch -b hugo-github-issue-12123 https://github.com/jmooring/hugo-testing hugo-github-issue-12123
cd hugo-github-issue-12123
hugo server
```

**Comment by Wirone** [comment] 2024-02-23 08:44
@jmooring based on your repo I created [actual reproducer](https://github.com/Wirone/hugo-github-issue-12123). After `hugo server` please follow these steps:

- click the `http://localhost:1314/ (bind address 127.0.0.1) en` → DE version is opened
- click [Post 1 (de)](http://localhost:1314/2024/02/post-1-de/) → post is OK
- `:de:` link is invalid (`http://localhost:1313/2024/02/post-1-de/`) because it has different port for the same language → 404 because of non-existing slug

**Comment by jmooring** [comment] 2024-02-24 02:41
@Wirone Your [last commit](https://github.com/Wirone/hugo-github-issue-12123/commit/3abcef1d564cebcce1b6cb664da194c340ad2041) introduced a configuration conflict. There's the original hugo.toml file in the root, and then the new files you added in the config directory. 

Try this again:

```text
git clone --single-branch -b hugo-github-issue-12123 https://github.com/jmooring/hugo-testing hugo-github-issue-12123
cd hugo-github-issue-12123
git submodule update --init
hugo server
```

My last commit message is:

> Org translations by directory, rename content files, add translation keys.

**Comment by jmooring** [comment] 2024-02-24 18:22
@Wirone In the interest of keep our v0.123.x issue list clean, I am closing this for now. We can re-open if necessary, but everything looks right to me.

**Closed by jmooring** 2024-02-24 18:22 UTC
Labels: Bug, NeedsTriage, NeedsUserFeedback

**Comment by Wirone** [comment] 2024-02-24 19:25
@jmooring thank you for pointing me into the right direction, after a quick look it looks like it indeed fixes the URL mismatch issue 🙂. I believe I've tested it at some point, but maybe had some other changes applied and it did not work.

I still need to address other changes, but at least the site is properly navigable so I can verify things. Thank you!
