### ISSUE TITLE
Bug with i18n & Language Code `pl`

### ISSUE THREAD

**Issue by MunifTanjim** [gohugoio/hugo#3947] opened 2017-10-07 08:31 UTC
**Test Repo**: https://bitbucket.org/MunifTanjim/hugo-test

**Hugo Version**: v0.29
**OS**: Ubuntu 16.04

### /config.toml
```toml
baseURL = "http://example.org/"
title = "Hugo Test Site"

[languages.en]
lang = "en"
[languages.fr]
lang = "fr"
[languages.pl]
lang = "pl"
```

### /i18n/en.toml
```toml
[test]
one = "test en {{ .Count }}"
other = "test en {{ .Count }}"
```

### /i18n/pl.toml
```toml
[test]
one = "test pl {{ .Count }}"
other = "test pl {{ .Count }}"
```

### /layouts/index.html
```html
<!DOCTYPE html>
<html>

<head>
  <title>{{ .Site.Title }}</title>
</head>

<body>
  <p>{{ i18n "test" 1 }}</p>
  <p>{{ i18n "test" 2 }}</p>
</body>

</html>
```

### localhost:1313/
```
test en 1
test en 2
```

### localhost:1313/pl/
```
test pl 1
test
```

## Description

As you can see, the plural (i.e. `other` part of the i18n file) translation is not being detected when the language code is **`pl`**. But it works for any other language code.

I've reproduced the same bug with Hugo v0.28 & v0.27 too. Didn't tried with older versions than those though.

**Comment by bep** [comment] 2017-10-07 09:07
It is probably a duplicate of a related issue ... somewhere. There is a fix in the works, but no-one has taken the time to "do it".

**Comment by kzys** [comment] 2017-10-10 03:40
Polish's plural form has 4 categories (one, few, many and other) according to [the Unicode spec](https://www.unicode.org/cldr/charts/29/supplemental/language_plural_rules.html#pl), which seems referenced by [go-i18n](https://github.com/nicksnyder/go-i18n/blob/ca33e78c8a430e2df435b02f63a3944fa8e9ea11/i18n/language/codegen/plurals.xml#L152). So, `pl.toml` should have 4 entires like below.

```
[test]
one = "test pl {{ .Count }}"
few = "test pl {{ .Count }}"
many = "test pl {{ .Count }}"
other = "test pl {{ .Count }}"
```

Probably we can show more user-friendly message?

**Comment by MunifTanjim** [comment] 2017-10-13 21:24
Okay, this is not a bug.

Perhaps this issue should be closed.

**Closed** 2017-10-13 21:25 UTC
