### ISSUE TITLE
Bootstrap 4.4.1's SASS fails in Hugo

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6945] opened 2020-02-23 15:08 UTC
```bash
SCSS processing failed: file "/var/folders/wy/g1rt5g3s5bd9flpq8g1741740000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/github.com/twbs/bootstrap@v4.4.1+incompatible/scss/_mixins.scss", line 6, col 1: File to import not found or unreadable: vendor/rfs. 
```

/cc @XhmikosR

**Comment by bep** [comment] 2020-02-23 15:12
Last working version is 4.2.1.

**Comment by XhmikosR** [comment] 2020-02-24 10:13
v4.2.1 didn't have the RFS patch landed hence why it worked. I'm not familiar with how modules work here, so let me ask you a couple of things:

1. Is the vendor folder included?
2. Can you pass extra include options?
3. I assume it's not a caching issue?
4. How can we try to reproduce the issue ourselves?

/CC @MartijnCuppens for any ideas

**Comment by bep** [comment] 2020-02-24 10:33
@XhmikosR I think I know what's happening. Will get back in a while.

**Comment by bep** [comment] 2020-02-24 11:10
OK, so the problem is a bug in Go. I have reported it upstream and I assume it will get priority, but one never knows.

In Go Modules, the top-level `/vendor` directory in a module has a special meaning, so they delete it from the bundle after downloading. Sadly, their regexp (or whatever) is a little aggressive, so this folder goes as well:

https://github.com/twbs/bootstrap/tree/master/scss/vendor

Note that if you mount that folder from the project itself, you will not experience this.

There may be other workarounds until this gets fixed upstream, but you would do me a solid if you could rename this folder to something else (`vendors`, "_vendor`... whatever).

**Comment by XhmikosR** [comment] 2020-02-24 11:15
The thing is that this change can be a breaking one so we definitely can't make it in a patch version. Also, this would affect everyone else that expects the file to be there, which is something we generally try to avoid doing because it doesn't result in the best user experience.

Referencing your upstream issue https://github.com/golang/go/issues/37397

**Comment by bep** [comment] 2020-02-24 11:20
OK, I guess can create a "Boostrap repo wrapper" with this _rfs.scss file duplicated. O well, one more thing to maintain.

**Comment by MartijnCuppens** [comment] 2020-02-24 13:12
Renaming the folder will be a breaking change on our side indeed, I'm afraid we can't change that for this case.

**Comment by bep** [comment] 2020-02-24 13:45
No worry, I actually came up with a good way to work around this.

**Comment by bep** [comment] 2020-02-24 16:41
See https://github.com/gohugoio/hugo-bootstrap-scss-v4/issues/1

**Closed** 2020-02-24 18:14 UTC
Labels: Bug, Upstream
