### ISSUE TITLE
While running hugo server, if new taxonomy values gets added to content post, create also its list page

### ISSUE THREAD

**Issue by ralexrdz** [gohugoio/hugo#10901] opened 2023-04-17 13:48 UTC
Steps to reproduce

1. Create new hugo site

```
hugo new site my-hugo-site
cd my-hugo-site
git init
git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke themes/ananke
echo "theme = 'ananke'" >> config.toml
```

2. Run huge server and visit the localhost:1313/tags, which should be empty

3. Using text/code editor add some tags to the front matter of the post: content/posts/my-first post.md

```
---
title: "My First Post"
date: 2023-04-16T09:31:16-06:00
draft: false
tags: ["foo", "bar"]
---
```

4. visit again localhost:1313/tags and voila! automagically, there is are "foo" and "bar" categories, and under them my first post (expected behavior)

5. Click the link of one of the tag titles and will redirect to localhost:1313/tags/foo

### **Real behavior: 404 page not found**

6. stop hugo server command using ctrl + c and restart it

The page localhost:1313/tags/foo now shows its list page showing my-first-post as expected

I think there is a missing feature when new content get added, beacouse terms page for tags get updated automatically, but no list page is created. You depend on rerunning hugo server to see it working. 

I need this because I have a simple CMS for my site using [File Browser](https://filebrowser.org/) and running my site with hugo server to avoid rebuilding or restarting when new files gets added or are updated

**Comment by jmooring** [comment] 2023-04-17 18:07
It looks like this worked as expected prior to v0.103.0.

@ralexrdz  Do not use `hugo server` for your production site. It is a development server with optimizations and limitations that make it unsuitable for production.

**Comment by nikumbgo12345** [comment] 2023-05-05 11:29
I am new to this repo and would like to take this issue please assign this to me

**Comment by tveyben** [comment] 2024-01-14 22:27
Issue reproduced on the current build [1] as well
I came here after wondering what I did wrong when trying to generate my first Hugo based site, not a good start ;-)

Seems like this might be a duplicate of https://github.com/gohugoio/hugo/issues/9533

[1]
`hugo v0.121.2-6d5b44305eaa9d0a157946492a6f319da38de154 linux/amd64 BuildDate=2024-01-05T12:21:15Z VendorInfo=gohugoio
`

**Comment by jmooring** [comment] 2024-02-14 15:39
Duplicate of #95.33

**Closed by jmooring** 2024-02-14 15:39 UTC
Labels: Bug, NeedsTriage, Feature: Server
