### ISSUE TITLE
`#` not escaped in Permalink when in title value

### ISSUE THREAD

**Issue by tcg** [gohugoio/hugo#4926] opened 2018-07-10 15:50 UTC
Initially posed a question in the forum: https://discourse.gohugo.io/t/hash-pound-sign-not-escaped-in-title-permalink-breaking-urls/12825

This seems really strange to me as a default behavior, and feels like a bug. Allow me to asplain? 

I have a post title, like `tcg's series of posts #1`. 

The [Permalinks configuration examples](http://gohugo.io/content-management/urls/#permalinks-configuration-example) in the docs contain the following example: 

`post = "/:year/:month/:title/"`

... which lead me to believe that this would pretty much automatically work for my not-unreasonable post titles. ("work" here meaning "escape the URL for `.Permalink` and filename value automatically). 

In the forum, [maiki](https://discourse.gohugo.io/t/hash-pound-sign-not-escaped-in-title-permalink-breaking-urls/12825/2) suggested that I might use `:slug` as a workaround, meaning that I would need to always manually provide `:slug`. 

Also, the aforementioned docs says this about `:slug`: 

> the content’s slug (or title if no slug is provided in the front matter)

Meaning that it will always fall back to `:title` if I fail to provide a slug. Which seems to me like **I always have to be sure to manually provide a URL-friendly value... as a human**, writing a document. That doesn't feel right. 

I think this is a bug. (Sadly, I am not yet familiar enough with Go to find a spot and try to offer a PR for the expected behavior).

I am willing to be wrong, and understand I may be Doing It Wrong. 

EDIT: 

Using versions **`0.42.2`** and **`0.43`**, on macOS

**Comment by frenck** [comment] 2018-07-12 19:59
Confirmed, same issue on my machine.
Causes Netlify to fail.

I've even used `:slug`, which renders the same issue.

**Comment by moorereason** [comment] 2018-07-12 21:12
Assuming this would be fixed by #4388.

**Comment by tcg** [comment] 2018-08-18 23:40
Great news! Hope to see it in soon!

**Comment by tcg** [comment] 2018-09-05 02:56
I saw https://github.com/gohugoio/hugo/pull/4388 was merged, and I am assuming it made it into v0.48, is that correct? 

On the site where I've run into this the most, I'm not seeing this fixed, if that's the case. Or has that merge not made it into a release? 🤷‍♂️    Just wanted to get this closed if it was fixed, but I'm not sure if that's the case.

**Comment by Jos512** [comment] 2018-09-05 06:04
> On the site where I've run into this the most, I'm not seeing this fixed, if that's the case. Or has that merge not made it into a release?

According to the release notes it's included in Hugo 0.48. The issue is the third bullet point in the 'Fixes' part of the [0.48 release notes](https://github.com/gohugoio/hugo/releases/tag/v0.48).

**Comment by onedrawingperday** [comment] 2018-09-05 09:35
It seems that this issue was not closed when #4388 was merged.

I can reproduce in Hugo 0.48

In the meantime @tcg you can always remove the hash `#` from the Permalink string in your templates with the [`replaceRE`](https://gohugo.io/functions/replacere/#readout) function.

**Comment by tcg** [comment] 2018-09-05 16:53
@onedrawingperday Thanks for the suggestion. I think I mentioned previously how I'm working around it. Specifically on one site, I am manually specifying the `url` value for the posts in question, to work around `.Permalink` containing a bad value. 

I'm of the opinion that the Theme code shouldn't necessarily concern itself with fixing permalink values, etc.

**Comment by onedrawingperday** [comment] 2018-09-20 17:48
I know that #5170 was not tested against my test repo (I never requested it and also I had removed the repo from GitHub).

Anyway it's a good thing that I am on the latest Hugo DEV so that I can see if PRs break things before they make it into a release.

I will keep an eye on this issue and any PR that will address it.

**Comment by maxammann** [comment] 2019-03-22 22:39
I still have this issue on `Hugo Static Site Generator v0.54.0/extended linux/amd64 BuildDate: unknown`

{{ .RelPermalink }} can return a link with a non-escaped hashtag.

**Comment by clanstyles** [comment] 2019-03-24 21:09
I'm having the same issue. This is causing our sites to break!

**Comment by bep** [comment] 2019-03-24 22:18
I guess the fix for this was reverted because it broke other stuff. I'm reopening this and closing the other.

**Comment by ErikSchierboom** [comment] 2019-05-13 13:04
Same issue for me as well

**Comment by szpak** [comment] 2020-02-28 10:01
I've just bump into this issue. Changing `posts = "/:year/:month/:day/:title/"` to `posts = "/:year/:month/:day/:slug/"` helps, but it took me a moment to find it (the documentation doesn't explain difference between `title` and `slug` in the context of quoting).

**Comment by thomaslevesque** [comment] 2020-05-16 17:50
I have the same problem with '#' in a taxonomy
For instance I have a `series` taxonomy, and one of my posts has the value "Things every C# developer should know" for this taxonomy. Unfortunately the `.RelPermalink` of the taxonomy page returns `/series/things-every-c#-developer-should-know/`. The correct permalink should be `/series/things-every-c%23-developer-should-know/`

**Comment by bcspragu** [comment] 2020-07-14 14:00
Just ran into this as well, with a tag that starts with a hashtag. Using

`replaceRE "#" "%23" .Permalink`

fixes it, but that only handles one page, and doesn't handle the taxonomy list and other places.

**Comment by tcg** [comment] 2021-02-03 04:17
Not trying to pile on anything, but bumped into this today on a fresh `brew install`, and just contributing "documentation" on my current version and how I'm working around it. (In case anyone else finds this issue via search). 

```
❯ hugo version
Hugo Static Site Generator v0.80.0/extended darwin/amd64 BuildDate: unknown
```

I regret not learning more Go and not being able to contribute directly to the solution for this. 

My `config.toml`: 

```toml
[permalinks]
  pages = ":title"
  blog = "blog/:slug"
```

Set "blog" to slug, because that's how I'm working around this issue for now: manually providing the `slug:` value in my markdown front-matter for posts that I'd prefer to title with a hash/pound. Hugo is still generates the automatic slug (for `:title`, or when `slug:` is not provided in front-matter) with a hash in the string.

**Comment by bryanjhogan** [comment] 2021-02-04 02:16
> I've just bump into this issue. Changing `posts = "/:year/:month/:day/:title/"` to `posts = "/:year/:month/:day/:slug/"` helps, but it took me a moment to find it (the documentation doesn't explain difference between `title` and `slug` in the context of quoting).

Thanks, this helped be get C# into my titles.

**Comment by bryanjhogan** [comment] 2021-02-04 02:21
This is what works for me - 

`config.toml`
```
[permalinks]
  post = "/:year/:month/:slug/" 
```
  
Then in my post - 
```
title: C# and...
slug: C and...
```

**Comment by maxammann** [comment] 2021-02-04 08:51
@bradleypeabody I think that is because title is not included in your permalink. According to docs I think this should be possible.

**Comment by bryanjhogan** [comment] 2021-03-11 15:07
> @bradleypeabody I think that is because title is not included in your permalink. According to docs I think this should be possible.

Can you give an example?

**Comment by maxammann** [comment] 2021-03-12 19:59
> Can you give an example?

https://gohugo.io/content-management/urls/#permalinks-configuration-example

**Comment by bryanjhogan** [comment] 2021-03-12 21:24
> > @bradleypeabody I think that is because title is not included in your permalink. According to docs I think this should be possible.
> 
> Can you give an example?

With `posts: /:year/:month/:title/` the url contains a '#', and the hugo can't find the corresponding post.

**Comment by david-bakin** [comment] 2021-04-29 03:49
Just reporting that it is still happening in `hugo v0.82.1-60618210+extended windows/amd64 BuildDate=2021-04-20T11:02:50Z VendorInfo=gohugoio` and furthermore you can't have a tag with a `#`, like `C#`, either.  (At least with the "cactus" theme.)

**Comment by jnguk** [comment] 2023-04-30 08:35
so... any progress?

**Closed** 2024-04-05 13:57 UTC
Labels: Bug
