### ISSUE TITLE
Merging object arrays

### ISSUE THREAD

**Issue by tednoelker** [gohugoio/hugo#3822] opened 2017-08-21 14:00 UTC
In my site data, I have two arrays of objects located in two different files.

**/data/file1.json**

    "array1": [
        {
            "key1": "a",
            "key2": "b"
        },
        {
            "key1": "c",
            "key2": "d"
        }
    ]

**/data/file2.json**

    "array2": [
        {
            "key1": "x",
            "key2": "y"
        }
    ]

In Hugo v0.21, I was able to use the `union` function to merge these arrays and range over them with the same loop.

    {{ range $loop := union $.Site.Data.file1.array1 $.Site.Data.file2.array2 }}
        <h1>{{ .key1 }}</h1>
        <p>{{ .key2 }}</p>
    {{ end }}

Since updating to v0.26, I now get a fatal `runtime error: hash of unhashable type map[string]interface {}` error at this function.

Is it possible that `union` would support this again? Or is there another function that could accomplish this?

For what it's worth, I'm not necessarily concerned with catching duplicate objects, just a simple merge of the two.

**Comment by bep** [comment] 2017-08-21 14:59
Duplicate of #3820

**Closed by bep** 2017-08-21 14:59 UTC

**Comment by tednoelker** [comment] 2017-10-05 17:43
Could this be reopened? I don't believe that's it's been solved in the duplicate issue.

**Comment by moorereason** [comment] 2017-10-05 17:53
@tednoelker, the duplicate issue isn't resolved yet.
