### ISSUE TITLE
Docs for RSS template do not seem correct

### ISSUE THREAD

**Issue by cfjedimaster** [gohugoio/hugo#2922] opened 2017-01-10 17:28 UTC
According to the docs for the default RSS template (https://gohugo.io/templates/rss/), one can include an author name value and see it reflected in the index.xml. In my testing, this was not the case. In fact, I do not see the managingEditor block at all.

**Comment by digitalcraftsman** [comment] 2017-06-22 19:35
Is this still an issue?

**Comment by cfjedimaster** [comment] 2017-06-23 13:02
I went to test, but ran into #3638.

**Comment by cfjedimaster** [comment] 2017-06-25 21:50
Seems to be fixed

**Comment by digitalcraftsman** [comment] 2017-06-26 18:27
Then I'll close this issue. If the issue is still existing please open a new issue at gohugo/hugoDocs instead.

**Closed** 2017-07-08 11:37 UTC
Labels: Docs
