### ISSUE TITLE
google_analytics_async.html should be deprecated and removed

### ISSUE THREAD

**Issue by carlmjohnson** [gohugoio/hugo#11467] opened 2023-09-18 19:47 UTC
_internal/google_analytics_async.html no longer works, which is okay because Google removed the version of Google Analytics it uses, but Hugo doesn't emit any warning about it. Hugo should begin emitting a warning to anyone who includes it and remove it at some point down the line.

**Comment by jmooring** [comment] 2023-09-18 19:50
Duplicate of https://github.com/gohugoio/hugo/issues/10899

**Closed by jmooring** 2023-09-18 19:50 UTC
Labels: Bug, NeedsTriage
