### ISSUE TITLE
<!--more--> breaks  shotcodes.  How to fix that?

### ISSUE THREAD

**Issue by IzyI** [gohugoio/hugo#7203] opened 2020-04-23 11:11 UTC
I have this  version of Hugo:
### Hugo Static Site Generator v0.64.0-DEV linux/amd64 BuildDate: unknown

Hey there, Ive got a problem.
I need to output some of my Summary html from the entries to the page list.html.
The code that generates summary:
```
{{ $paginator := .Paginate (.Pages.ByDate.Reverse) }}
{{ range $paginator.Pages}}
{{ .Render “summary”}}
{{ end }}
```

In order to specify what exactly I want in the summary Iv found the following:
<--more-->

Lets suggest that iv created an article and im writing the following code:
https://github.com/IzyI/blog/blob/master/content/it/first.html

But if I write the code in my articles, the shotcodes in archetypes templates stop working and delete the first pert of the article.

https://aws1.discourse-cdn.com/standard10/uploads/gohugo/original/2X/1/15a82eec6d689a2bbfb4e314fbd4d76f55b66cc5.png

At the same time summary in list.html template is still correct.

Where do I have problems?

**Comment by tristan957** [comment] 2020-04-29 04:18
Hi @IzyI. I would recommend against writing inline html in your markdown. Hugo knows where paragraphs start and end and will insert `p` accordingly. I am using shortcodes in my site just fine.

github.com/tristan957/tristan.partin.io and am not seeing your behavior. This should fix your issue. However it is unclear whether this is a bug or intended behavior to me. I am fairly new to hugo.

**Comment by IzyI** [comment] 2020-05-15 21:09
> Hi @IzyI. I would recommend against writing inline html in your markdown. Hugo knows where paragraphs start and end and will insert `p` accordingly. I am using shortcodes in my site just fine.
> 
> github.com/tristan957/tristan.partin.io and am not seeing your behavior. This should fix your issue. However it is unclear whether this is a bug or intended behavior to me. I am fairly new to hugo.


Thank you so much

**Comment by tristan957** [comment] 2020-05-18 03:50
No problem. Happy hacking!

**Comment by lawik** [comment] 2020-09-18 08:26
This issue seems quite right. Using the  tag in an HTML file will also break shortcodes. Example: https://github.com/lawik/moresyntax (theme is submoduled, just followed the quickstart and added a minimal case)

**Comment by lawik** [comment] 2020-09-18 09:22
I'm working with a site that uses the HTML format, not the markdown format. When using that the  tag breaks shortcodes. Which is weird.

I've tried to verify this with a test that can be seen at: https://github.com/gohugoio/hugo/compare/master...lawik:shortcodes-more

I'm not a go dev so digging into the how and why it is broken is a bit complex for me. But it definitely seems broken to me.

**Comment by jmooring** [comment] 2021-05-01 14:27
Duplicate of https://github.com/gohugoio/hugo/issues/6686

**Closed by jmooring** 2021-05-01 14:27 UTC
Labels: Duplicate
