### ISSUE TITLE
Support wiki-style internal page links

### ISSUE THREAD

**Issue by rcoreilly** [gohugoio/hugo#3606] opened 2017-06-18 14:47 UTC
It would be great if hugo could support wiki-style page links, as in the git-hub wiki syntax:
https://help.github.com/articles/adding-links-to-wikis/

This has been suggested a few times it seems:

* https://discourse.gohugo.io/t/internal-links-hugo-as-wiki-backend/3518/3
* https://discourse.gohugo.io/t/automated-linking-wiki-like-behaviour/4244
* https://discourse.gohugo.io/t/support-wiki-internal-link-converson-to-relref-shortcode/6074

But I didn't see an open bug ticket on it, so.. here goes -- please mark as a duplicate if I somehow missed it.

Proposal:

* This would make a link to another wiki page with given title: `[[Page Title]]`  -- it would find page based on the title property of the pages, and render the link (via the pathed file name) for you.

* You can optionally include alternative link text: `[[Alternative Text|Page Title]]` and also use the file name, but it would still use the title for the link if avail for that page: `[[docs/my_file_name]]` renders link with text as title of that page

Motivation:

* Current link syntax requires significant duplicate typing -- one of the main design criteria for the Go language was to remove all that "stuttering" kind of thing -- very annoying to constantly be typing something like `[My Page Here](docs/my_page_here)`.

* The `[[ ]]` link syntax is standard on the git hub wiki, and on the widely-used mediawiki, so it will be familiar to many users.

* Using the page title instead of the path is more robust if you decide to reorganize your file structure.

* We are just experimenting with porting our wiki from mediawiki to hugo and this link issue is the main remaining barrier to having the new platform be a clear win!  Hugo can be a great wiki platform, but the high density of internal links in a wiki requires this simpler kind of link syntax.

Thanks for making such an awesome tool!

**Comment by maiki** [comment] 2017-06-18 18:20
I've dealt with internal linking for a while, so I am gonna throw out the low-hanging fruit, planning-wise:

* How does the internal linking work for capitalization? Does it standardize the title using the same rules as slugs?
* How does it handle namespaces/sections? When I type `[[About]]`, does it go to `/about/` or `/other-project/about/`? We want to make sure folks don't need to change their site structure in order to use the link brackets effectively.
* Will it throw errors if links are non-existent? For instance, I change a page title, on the next build will there be errors about the links that were pointing at that page title?

**Comment by bep** [comment] 2017-06-18 19:21
@maiki about the middle one, and I guess the challenging part of this, is about the handling of ambiguous links, i.e. which one to pick. I'm not sure how MediaWiki handles this, but I'm pretty sure they "pick one".

To me, it would be natural to pick the one closest in "file system distance", so given this tree:

```
about/blog
about/blog/subsection
```
A link to `about` in `blog/subsection` would be ambiguous, but pick the one with the longest prefix match, i.e. `about/blog/subsection`. This is also extremely fast.

**Comment by maiki** [comment] 2017-06-18 20:03
> I'm not sure how MediaWiki handles this, but I'm pretty sure they "pick one".

@bep in MediaWiki they have the concept of namespaces, and the default namespace is without prefix. Taking Wikipedia for example (assume editing on a page there), here are some [internal link](https://www.mediawiki.org/wiki/Help:Links#Internal_links) examples:

* `[[Tron]]` > https://en.wikipedia.org/wiki/Tron
* `[[Talk:Tron]]` > https://en.wikipedia.org/wiki/Talk:Tron
* `[[User:マイキ]]` > https://en.wikipedia.org/wiki/User:マイキ

[Namespaces](https://www.mediawiki.org/wiki/Help:Namespaces) are nearly identical to "sections" in Hugo as they are used by site editors; there are some special namespaces, but they are primarily used to "differentiate between the purpose of the pages at a high level".

But note that following the method prescribed by MediaWiki may not make sense elsewhere. URLs and linking is kinda wonky, and presents a lot of caveats. For instance, wiki articles are named intentionally as fact, whereas the title of my site's about page can change over time.

I like the idea of making the [rel/relref](http://gohugo.io/extras/shortcodes/#ref-relref) shortcode work with double brackets. It doesn't help convert a MediaWiki instance to Hugo as @rcoreilly is doing, but that process is going to be finicky anyhow, since Hugo doesn't produce default MediaWiki URL structures out of the box. If some massaging is going to be done anyhow, I'd opt to build a system that make `ref`s easy, and tweak content being processed by Hugo.

BTW, the wiki included in GitHub projects is called [Gollum](https://github.com/gollum/gollum/), and it has a way to do [internal linking](https://github.com/gollum/gollum/wiki#linking-internal-pages). I've used Gollum (here and in GitLab), and the linking works really nice. It isn't the "link by title" that @rcoreilly requested, but it does "[s]upport wiki-style internal page links". ^_^

**Comment by bep** [comment] 2017-06-18 20:20
>Namespaces are nearly identical to "sections" in Hugo as they are used by site editors

I would not say that. 

* The only reason linking kind of works on Wikipedia is that it is, in practice, one big namespace. There are the "talk" namespace etc., but that is not part of the "daily article editing".
* Since MediaWiki is a server software, they can also suggest/autocomplete links.
* In Hugo, namespaces (i.e. sections) are very common, and the only way this is going to work is if the user does not have to think about these sections. 
* This should also follow "regular Github wiki syntax" to be of real value

But I think this issue is duplicate of another.

**Comment by maiki** [comment] 2017-06-18 20:37
> The only reason linking kind of works on Wikipedia is that it is, in practice, one big namespace. There are the "talk" namespace etc., but that is not part of the "daily article editing".

Namespaces don't change often on Wikipedia, but they are something that folks change in general MediaWiki usage, and for the same reasons as with Hugo: as a way to structure content.

**Comment by rcoreilly** [comment] 2017-06-19 03:42
The transition from a single big namespace has been a major issue in migrating from mediawiki to Hugo -- the ability to edit files locally using e.g., emacs (and see changes immediately on the local hugo server) is a major plus, but then it becomes more important to organize the files in subdirectories to avoid a single massive directory that is hard to manage.  Nevertheless, having the convenience of a single effective namespace based on titles seems like the "best of both worlds".  And if you want to be unambiguous, you can always have the option of using the file path as in the ref/relref.

Here's a possible spec for how it could work to address above questions:
* If the link has a / in it, then look for a filename, otherwise look for a page title
  + could have a param option to exclude title search if that seems important for some users -- in which case it works like ref/relref (except for the title text part)
  + if not found, render "link not found: `<the link>`" right on the page -- in general it seems like providing error feedback right on the page is better than in the server output -- that is where you're looking when you're editing.
  + if multiple matches, count the number of characters in common at start of file path for each found page vs. the current page path -- higher number wins (this will favor items in the same path -- similar to @bep's suggestion) -- if still a tie then pick the one with the *shortest* path, because you have now determined that the file is not within the same section, and thus the most general version should be chosen.
* Unless an explicit alternative text has been provided, use the page title for the link text.  I'm not sure what the @maki's question is about capitalizing?  The title is what the user has specified, and typically it seems like this will be a nice human-readable capitalized or whatever according to user's preference.  Note that even if you use the page path in the link, it will replace that with the page title, which seems like a big win over using ref/relref.
  + btw, I tried implementing some of this functionality myself using ref/relref in a shortcode, to massage the page path to discard the path and upper-case it, but I couldn't find any string functions exposed in the template language -- might be good to expose some of those so people can do some basic string manipulations within templates.
  + can expose this [[ ]] functionality as a template function too, e.g., titleref or something like that, and then if people want to manipulate the results they can.

**Comment by rcoreilly** [comment] 2017-06-19 19:40
BTW, I did manage to use the new `.Site.GetPage` functionality to write a shortcode "page.html" that takes the path as input and automatically uses the page title in the link, saving the double-typing but still requiring a lot more keystrokes than [[ ]] -- including this here in case anyone else looking for this functionality is interested in a stop-gap measure until the real thing is implemented :)

usage:
```markdown
{{< page "path/page" >}}
```
code for `page.html` -- put in layouts/shortcodes
```markdown
{{ $inlnk := .Get 0 }}{{ $pgfl := printf "%s.md" $inlnk }}{{ $pgtt := .Site.GetPage "page" $pgfl }}{{ if $pgtt }} <a href="{{ $pgtt.URL }}"> {{ $pgtt.Title }} </a>{{ else }}<a href="{{ .Site.BaseURL }}{{ $inlnk }}"> {{ $pgfl }} Not Found! </a>{{ end }}
```

Interestingly, it even works with just entering the page name without the full path -- I guess the getpage is robust that way, but probably doesn't have the advanced logic mentioned above.

Also please ignore comment about template functions for strings -- somehow I missed the key page in the docs about that!

**Comment by bep** [comment] 2017-06-19 20:01
> I guess the getpage is robust that way, but probably doesn't have the advanced logic mentioned above.

No, it is a "light version" the "tree logic" I was talkin about; the search order is

1) Exact match (i.e. path + filename)
2) Filename

**Comment by rcoreilly** [comment] 2017-12-07 06:17
I still think this would be a great and widely used feature, and should be relatively easy to implement, so please do keep the ticket open!

**Comment by idealhack** [comment] 2018-07-07 11:37
I would love to see this happen.

For myself, I use nvALT to take markdown notes and want to use Hugo for building the website.

**Comment by idealhack** [comment] 2019-01-21 06:31
I've written my site generator for this. But if Hugo can support both https://github.com/gohugoio/hugo/issues/3805 and this, I'll try to use it again.

**Comment by gagarine** [comment] 2019-02-06 23:57
We are planning to migrate http://baripedia.org mediawiki to hugo.  It's very important for us to have link on page title and not path.
The plan is to first migrate all page to md (and keep the history as separate commit). Then we will need to organize pages in folder, right now the wiki page do not use namespace and the organization is only done trough links.

That mean that if links are not on the page title, things are going to break badly. It's a blocker for us.

**Comment by TyberiusPrime** [comment] 2019-11-26 09:09
@rcoreilly  page shortcode works well for my use case.

Now all I'd need is to stick a regexps at the right location to rewrite [[xyz]] to {{<page "xyz>"}} and have it processed. Unfortunatly, sticking it in ```{{- .Content -}}``` as ```{{- .Content | replaceRE ...-}}``` appears to be too late.

Can anybody point me in the right direction?
Thanks!

**Comment by tcgriffith** [comment] 2019-11-26 12:50
My workaround:

https://discourse.gohugo.io/t/my-tips-to-turn-a-github-wiki-into-hugo-website/21217

**Comment by crisrojas** [comment] 2020-05-26 15:19
> My workaround:
> 
> https://discourse.gohugo.io/t/my-tips-to-turn-a-github-wiki-into-hugo-website/21217

Using your Perl regex and with the hints providen by a [good reddit citizen](https://www.reddit.com/r/gohugo/comments/gqak1j/transform_wikilinks_in_markdown/) I've come with this solution:

```
{{ .Content | replaceRE "\\\\\[\\\\\[(\[\^/\]+)\\\\\]\\\\\]" "<a href=\\"${1}.html\\">$1</a>" |safeHTML }} ```
It works really well for me.

NOTE: Since I wanted to port my zettelkästen note system to hugo, I use a date convention to name my files, so every file has a name like "20200526171227" and therefore every wikilink takes this form [[20200526171250]], so my guess is that the above regex won't work with wikilinks having spaces [[like this]]

**Comment by bep** [comment] 2020-05-26 18:52
You may get somewhere with this using render hooks: https://portable-hugo-links.netlify.app/

**Comment by b4D8** [comment] 2021-01-05 23:01
@bep Maybe we could use this [Goldmark wikilink plugin](https://github.com/13rac1/goldmark-wikilink)?

**Comment by StefanoCecere** [comment] 2021-03-30 23:32
> You may get somewhere with this using render hooks: https://portable-hugo-links.netlify.app/

@bep this could be a life changer for anybody using Obsidian as content editor (which autoupdates all links)
it works or with [[note-title]] wiki like links or with these standard md syntaxt

do you think we could have this render hook method integrated into Hugo?

**Comment by RoyiAvital** [comment] 2021-05-17 17:54
The important feature of a Wiki Link is the back link (Namely automatically add a link to the linking page ad the linked page).
Could that be done as well?
It will make a lot of sense in web sites which are a set of notes of the user.

**Comment by crisrojas** [comment] 2021-05-17 19:42
> The important feature of a Wiki Link is the back link (Namely automatically add a link to the linking page ad the linked page).
> Could that be done as well?
> It will make a lot of sense in web sites which are a set of notes of the user.

Here is a basic regex implementation of wikilinks + backlinks:

- https://github.com/crisrojas/Zettels/blob/master/layouts/partials/content.html
- https://github.com/crisrojas/Zettels/blob/master/layouts/partials/backlinks.html

**Comment by RoyiAvital** [comment] 2021-05-17 19:57
@crisrojas , Is there a discussion on your template on the forum?

**Comment by crisrojas** [comment] 2021-05-17 20:00
@RoyiAvital no that I know 🤔

**Comment by RoyiAvital** [comment] 2021-05-17 20:05
You should open a discussion at the forum of Hugo. You will get more exposure and collaborators.

**Comment by crisrojas** [comment] 2021-05-18 16:39
@RoyiAvital I will do it, thanks 👍

**Comment by milafrerichs** [comment] 2021-11-27 11:56
@bep would you be open to a PR that includes the extension: 
https://github.com/abhinav/goldmark-wikilink

This specific one is linked from the main goldmark extensions list: https://github.com/yuin/goldmark/#extensions

Similar to the other extensions one can configure in the config?
https://github.com/gohugoio/hugo/blob/7a15edafe240471c072d3548b72ccda0271ffd8f/markup/goldmark/convert.go#L135-L137

**Comment by jaded0** [comment] 2022-06-07 23:16
What's the status on all this?

**Comment by dgasparri** [comment] 2022-06-14 08:11
I'm working on a possible solution. 

1. Render-link hooks are not invoked on links in the form \[\[Wikilink]].
2. There is a Goldmark extension that does that
3. Shortcodes are not activated and it is not possible to define a custom shortcode opening \[\[

Easiest path is to import the Goldmark extension, but I don't believe that is the correct way to go: wikilinks must resolve a file/link path and must work with the internal structure of the site, and a Markdown renderer shouldn't be involved in that.

I was considering:

1. create a render-internallink hook
2. create a shortcode "hook"

REF, RELREF and \[\[ are closely related, I believe the best way is to create a shortcode hook so that the implementation of REF and \[\[ can follow the same path (a INTERNALREF shortcode, and the format \[\[ is its alias).

The idea is to insert a `if strings.Contains(contentToRender, "[[")` in hugolib/page__per_output.go *before* it is checked for shortcodes (now on row 387) and to transform that into a proper link in the format \[]\({{< relref/internalrelref .... >}}).

TODO: check if REF and internal link are supposed to behave the same - if yes, then transform it into a REF (RELREF?), otherwise create a shortcode for internal links 

I believe this solution is also the easiest to maintain and test, because all the issues with the link/url resolution are in a shortcode and not in the page parser.

Please let me know if you have other ideas or see drawbacks from this approach (I'm writing my notes [here](https://gasparri.org/2022-06-10-hugo-wikilinks/) as I work on the issue)

**Comment by dgasparri** [comment] 2022-06-15 18:31
Was bigger than expected because none of my original ideas worked. 

Lexer now handles:

> // internal links
> tLeftDelimInternalLink
> tRightDelimInternalLink
> tInternalLinkLabel
> tInternalLinkLink
> tInternalLinkLinkLabel

and it creates a shortcode RELREF for the link

**Comment by ryanwwest** [comment] 2023-01-10 23:47
It's great that [the PR](https://github.com/gohugoio/hugo/pull/10019) exists, but I don't see any discussion there and see 71 other open PRs as well... so I'm not sure if/when this will get added. https://github.com/milafrerichs/hugo-wikilinks could possibly work for now instead, I need to check it out.

**Comment by modeckimellett** [comment] 2023-05-20 11:57
I started a fresh discussion for this on Discourse here: https://discourse.gohugo.io/t/wiki-style-links-followup/44444

At least based on the first response, there is concern that consensus has not been reached on what the behavior of this feature should be. I have included responses to the questions posed in that thread. If you have an interest in this feature please check the Discourse and respond to that thread with your thoughts. Once consensus is reached on the exact behavior of this feature we can update this issue with that information.

**Comment by bep** [comment] 2023-05-20 17:20
Hugo has moved a little since this topic was created. We have more or less standardised on the CommonMark (via Goldmark) with some extensions:

* Shortcodes
* Markdown attributes
* Render hooks

What I don't think we want to do is to introduce new Markdown syntax, e.g. `[[Page Title]]`. One reason is the added complexity, but most importantly: It makes the Markdown incredibly unportable (when viewed on GitHub etc.).

I have created a vaguely related proposal at https://github.com/gohugoio/hugo/issues/10957

That discusses using plain Markdown links in combination with render hooks. I would rather spend my time on making effective ways to _find pages_ behind the scenes than creating complex Markdown parsers ...

So, instead of:

```markdown
[[Page Title]]
```

You would write:

```
[Page Title]](wikilink)
```

Or something. Which with some trickery should work as is even today.

**Comment by modeckimellett** [comment] 2023-05-20 18:26
Thank you for your prompt response @bep I must admit that I'm disappointed but at least the intention is now clear.

With this feedback in mind, can we close this issue as well as https://github.com/gohugoio/hugo/pull/10019 to get things cleaned up?

**Closed** 2023-05-23 13:36 UTC
Labels: Enhancement, Keep
