### ISSUE TITLE
Server doesn't always ignore files to be ignored.

### ISSUE THREAD

**Issue by sciurius** [gohugoio/hugo#7345] opened 2020-06-01 17:07 UTC
Even though there is code in function handleEvents (commands/hugo.go, line 998) to ignore files that start with `.#` and `#` there seem to be situations where files like these are processed nevertheless.

See https://discourse.gohugo.io/t/live-preview-rebuild-failed/25924/12 post #11.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.71.1-A301F6B2/extended linux/amd64 BuildDate: 2020-05-25T09:18:12Z
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by jmooring** [comment] 2020-06-21 08:00
Might be fixed by https://github.com/gohugoio/hugo/pull/6774

**Comment by obar** [comment] 2020-06-22 04:46
Thanks for the tip on this bug report @jmooring.

@sciurius: since hugo is a go project, it's fairly painless to build it yourself with this bug fixed. The first thing to do is [install go](https://golang.org/doc/install#install). Then it's just a matter of merging the latest hugo source with the patch. Create the `~/go/src` path if needed.

```
cd ~/go/src
git clone --shallow-since 2020/01/18 https://github.com/gohugoio/hugo.git
cd hugo
git remote add obar http://github.com/obar/hugo.git
git fetch obar -b ignore-lockfiles --depth 2
git merge obar/ignore-lockfiles
```

At this point, put in an unexciting merge commit. You can 'save' on the editor that pops up and that's enough. Then:

```
go install --tags extended
```

(The `--tags extended` bit is optional but I would recommend it)

Add `HOME/go/bin` to your `PATH` so the hugo executable will work.

Let me know if this works for you!

**Comment by sciurius** [comment] 2020-06-22 14:29
@obar Thanks for the detailed instructions. I took the liberty of taking a different route :smile::

I extracted your ignore-lockfiles patch and applied it to the git head. Builds okay and it seems to have cured the problem. Hurray!

BTW: `git fetch obar -b ignore-lockfiles --depth 2` barfs on the `-b` option.

**Comment by obar** [comment] 2020-06-22 16:34
I gave you long winded instructions to basically do that :) Glad it works! If you wouldn't mind confirming your experience on the pull request, maybe that would be helpful when it eventually gets reviewed.

**Comment by sciurius** [comment] 2020-06-22 16:48
Good suggestion. Done.

**Comment by JonathanDoughty** [comment] 2021-03-21 00:47
Still happens with hugo v0.81.0+extended darwin/amd64
Admittedly the stale emacs file was left over after a panic and the discourse discussion led to eventual enlightenment but ...

**Comment by moorereason** [comment] 2021-04-05 19:04
Closing as dupe of #6773.

**Closed by moorereason** 2021-04-05 19:04 UTC
