### ISSUE TITLE
`<!--more-->` divider behaves differently for html and markdown content

### ISSUE THREAD

**Issue by FelixBenning** [gohugoio/hugo#9413] opened 2022-01-22 12:45 UTC
I tried to write my first html content page today and realized that the content above `<!--more-->` is removed from the page. It is only displayed in the article list. This is not how the divider works for Markdown content where the content before `<!--more-->` is retained in the article as well. So I think this is a bug. Although it might be a bug of the theme (https://github.com/dsrkafuu/hugo-theme-fuji/)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.92.0-B3549403+extended windows/amd64 BuildDate=2022-01-12T08:23:18Z VendorInfo=gohugoio
</pre>

**Comment by davidsneighbour** [comment] 2022-01-22 12:51
Can you maybe add a sample of your code? The `<!--more-->` tag is heavily influenced by the availability of a `summary` frontmatter and this might be the case here.

https://gohugo.io/content-management/summaries/#summary-selection-order

**Comment by FelixBenning** [comment] 2022-01-22 12:57
sure, this is the file (two summaries to get one in the end), and this is the result: https://www.unassuming.page/blog/tools/bayes-helper/ (not pretty but it was my first attempt at interactivity 🤷 )

```html
---
title: Bayes Helper
date: "2022-01-22"
tags: [maths, tools, health]
---

If you use a test with 95% sensitivity and 95% specificity, and it is positive
then you are surly more likely sick than not, right? Well, ... it depends.
On the prior probability to be sick (or incidence rate) to be precise. And
humans are really bad assessing the meaning of a test result.

<!--more-->

If you use a test with 95% sensitivity and 95% specificity, and it is positive
then you are surly more likely sick than not, right? Well, ... it depends.
On the prior probability to be sick (or incidence rate) to be precise. And
humans are really bad assessing the meaning of a test result.

Here is a bayes calculator to make this easer:


<form id="bayes-form">
	<label for="incidence">Incidence Rate</label>
	<input type="number", id="incidence", name="incidence", min="0", max="100000", step="1", placeholder="per 100 000", required> 
	<br>
	<label for="sensitivity">Sensitivity</label>
	<input type="number", id="sensitivity", name="sensitivity", min="0", max="100", step=".01", placeholder="in percent", required> 
	<br>
	<label for="specificity">Specificity</label>
	<input type="number", id="specificity", name="specificity", min="0", max="100", step=".01", placeholder="in percent", required> 
	<br>
	<label for="test_positive">Test positive?</label>
	<input type="checkbox", id="test_positive", name="test_positive"> 
	<br>
	<label for="posterior" >Likelihood to be infected:</label>
	<output id="posterior" name="posterior">Input not Valid</output>
</form>

<script>
	function _calculatePosterior(prior, sensitivity, specificity, test_positive) {
		const p_test_given_pos = test_positive ? sensitivity : 1-sensitivity
		if (prior==0 || p_test_given_pos == 0){
			return 0
		}
		const p_test_given_neg = test_positive ? 1-specificity : specificity
		return 1/(1+ p_test_given_neg*(1-prior)/(p_test_given_pos*prior))
	}

	function calculatePosterior() {
		this.posterior.value = _calculatePosterior(
			this.incidence.value/100000.0,
			this.sensitivity.value/100.0,
			this.specificity.value/100.0,
			this.test_positive.checked
		) *100 + "%";
	}
	document.getElementById("bayes-form").oninput = calculatePosterior

	function add_wasModified() {
		this.classList.add("wasModified");
	}

	for (const input of document.getElementsByTagName("input")) {
		input.oninput = add_wasModified;
	}
</script>
```

**Comment by ptgott** [comment] 2022-01-22 15:28
I am looking into issue https://github.com/gohugoio/hugo/issues/6513, and I'm pretty sure these two issues have the same cause. I should have a PR up this weekend.

**Comment by jmooring** [comment] 2022-01-22 15:33
This is a duplicate of https://github.com/gohugoio/hugo/issues/6686.

**Closed** 2022-01-22 15:36 UTC
Labels: Bug, Duplicate
