### ISSUE TITLE
In nested range the map key and value become are inverted.

### ISSUE THREAD

**Issue by zhengchun** [gohugoio/hugo#11112] opened 2023-06-14 19:18 UTC
I upgraded my hugo from v0.99 to v0.113 yesterday, I get a strange output from `range $key, $value = range .` , the value of  **$key** is output as **$value**, and the value of **$value** is output as **$key**.

The full source code from [https://github.com/fastbootstrap/atlassian-design-for-bootstrap/blob/main/site/layouts/shortcodes/class-api.html](https://github.com/fastbootstrap/atlassian-design-for-bootstrap/blob/main/site/layouts/shortcodes/class-api.html)

```html
      {{ range index .Site.Data.css $module }}
        {{ $properties := .property }}
        {{ $values := .values }}
        {{ $prefix := .class | default .property }}
        {{ $format := .format | default "%s-%s" }}
        {{ range $values }}
          {{ $key := . }}
          {{ $value := . }}
          {{ if reflect.IsMap . }}
            {{ range $key, $value = . }}  **WARNING: here, key and value is inverted **
            {{ end }}
          {{ end }}
          {{ $class :=trim (printf $format $prefix (string $key)) "-" }}
          {{ $styles := slice }}
          {{ range split $properties " " }}
            {{ $property := trim . "" }}
            {{ $styles = $styles | append ( printf "%s: %s;" $property (string $value)) }}
          {{ end }}
          <tr>
            <td class="text-blue-400 text-nowrap"><code>{{ printf ".%s" $class }}</code></td>
            <td class="text-purple-300">{{ delimit $styles "<br/>" }}</td>           
          </tr>
        {{ end }}
      {{ end }}
```

The warning output from `{{ range $key, $value = . }}`
```
          {{ if reflect.IsMap . }}
            {{ range $key, $value = . }}  **WARNING: here, key and value are inverted **
            {{ end }}
          {{ end }}
```

The normal output from Hugo v0.99

| Class | Property |
| ------------- |:-------------:|
|.border-0	| border-width: 0; |
|.border-1	| border-width: 1px; |
|.border-2	| border-width: 2px; |
|.border-3	| border-width: 3px; |
|.border-4	| border-width: 4px; |
|.border-5	| border-width: 5px; |

Since upgrade to Hugo v0.113, The output value key become value, value become key.

| Class        | Property           |
| ------------- |:-------------:|
| .border-0	| border-width: 0; |
| .border-1px	| border-width: 1; |
| .border-2px	| border-width: 2; |
| .border-3px	| border-width: 3; |
| .border-4px	| border-width: 4; |
| .border-5px	| border-width: 5; |

Data from [https://github.com/fastbootstrap/atlassian-design-for-bootstrap/blob/main/site/data/css.yml](https://github.com/fastbootstrap/atlassian-design-for-bootstrap/blob/main/site/data/css.yml)

```yml
border-width:
  - property: border-width
    class: border
    values:
      - 0
      - 1: 1px
      - 2: 2px
      - 3: 3px
      - 4: 4px
      - 5: 5px
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.113.0-085c1b3d614e23d218ebf9daad909deaa2390c9a+extended windows/amd64 BuildDate=2023-06-05T15:04:51Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by bep** [comment] 2023-06-14 19:28
I have not looked closely at your templates, but this issue rings a bell:

https://github.com/golang/go/issues/56490

**Comment by jmooring** [comment] 2023-06-14 19:57
The problem was introduced in [v0.106.0](https://github.com/gohugoio/hugo/releases/tag/v0.106.0), where we merged the changes from https://github.com/golang/go/commit/be7068fb0804f661515c678bee9224b90b32869a. So, upstream fixed one thing but broke another.

**Comment by jmooring** [comment] 2023-06-14 21:46
To reproduce:

```
{{ $m := dict "key" "value" }}
{{ $k := "" }}
{{ $v := "" }}
{{ range $k, $v = $m }}
  {{ $k }} = {{ $v }}
{{ end }}
```

Produces:

```
value = key
```

**Comment by jmooring** [comment] 2023-06-14 22:13
See upstream <https://github.com/golang/go/issues/60801>

**Comment by bep** [comment] 2023-06-15 06:37
@jmooring that's a pretty bad bug ... I'm guessing they will merge that one fast, so I will hold on with any release until I can get that one into Hugo.

**Comment by jmooring** [comment] 2023-06-15 14:39
<https://github.com/golang/go/commit/befec5ddbbfbd81ec84e74e15a38044d67f8785b>

**Closed** 2023-06-15 21:04 UTC
Labels: Bug, Upstream
