### ISSUE TITLE
Wrong menu items order with accentuated characters

### ISSUE THREAD

**Issue by inwardmovement** [gohugoio/hugo#6947] opened 2020-02-23 17:44 UTC
`Hugo Static Site Generator v0.65.3/extended windows/amd64 BuildDate: unknown`

For example, `É` is ordered after `Z` instead of being ordered after `E`.

**Comment by sams96** [comment] 2020-03-03 18:47
This is a duplicate of #2180

**Closed** 2020-03-03 18:50 UTC
Labels: Duplicate
