### ISSUE TITLE
 hugo --minify strips out IE conditional statements

### ISSUE THREAD

**Issue by coliff** [gohugoio/hugo#5089] opened 2018-08-17 11:41 UTC
I've just upgraded to Hugo v0.47 Extended (Windows 64-bit).

When I run `hugo --minify` the HTML output strips the IE conditional statements I had.
```
  <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/g/html5shiv@3.7.3,respond@1.4.2"></script>
    <![endif]-->
```
The conditional statements are not stripped using `hugo serve` or making an unminified build with `hugo`.

**Comment by jhabdas** [comment] 2018-08-17 12:38
FYI H5BP is still showing a browser upgrade message for `lte` ie9. [According to](http://gs.statcounter.com/browser-version-market-share) stats counter IE 11 currently has 2.59 of the ~3% global market share. IE 11 does not support conditional comments.

**Comment by moorereason** [comment] 2018-08-17 14:34
FYI: Upstream says this is the intended behavior and won't be supported: https://github.com/tdewolff/minify/issues/133

Work-around is to solve it in Javascript.

**Closed** 2018-08-18 09:16 UTC
Labels: Bug
