### ISSUE TITLE
Draft _index.md gives "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by JVimes** [gohugoio/hugo#11441] opened 2023-09-10 02:01 UTC
### What version of Hugo are you using?

<pre>
hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended windows/amd64 BuildDate=2023-08-31T11:23:51Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

## Summary

When I use a `draft` _index.md at the root level I get:

> invalid memory address or nil pointer dereference

The error goes away if I change `draft` to false for _index.md.

## Repro

```shell
hugo new site foo
cd foo
git init
git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke
echo "theme = 'ananke'" >> hugo.toml
hugo new _index.md
hugo server
```

Final output:

```
Error: error building site:
render: render of "404" failed: "C:\foo\themes\ananke\layouts\404.html:1:24":
execute of template failed: template: 404.html:1:24:
executing "header" at <partial "page-header.html" .>:
error calling partial: "C:\foo\themes\ananke\layouts\partials\page-header.html:22:9":
execute of template failed: template: partials/page-header.html:22:9:
executing "partials/page-header.html" at <partial "site-navigation.html" .>:
error calling partial: "C:\foo\themes\ananke\layouts\partials\site-navigation.html:3:21":
execute of template failed: template: partials/site-navigation.html:3:21:
executing "partials/site-navigation.html" at <.Site.Home.RelPermalink>:
error calling RelPermalink:
runtime error: invalid memory address or nil pointer dereference
```

### Other themes

Same error from different file/lines.

PaperMod:
```
Error: error building site:
render: render of "404" failed: "C:\foo\themes\PaperMod\layouts\_default\baseof.html:16:8":
execute of template failed: template: 404.html:16:8:
executing "404.html" at <partialCached "header.html" . .Page>:
error calling partialCached: "C:\foo\themes\PaperMod\layouts\partials\header.html:101:29":
execute of template failed: template: partials/header.html:101:29:
executing "partials/header.html" at <site.Home.AllTranslations>:
error calling AllTranslations:
runtime error: invalid memory address or nil pointer dereference
```

Blowfish:
```
Error: error building site: render: render of "404" failed: "C:\foo\themes\Blowfish\layouts\_default\baseof.html:20:5":
execute of template failed: template: 404.html:20:5:
executing "404.html" at <partial $header .>:
error calling partial: "C:\foo\themes\Blowfish\layouts\partials\header\basic.html:21:30":
execute of template failed: template: partials/header/basic.html:21:30:
executing "partials/header/basic.html" at <markdownify>:
error calling markdownify: runtime error: invalid memory address or nil pointer dereference
```

**Comment by jmooring** [comment] 2023-09-10 02:55
When a page is in draft mode, it does not exist. So in your case, the home page (`_index.md`) does not exist. Which means that the `.Site.Home` object does not exist.

- Ananke calls the `.Site.Home` object directly
- PaperMod: calls `site.Home` which returns `.Site.Home`
- Blowfish: calls the `markdownify` function, which is aliased to `.Site.Home.RenderString`

The short answer is, "Don't do that." Perhaps we should just ignore the `draft` setting on the home page.

**Comment by JVimes** [comment] 2023-09-10 04:16
Thanks. A memory error isn't an appropriate way to handle it. Draft is conceptually valid for the home page. I want to use it while I work on the home page text.

**Comment by jmooring** [comment] 2023-09-10 05:07
> A memory error isn't an appropriate way to handle it. 

I agree this could be better, but what you've done is uncommon.

> Draft is conceptually valid for the home page.

If draft is true on the home page, none of the content is published. So conceptually, the only way it makes sense to keep the home page in draft mode is if you are running `hugo --buildDrafts` or `hugo server --buildDrafts`, which works fine.

**Comment by JVimes** [comment] 2023-09-10 15:28
Well, that's not entirely true. My home page is the Recent Articles section. The index file is for a bit of marketing text at the top, I'm working on.

**Comment by jmooring** [comment] 2024-01-18 04:11
Closing as duplicate of #11809.

**Closed by jmooring** 2024-01-18 04:11 UTC
Labels: Bug
