### ISSUE TITLE
Add `minify` configuration

### ISSUE THREAD

**Issue by Jos512** [gohugoio/hugo#5424] opened 2018-11-09 06:52 UTC
Since both `hugo` and `hugo server` accept the `--minify`  flag, would it be an idea to add a configuration option for this feature? 

That way we can enable (or disable) minification in `config.toml` instead of typing it in the command line every time.

----

With `Hugo Static Site Generator v0.51/extended windows/amd64 BuildDate: unknown` the `minify` option in the `config.toml` file does nothing.

**Comment by carlmjohnson** [comment] 2018-11-12 21:15
Dupe of #5142.

**Closed** 2018-11-12 22:29 UTC
Labels: Duplicate, Enhancement

**Comment by Jos512** [comment] 2018-12-10 15:52
It's indeed a duplicate, my apologies for that. If I looked better I'd have found that other one.

But why I respond here is that I think the 0.53 milestone should be removed from this issue. It now looks like this issue gets closed with Hugo 0.53, but that's not the case since the other issue is still open. :slightly_smiling_face:
