### ISSUE TITLE
[permalinks] ignored for capitalized folders / sections

### ISSUE THREAD

**Issue by cvladan** [gohugoio/hugo#8302] opened 2021-03-05 11:01 UTC
> reproduced on: hugo v0.81.0+extended linux/amd64 BuildDate=unknown  
... and that should be latest release

#### Permalinks ignored

It took me a while to figure it out, but `[permalinks]` line is ignored when section name is Title case capitalized.
For example, my folder structure is

```
/content/Projects
```

and my `permalinks.yaml`:
```
projects = ":sections/dummy/:title"
```

This should, but **it doesn't work**

#### Rename folder as only working solution?

When I rename folder to `/content/projects` to lowercase, it **starts working again**. If I leave folder to `Projects` and change accordingly in `permalinks.yaml` to `Projects = ...` or just leave it lowercase - in any case it **doesn't work**.

The only way to make it work is to **rename a folder to lowercase**, but this is the only solution that is not acceptable to me as I have a lot of folders with very descriptive title sentences.

> I've experimented with `disablePathToLower` with no luck

**Comment by bep** [comment] 2021-03-05 18:59
So,

* Hugo's "file system" is case insensitive
* We should support upper case folders vs permalink config (not sure what happens there)
* However, since we at some point throw away the case info, you might as well make it lowercase and put the title info into front matter

**Comment by cvladan** [comment] 2021-03-05 19:30
Yes, right now I've renamed the folder to lowercase and everything is working as expected again.

It was quite hard to detect this problem as it's not obvious to look for a bug in that direction. For me, it was more than two hours trying everything before stumbling on this solution. In the process, I tried all TOML/YAML/JSON, configuration like `disablePathToLower` and looking if there is some other configuration directive, etc.

**Comment by jmooring** [comment] 2023-05-20 05:18
Closing as duplicate of #10095.

**Closed by jmooring** 2023-05-20 05:18 UTC
Labels: Bug, NeedsInvestigation

**Comment by cvladan** [comment] 2023-06-08 00:32
To be honest, I've already decided that as soon as I find the time, I'm going to switch to Astro. I see that a lot of work is being done on Hugo, but the fact that it takes as many as 30 versions (112-81) and 2 years to fix such a fundamental bug is troubling.

Moreover, it was an incredibly easy bug to reproduce and it seems to me that it wasn't even taken seriously, rather they waited for someone else to report it again. Actually, it seems as if it was just left forgotten.
