### ISSUE TITLE
markdownify doesn't respect custom render hooks

### ISSUE THREAD

**Issue by janoszen** [gohugoio/hugo#8669] opened 2021-06-19 11:29 UTC
When using `markdownify` in a template it does not use the markup rendering hooks (e.g. `render-link.html`), whereas in normal content it does.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.1-5AFE0A57+extended windows/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio 
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment] 2021-06-19 14:31
Use `.RenderString` instead of `markdownify`.

<https://gohugo.io/functions/markdownify>

> Note: if you need Render Hooks, which markdownify doesn’t currently support, use .RenderString instead.

<https://gohugo.io/functions/renderstring>

> Note that this method is more powerful than the similar markdownify function as it also supports Render Hooks and it has options to render other markup formats.

Duplicate of #6650.

**Closed by jmooring** 2021-06-19 14:31 UTC
Labels: Duplicate
