### ISSUE TITLE
panic when hugo starts

### ISSUE THREAD

**Issue by maxtar** [gohugoio/hugo#9988] opened 2022-06-07 16:14 UTC
### What version of Hugo are you using (`hugo version`)?

hugo v0.100.1-0afb4866e345d31cbbcbab4349e43f1d36122806+extended windows/amd64 BuildDate=2022-06-01T10:11:48Z VendorInfo=gohugoio

### Does this issue reproduce with the latest release?

Yes, this is the latest release.

I had one if previous releases (91 or 96 don't remember) today i;ve download v0.100.1 version. When I trying run `hugo` or `hugo serve` I got the following panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x16c9c31]

goroutine 1 [running]:
github.com/gohugoio/hugo/helpers.NewContentSpec({0x309f680, 0xc0006a0400}, {0x30a0958, 0xc0001f95f0}, {0x309e660, 0xc000297ce0}, 0xc0001a8780)
        /root/project/hugo/helpers/content.go:87 +0x291
github.com/gohugoio/hugo/deps.New({{0x30a0958, 0xc0001f95f0}, 0xc000885960, 0xc0006a0400, {0x0, 0x0}, {0x309f570, 0xc000096460}, {0xc0006af000, 0x22, ...}, ...})
        /root/project/hugo/deps/deps.go:260 +0x4b7
github.com/gohugoio/hugo/hugolib.configLoader.applyDeps({{0x0, 0x0}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}}, ...)  
        /root/project/hugo/hugolib/hugo_sites.go:519 +0x31e
github.com/gohugoio/hugo/hugolib.newHugoSites({{0x30a0958, 0xc0001f95f0}, 0xc000885960, 0x0, {0x0, 0x0}, {0x309f570, 0xc000096460}, {0x0, 0x0, ...}, ...}, ...)
        /root/project/hugo/hugolib/hugo_sites.go:406 +0x766
github.com/gohugoio/hugo/hugolib.NewHugoSites({{0x30a0958, 0xc0001f95f0}, 0xc000885960, 0x0, {0x0, 0x0}, {0x309f570, 0xc000096460}, {0x0, 0x0, ...}, ...})
        /root/project/hugo/hugolib/hugo_sites.go:555 +0x158
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig.func3()
        /root/project/hugo/commands/commandeer.go:496 +0x838
sync.(*Once).doSlow(0xc000096460?, 0x2ac8ec7?)
        /usr/local/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc000281590)
        /root/project/hugo/commands/commandeer.go:422 +0xa19
github.com/gohugoio/hugo/commands.newCommandeer(0x1, 0x1, 0x1, 0xc0002813b0, {0x3088a60?, 0xc00004c380}, 0xc0002962a0, {0x0, 0x0, 0x0})
        /root/project/hugo/commands/commandeer.go:226 +0x310
github.com/gohugoio/hugo/commands.initializeConfig(0x0?, 0x0?, 0x0?, 0x2a99239?, {0x3088a60?, 0xc00004c380?}, 0x1d8?)
        /root/project/hugo/commands/hugo.go:125 +0x31
github.com/gohugoio/hugo/commands.(*serverCmd).server(0xc00004c380, 0xc00063d180, {0xc0001e0500?, 0xee0380?, 0xc00093fd00?})       
        /root/project/hugo/commands/server.go:257 +0x1cd
github.com/gohugoio/hugo/commands.(*commandsBuilder).newServerCmdSignaled.func1(0xc00063d180?, {0x3ff9568?, 0x0?, 0x0?})
        /root/project/hugo/commands/server.go:96 +0x36
github.com/spf13/cobra.(*Command).execute(0xc00063d180, {0x3ff9568, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0008a0f00)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/gohugoio/hugo/commands.Execute({0xc0000a63b0, 0x1, 0x1})
        /root/project/hugo/commands/hugo.go:92 +0xb4
main.main()
        /root/project/hugo/main.go:23 +0x57
```

**Comment by bep** [comment] 2022-06-07 16:18
Duplicate of #9968

**Closed by bep** 2022-06-07 16:18 UTC
Labels: Bug, NeedsTriage
