### ISSUE TITLE
Create a new post in the other languages' directory

### ISSUE THREAD

**Issue by whatacold** [gohugoio/hugo#8768] opened 2021-07-16 14:29 UTC
Hi,

I use the multilingual mode of Hugo, which has below language settings:
```toml
DefaultContentLanguage = "en"
hasCJKLanguage = true

[languages]
  [languages.en]
    contentDir = "content/en"
    weight = 1
  [languages.zh-cn]
    contentDir = "content/zh-cn"
    weight = 2
```

But it seems there is no way to create a new post in the `zh-cn` subdir.
For example, I tried to new a post by `hugo new -c zh-cn t1.org`, but it didn't work.

My Hugo version is v0.80.0, and the blog is at https://whatacold.io/

**Comment by pamubay** [comment] 2021-07-17 04:04
Try
```
hugo new content/zh-cn t1.org
```

**Comment by whatacold** [comment] 2021-07-17 04:27
Thanks @pamubay ,

But it doesn't work on my side:
```
$ hugo new content/zh-cn t1.org
Error: content/zh-cn already exists
```

**Comment by pamubay** [comment] 2021-07-17 04:41
whoops, sorry, i mean 

```
hugo new content/zh-cn/t1.org
```

**Comment by whatacold** [comment] 2021-07-17 07:17
Ah, that works! Thank you so much!

The prefix `content/` makes a big difference here, with `content/`:
```
hugo new content/zh-cn/blog/t1.org
content/zh-cn/blog/t1.org created
```

vs. without `content/`:
```
$ hugo new zh-cn/blog/t1.org 
/path/to/hugo-root/content/en/zh-cn/blog/t1.org created
```

**Comment by whatacold** [comment] 2021-07-17 09:43
Oops, if I use the same `hugo new content/blog/t1.org ` in a "single language" site, Hugo creates the file path under the top-level `content` directory:
```
$ hugo new content/blog/t1.org 
/tmp/hello-world/content/content/blog/t1.org created  # note that it has two 'content' directories here
```

Hope that there is a consistent way to archieve that.

**Comment by jmooring** [comment] 2021-11-22 16:23
@whatacold 

> If I use the same hugo new content/blog/t1.org in a "single language" site, Hugo creates the file path under the top-level content directory:

I cannot reproduce this with v0.89.4. Can we close this issue?

**Closed** 2021-11-22 16:26 UTC
Labels: Proposal
