### ISSUE TITLE
Instagram Shortcode broken getJSON failure

### ISSUE THREAD

**Issue by tfolbrecht** [gohugoio/hugo#5659] opened 2019-01-31 15:35 UTC
The Instagram Shortcode isn't working, getJSON error even though the addresses are valid and able to be fetched with my browser

Probably related to https://github.com/gohugoio/hugo/issues/5643#issue-403564640

I'll try looking into it and writing a build test. (I'm a noob)

![screenshot from 2019-01-31 10-24-12](https://user-images.githubusercontent.com/6099765/52064881-7a83b800-2543-11e9-8162-82b4bca7c148.png)
![screenshot from 2019-01-31 10-24-59](https://user-images.githubusercontent.com/6099765/52064817-5de78000-2543-11e9-9718-986c7707f897.png)

**Comment by bep** [comment] 2019-02-01 08:57
I have merged #5643 -- and I cannot reproduce this particular issue -- the instagram examples on the docs site works fine (I have cleared the cache).

**Comment by pawelgrzybek** [comment] 2019-02-01 10:13
I am having similar issue with `tweet` shortcode.

```
Building sites … ERROR 2019/02/01 10:12:24 "/Users/pgrzybek/Sites/pawelgrzybek.com/content/posts/2018-06-30-top-picks-2018-june.md:15:1": failed to render shortcode "tweet": failed to process shortcode: template: _internal/shortcodes/tweet.html:7:13: executing "_internal/shortcodes/tweet.html" at <getJSON $url>: error calling getJSON: failed to get getJSON resource "https://api.twitter.com/1/statuses/oembed.json?id=1003623284829638659&dnt=false": Get https://api.twitter.com/1/statuses/oembed.json?id=1003623284829638659&dnt=false: x509: certificate signed by unknown authority
```

![screenshot 2019-02-01 at 10 11 12](https://user-images.githubusercontent.com/3697104/52116780-f21c1a80-2609-11e9-93d1-d9dd5f4e4d07.jpg)

It happened to me after update from v50 to v53.

**Comment by pawelgrzybek** [comment] 2019-02-02 07:16
I can confirm that version. 0.54 fixed my issues.

**Comment by pawelgrzybek** [comment] 2019-02-02 07:16
Thank you a lot for rapid action @bep

**Closed** 2019-02-04 14:40 UTC
Labels: NeedsUserFeedback
