### ISSUE TITLE
`0.56.x` breaks quickstart

### ISSUE THREAD

**Issue by toadjaune** [gohugoio/hugo#6191] opened 2019-08-10 11:58 UTC
Hi everybody !

I just tried to start a new website, following the instructions at https://gohugo.io/getting-started/quick-start/

```bash
$ hugo new site quickstart
$ cd quickstart
$ git init
$ git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
$ echo 'theme = "ananke"' >> config.toml
# Works fine until here
$ hugo new posts/my-first-post.md
Error: failed to read module config for "ananke" in "/tmp/tmp.XfdiUP8a9j/quickstart/themes/ananke/theme.toml": unmarshal failed: Near line 11 (last key parsed 'min_version'): Invalid float value: "0.30.2"
```
I've tried to reproduce the issue with several versions of hugo, here are my findings :
* Broken versions : 
```
Hugo Static Site Generator v0.56.0-45F4EB98 linux/amd64 BuildDate: 2019-07-25T16:38:06Z
Hugo Static Site Generator v0.56.3-F637A1EA linux/amd64 BuildDate: 2019-07-31T12:51:09Z
```
* Working version : 
```
Hugo Static Site Generator v0.55.6-A5D4C82D linux/amd64 BuildDate: 2019-05-18T07:56:30Z
```
I don't currently have a working go toolchain, so I'm not in a position to do proper bisecting at the moment.

Some extra system info : 
* `uname -a` : Linux hostname 5.0.16-100.fc28.x86_64 #1 SMP Tue May 14 18:22:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Fedora 28 (Workstation Edition)
* Installation done through downloading a .tar.gz on the releases page

Possible related issue : https://github.com/gohugoio/hugo/issues/6156

For now, I'm just going to downgrade to v0.55 as a workaround, but I suppose that it's pretty important from a user onboarding perspective to fix that.

Feel free to ask if I can be of any help (e.g. to provide a reproduction setup, etc…)

**Comment by bep** [comment] 2019-08-10 12:04
Duplicate of #6157 and #6162

**Closed by bep** 2019-08-10 12:04 UTC
