### ISSUE TITLE
Markdown does not render in figure shortcode

### ISSUE THREAD

**Issue by ahelwer** [gohugoio/hugo#6580] opened 2019-12-04 18:25 UTC
### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.60.1-96066756 windows/amd64 BuildDate: 2019-11-29T14:57:23Z

</pre>

### Does this issue reproduce with the latest release?

Yes

### Issue

I wrote the following figure shortcode:

```
{{< figure src="/img/imagename.png" caption="Image caption (Source: [Website Name](https://www.example.com))" >}}
```

I expected the markdown in the caption to be rendered, [as documented](https://gohugo.io/content-management/shortcodes/#figure). After running the `hugo` command locally, it generates this output:

```
<div class="box" >
  <figure  itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
    <div class="img">
      <img itemprop="thumbnail" src="https://ahelwer.gitlab.io/img/imagename.png" alt="Image caption (Source: [Website Name](https://www.example.com/))"/>
    </div>
      <figcaption>
          <p>Image caption (Source: [Website Name](https://www.example.com/))</p>
      </figcaption>
    <a href="https://ahelwer.gitlab.io/img/imagename.png" itemprop="contentUrl"></a>
  </figure>
</div>
```

So the markdown is not rendered. I see the related feature request #4406 was closed as completed last year.

**Comment by bep** [comment] 2019-12-04 18:29
I assume this is the same as #6573 

What you have is HTML. You can:

* Switch to Blackfriday as MD renderer (see docs)
* Write HTML (I would recommend this)
* Or you can read what CommonMark spec says about this, and consider opening an issue here:  https://github.com/yuin/goldmark/

**Comment by ahelwer** [comment] 2019-12-04 18:42
So this is more a bug with the docs than a bug with Hugo itself?

**Comment by bep** [comment] 2019-12-04 18:44
I'm not sure how to label it. We replaced Blackfriday with Goldmark as the default Markdown engine a week ago. GoldMark is CommonMark compliant and very very good. But while it fixes a lot of issues, it is also stricter in some areas.

**Comment by kaushalmodi** [comment] 2019-12-04 20:27
@ahelwer FWIW, I cannot reproduce the issue on Hugo v0.60.1 or v0.61.0-DEV.

I use this exact shortcode as you:

```
{{< figure src="/img/imagename.png" caption="Image caption (Source: [Website Name](https://www.example.com))" >}}
```

and this is the generated HTML:

```html
<figure>
    <img src="http://localhost:5555/img/imagename.png"
         alt="Image caption (Source: Website Name)"/> <figcaption>
            <p>Image caption (Source: <a href="https://www.example.com">Website Name</a>)</p>
        </figcaption>
</figure>
```

**Comment by kaushalmodi** [comment] 2019-12-04 20:30
@ahelwer In your generated HTML, I see this:

```html
<div class="box" >
  <figure  itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
    <div class="img">
```

Where is that coming from? The [default Hugo `figure` shortcode][1] does not do that. May be you are using a custom `figure` shortcode?

[1]: https://github.com/gohugoio/hugo/blob/aba2647c152ffff927f42523b77ee6651630cd67/tpl/tplimpl/embedded/templates/shortcodes/figure.html

**Comment by kaushalmodi** [comment] 2019-12-04 20:33
> May be you are using a custom figure shortcode?

Yep.. try deleting [this custom `figure` shortcode][1] from your site's theme.

You will need to open an issue in that theme's repo to have it fixed for GoldMark (Hugo v0.60+).

[1]: https://gitlab.com/ahelwer/ahelwer.gitlab.io/blob/master/themes/beautifulhugo/layouts/shortcodes/figure.html

**Comment by kaushalmodi** [comment] 2019-12-04 20:35
Actually the fix is simple.. in [this line][1], simply change it to `{{- .Get "caption" | markdownify -}}` as in the [default Hugo `figure`][2].

[1]: https://gitlab.com/ahelwer/ahelwer.gitlab.io/blob/e373b46b5fe190f63224df884707b1b2a839dfaf/themes/beautifulhugo/layouts/shortcodes/figure.html#L21

[2]: https://github.com/gohugoio/hugo/blob/aba2647c152ffff927f42523b77ee6651630cd67/tpl/tplimpl/embedded/templates/shortcodes/figure.html#L19

**Comment by ahelwer** [comment] 2019-12-04 20:36
Ah yes, I deleted the figure.html file in the themes/beautifulhugo/layouts/shortcodes directory and now it works! I forked my repo directly from the example Hugo GitLab page (https://gitlab.com/pages/hugo); thank you!

**Comment by kaushalmodi** [comment] 2019-12-04 20:36
Related: https://github.com/gohugoio/hugo/issues/4406.. this issue was originally present in Hugo but I fixed it a while back 😉

**Comment by kaushalmodi** [comment] 2019-12-04 20:38
> I forked my repo directly from the example Hugo GitLab page (https://gitlab.com/pages/hugo); 

You can then close this issue here. But to help the community, do open this issue on the beautifulhugo theme repo.

> thank you!

You're welcome.

**Comment by ahelwer** [comment] 2019-12-04 20:42
Unfortunately your proposed in-place fix doesn't quite work for me; it renders like this:

![image](https://user-images.githubusercontent.com/718765/70179639-3dbcac00-1693-11ea-928f-d6a2120f0f2f.png)

Here is the shortcode:

```
{{< figure src="/img/chsh/mob.jpeg" caption="Enraged Bohmian Mechanics enthusiasts approach the comment section (Source: [Wellcome Collection](https://wellcomecollection.org/))" >}}
```

Plus associated HTML:

```
<link rel="stylesheet" href="https://ahelwer.ca/css/hugo-easy-gallery.css" />
<div class="box" >
  <figure  itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
    <div class="img">
      <img itemprop="thumbnail" src="https://ahelwer.ca/img/chsh/mob.jpeg" alt="Enraged Bohmian Mechanics enthusiasts approach the comment section (Source: [Wellcome Collection](https://wellcomecollection.org/))"/>
    </div>
      <figcaption>
          <p>Enraged Bohmian Mechanics enthusiasts approach the comment section (Source: <a href="https://wellcomecollection.org/">Wellcome Collection</a>)</p>
      </figcaption>
    <a href="https://ahelwer.ca/img/chsh/mob.jpeg" itemprop="contentUrl"></a>
  </figure>
</div>
```

**Comment by kaushalmodi** [comment] 2019-12-04 20:43
The HTML looks fine.. seems like you need to fix some CSS? In any case, you should now move this discussion to the Hugo Discourse forum.

**Closed** 2019-12-04 20:44 UTC

**Comment by ahelwer** [comment] 2019-12-04 20:48
Issue opened against GitLab Pages Hugo example repo here: https://gitlab.com/pages/hugo/issues/43

**Comment by kaushalmodi** [comment] 2019-12-04 20:50
@ahelwer No, it needs to be opened on that's specific theme's repo: https://github.com/halogenica/beautifulhugo

**Comment by kaushalmodi** [comment] 2019-12-04 20:51
You essentially cloned the markdown-not-respecting `figure` shortcode from there: https://github.com/halogenica/beautifulhugo/blob/master/layouts/shortcodes/figure.html
